//! flutter_rust_bridge adapter for `lfs_core`.
//!
//! Thin pass-through layer: every public item here delegates to
//! `lfs_core` and adds nothing beyond Dart-friendly type marshalling
//! (handle IDs, error mapping, FRB Stream wrapping). Keep it boring —
//! logic belongs in `lfs_core`, this crate is just the bridge.

pub mod api;

// Generated by `flutter_rust_bridge_codegen generate` (`make rust-codegen`)
// from the `pub mod api` surface above. Edit the API surface, run
// codegen, then stage both this file and `lib/src/rust/` together.
mod frb_generated;
