// Mocks generated by Mockito 5.4.6 from annotations
// in letsflutssh/test/core/sftp/sftp_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i10;

import 'package:dartssh2/src/sftp/sftp_client.dart' as _i2;
import 'package:dartssh2/src/sftp/sftp_file_attrs.dart' as _i3;
import 'package:dartssh2/src/sftp/sftp_file_open_mode.dart' as _i7;
import 'package:dartssh2/src/sftp/sftp_name.dart' as _i8;
import 'package:dartssh2/src/sftp/sftp_statvfs.dart' as _i4;
import 'package:dartssh2/src/sftp/sftp_stream_io.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSftpHandsake_0 extends _i1.SmartFake implements _i2.SftpHandsake {
  _FakeSftpHandsake_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSftpFileAttrs_1 extends _i1.SmartFake implements _i3.SftpFileAttrs {
  _FakeSftpFileAttrs_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSftpFile_2 extends _i1.SmartFake implements _i2.SftpFile {
  _FakeSftpFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSftpStatVfs_3 extends _i1.SmartFake implements _i4.SftpStatVfs {
  _FakeSftpStatVfs_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSftpFileWriter_4 extends _i1.SmartFake
    implements _i5.SftpFileWriter {
  _FakeSftpFileWriter_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SftpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSftpClient extends _i1.Mock implements _i2.SftpClient {
  @override
  _i6.Future<_i2.SftpHandsake> get handshake =>
      (super.noSuchMethod(
            Invocation.getter(#handshake),
            returnValue: _i6.Future<_i2.SftpHandsake>.value(
              _FakeSftpHandsake_0(this, Invocation.getter(#handshake)),
            ),
            returnValueForMissingStub: _i6.Future<_i2.SftpHandsake>.value(
              _FakeSftpHandsake_0(this, Invocation.getter(#handshake)),
            ),
          )
          as _i6.Future<_i2.SftpHandsake>);

  @override
  _i6.Future<_i3.SftpFileAttrs> stat(String? path, {bool? followLink = true}) =>
      (super.noSuchMethod(
            Invocation.method(#stat, [path], {#followLink: followLink}),
            returnValue: _i6.Future<_i3.SftpFileAttrs>.value(
              _FakeSftpFileAttrs_1(
                this,
                Invocation.method(#stat, [path], {#followLink: followLink}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.SftpFileAttrs>.value(
              _FakeSftpFileAttrs_1(
                this,
                Invocation.method(#stat, [path], {#followLink: followLink}),
              ),
            ),
          )
          as _i6.Future<_i3.SftpFileAttrs>);

  @override
  _i6.Future<void> setStat(String? path, _i3.SftpFileAttrs? attrs) =>
      (super.noSuchMethod(
            Invocation.method(#setStat, [path, attrs]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.SftpFile> open(
    String? path, {
    _i7.SftpFileOpenMode? mode = _i7.SftpFileOpenMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [path], {#mode: mode}),
            returnValue: _i6.Future<_i2.SftpFile>.value(
              _FakeSftpFile_2(
                this,
                Invocation.method(#open, [path], {#mode: mode}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.SftpFile>.value(
              _FakeSftpFile_2(
                this,
                Invocation.method(#open, [path], {#mode: mode}),
              ),
            ),
          )
          as _i6.Future<_i2.SftpFile>);

  @override
  _i6.Future<int> download(
    String? path,
    _i6.StreamSink<List<int>>? destination, {
    int? length,
    int? offset = 0,
    void Function(int)? onProgress,
    int? chunkSize = 65536,
    int? maxPendingRequests = 128,
    bool? closeDestination = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [path, destination],
              {
                #length: length,
                #offset: offset,
                #onProgress: onProgress,
                #chunkSize: chunkSize,
                #maxPendingRequests: maxPendingRequests,
                #closeDestination: closeDestination,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Stream<List<_i8.SftpName>> readdir(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#readdir, [path]),
            returnValue: _i6.Stream<List<_i8.SftpName>>.empty(),
            returnValueForMissingStub: _i6.Stream<List<_i8.SftpName>>.empty(),
          )
          as _i6.Stream<List<_i8.SftpName>>);

  @override
  _i6.Future<List<_i8.SftpName>> listdir(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#listdir, [path]),
            returnValue: _i6.Future<List<_i8.SftpName>>.value(<_i8.SftpName>[]),
            returnValueForMissingStub: _i6.Future<List<_i8.SftpName>>.value(
              <_i8.SftpName>[],
            ),
          )
          as _i6.Future<List<_i8.SftpName>>);

  @override
  _i6.Future<void> remove(String? filename) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [filename]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> mkdir(String? path, [_i3.SftpFileAttrs? attrs]) =>
      (super.noSuchMethod(
            Invocation.method(#mkdir, [path, attrs]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> rmdir(String? dirname) =>
      (super.noSuchMethod(
            Invocation.method(#rmdir, [dirname]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> absolute(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#absolute, [path]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#absolute, [path]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#absolute, [path]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> rename(String? oldPath, String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [oldPath, newPath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> readlink(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#readlink, [path]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#readlink, [path]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#readlink, [path]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> link(String? linkPath, String? targetPath) =>
      (super.noSuchMethod(
            Invocation.method(#link, [linkPath, targetPath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.SftpStatVfs> statvfs(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#statvfs, [path]),
            returnValue: _i6.Future<_i4.SftpStatVfs>.value(
              _FakeSftpStatVfs_3(this, Invocation.method(#statvfs, [path])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.SftpStatVfs>.value(
              _FakeSftpStatVfs_3(this, Invocation.method(#statvfs, [path])),
            ),
          )
          as _i6.Future<_i4.SftpStatVfs>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SftpFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockSftpFile extends _i1.Mock implements _i2.SftpFile {
  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.SftpFileAttrs> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i6.Future<_i3.SftpFileAttrs>.value(
              _FakeSftpFileAttrs_1(this, Invocation.method(#stat, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i3.SftpFileAttrs>.value(
              _FakeSftpFileAttrs_1(this, Invocation.method(#stat, [])),
            ),
          )
          as _i6.Future<_i3.SftpFileAttrs>);

  @override
  _i6.Future<void> setStat(_i3.SftpFileAttrs? attrs) =>
      (super.noSuchMethod(
            Invocation.method(#setStat, [attrs]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<_i10.Uint8List> read({
    int? length,
    int? offset = 0,
    void Function(int)? onProgress,
    int? chunkSize = 16384,
    int? maxPendingRequests = 64,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #length: length,
              #offset: offset,
              #onProgress: onProgress,
              #chunkSize: chunkSize,
              #maxPendingRequests: maxPendingRequests,
            }),
            returnValue: _i6.Stream<_i10.Uint8List>.empty(),
            returnValueForMissingStub: _i6.Stream<_i10.Uint8List>.empty(),
          )
          as _i6.Stream<_i10.Uint8List>);

  @override
  _i6.Future<int> downloadTo(
    _i6.StreamSink<List<int>>? destination, {
    int? length,
    int? offset = 0,
    void Function(int)? onProgress,
    int? chunkSize = 65536,
    int? maxPendingRequests = 128,
    bool? closeDestination = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadTo,
              [destination],
              {
                #length: length,
                #offset: offset,
                #onProgress: onProgress,
                #chunkSize: chunkSize,
                #maxPendingRequests: maxPendingRequests,
                #closeDestination: closeDestination,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i10.Uint8List> readBytes({int? length, int? offset = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [], {
              #length: length,
              #offset: offset,
            }),
            returnValue: _i6.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
            returnValueForMissingStub: _i6.Future<_i10.Uint8List>.value(
              _i10.Uint8List(0),
            ),
          )
          as _i6.Future<_i10.Uint8List>);

  @override
  _i5.SftpFileWriter write(
    _i6.Stream<_i10.Uint8List>? stream, {
    int? offset = 0,
    void Function(int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #write,
              [stream],
              {#offset: offset, #onProgress: onProgress},
            ),
            returnValue: _FakeSftpFileWriter_4(
              this,
              Invocation.method(
                #write,
                [stream],
                {#offset: offset, #onProgress: onProgress},
              ),
            ),
            returnValueForMissingStub: _FakeSftpFileWriter_4(
              this,
              Invocation.method(
                #write,
                [stream],
                {#offset: offset, #onProgress: onProgress},
              ),
            ),
          )
          as _i5.SftpFileWriter);

  @override
  _i6.Future<void> writeBytes(_i10.Uint8List? data, {int? offset = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#writeBytes, [data], {#offset: offset}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.SftpStatVfs> statvfs() =>
      (super.noSuchMethod(
            Invocation.method(#statvfs, []),
            returnValue: _i6.Future<_i4.SftpStatVfs>.value(
              _FakeSftpStatVfs_3(this, Invocation.method(#statvfs, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.SftpStatVfs>.value(
              _FakeSftpStatVfs_3(this, Invocation.method(#statvfs, [])),
            ),
          )
          as _i6.Future<_i4.SftpStatVfs>);
}
