// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Compose, (optionally) encrypt, and atomically write the `.lfs`
/// archive entirely inside Rust. Plaintext credentials never cross
/// the FRB boundary outbound: the bytes flow DB → JSON → ZIP →
/// AES-GCM → atomic file write under `output_path`. Returns the
/// archive byte count so the caller can log or surface progress
/// without re-stat'ing the file. Atomic via
/// [`lfs_core::path::write_bytes_atomic`] (tmp + fsync + rename +
/// parent-dir fsync), so a crash mid-write leaves the previous
/// file at `output_path` (or no file when none existed). The Dart
/// caller no longer maintains its own tmp + writeAsBytes + rename
/// discipline.
Future<PlatformInt64> dbExportArchive({
  required DbExportInput input,
  required String outputPath,
}) => RustLib.instance.api.crateApiArchiveDbExportArchive(
  input: input,
  outputPath: outputPath,
);

/// Size of the `.lfs` archive bytes for the current selection
/// without running Argon2id KDF or AES-GCM encryption — drives the
/// live "archive size" preview line in the export dialog. Reads
/// sessions / keys / tags / snippets straight from the open
/// SQLCipher connection by id, so manager-key PEM never crosses
/// the FRB boundary into Dart memory for the gauge.
///
/// Sync — composition is a few hundred clones + the ZIP STORED-
/// mode write pass, sub-millisecond on realistic export
/// selections. The dialog calls this on every checkbox toggle so
/// the no-async-hop overhead matters; `master_password` is only
/// consulted to decide whether to add the LFSE envelope's fixed
/// 75-byte overhead constant — the bytes themselves are never
/// inspected, so the dialog can pass an empty `Vec<u8>` until the
/// user reaches the password prompt.
int dbLfsExportSize({required DbExportInput input}) =>
    RustLib.instance.api.crateApiArchiveDbLfsExportSize(input: input);

/// Same composition as [`db_export_qr_payload`] but skips the
/// base64url encode step and returns the deflated payload's
/// byte count. Drives the live "fits in QR" gauge in the Dart
/// `unified_export_controller` — single FRB call per checkbox
/// toggle replaces the per-toggle Dart-side JSON build + Rust
/// deflate round-trip the controller used to do.
Future<int> dbExportQrPayloadSize({required DbQrExportInput input}) =>
    RustLib.instance.api.crateApiArchiveDbExportQrPayloadSize(input: input);

/// Build the QR deeplink payload (`d=` value) entirely Rust-side.
/// Returns the deflated + base64url-encoded ASCII string ready to
/// hand to a QR widget. Plaintext credential bytes — manager-key
/// PEM, session passwords — flow DB → JSON → deflate → base64
/// inside Rust so the Dart heap only sees the encoded ASCII.
Future<String> dbExportQrPayload({required DbQrExportInput input}) =>
    RustLib.instance.api.crateApiArchiveDbExportQrPayload(input: input);

/// Classify the file at `path`. Pure best-effort: any I/O / parse
/// error collapses to `NotLfs` so the caller surfaces a single
/// rejection. The probe stays sub-millisecond on small files
/// (header read + size stat) and milliseconds on large plain ZIPs
/// (entry-list scan); blocking-pool wrapped to keep the FRB worker
/// thread free.
Future<DbArchiveProbeKind> dbArchiveProbe({required String path}) =>
    RustLib.instance.api.crateApiArchiveDbArchiveProbe(path: path);

Future<DbImportOpenResult> qrImportOpen({required String payload}) =>
    RustLib.instance.api.crateApiArchiveQrImportOpen(payload: payload);

/// Open and decrypt a `.lfs` archive (or a raw ZIP for the
/// no-password export shape). Stages the decoded entries inside
/// `AppState::imports` under a freshly-generated handle id and
/// returns the sanitised preview. Plaintext payload (sessions,
/// keys, …) stays Rust-side; the Dart caller only sees counts
/// + labels until it hands the handle back to the apply driver.
///
/// `password` empty → assumes a raw-ZIP archive (matches the
/// "no encryption" export branch). Wrong password / malformed
/// envelope surfaces as an error and no handle is registered.
Future<DbImportOpenResult> dbImportOpen({
  required String path,
  required List<int> password,
}) => RustLib.instance.api.crateApiArchiveDbImportOpen(
  path: path,
  password: password,
);

/// Stage a [`DbStagedImport`] into the registry under a
/// freshly-minted handle id. Returns the handle so the caller
/// can hand it back to [`db_import_apply`] / [`db_import_drop`].
/// Skips the LFSE decrypt + zip parse — the caller's already
/// done that work or has built the JSONs locally (QR import,
/// OpenSSH parser).
Future<String> dbImportStage({required DbStagedImport input}) =>
    RustLib.instance.api.crateApiArchiveDbImportStage(input: input);

/// Drop the staged archive without applying it. Idempotent on a
/// missing handle id. Pair with [`db_import_open`] /
/// [`db_import_stage`] from the Dart side: cancel button on the
/// preview dialog calls this; OK button hands the id to
/// [`db_import_apply`].
Future<void> dbImportDrop({required String handleId}) =>
    RustLib.instance.api.crateApiArchiveDbImportDrop(handleId: handleId);

/// Commit the staged archive to the DB in merge mode. The
/// handle is consumed (taken out of the registry) on success;
/// on parse failure the registry keeps the entry so the caller
/// can retry / drop. `created_at_ms` stamps the rows that don't
/// carry their own timestamp in the archive.
Future<DbApplyResult> dbImportApply({
  required String handleId,
  required DbApplyOptions options,
  required PlatformInt64 createdAtMs,
}) => RustLib.instance.api.crateApiArchiveDbImportApply(
  handleId: handleId,
  options: options,
  createdAtMs: createdAtMs,
);

/// Apply-time toggles. Each flag enables the matching entry kind
/// regardless of what the archive carries — the apply driver
/// silently no-ops on missing JSON entries.
class DbApplyOptions {
  final DbImportMode mode;
  final bool applySessions;
  final bool applyKeys;
  final bool applyTags;
  final bool applySnippets;
  final bool applyKnownHosts;

  const DbApplyOptions({
    required this.mode,
    required this.applySessions,
    required this.applyKeys,
    required this.applyTags,
    required this.applySnippets,
    required this.applyKnownHosts,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      applySessions.hashCode ^
      applyKeys.hashCode ^
      applyTags.hashCode ^
      applySnippets.hashCode ^
      applyKnownHosts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbApplyOptions &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          applySessions == other.applySessions &&
          applyKeys == other.applyKeys &&
          applyTags == other.applyTags &&
          applySnippets == other.applySnippets &&
          applyKnownHosts == other.applyKnownHosts;
}

/// Counters returned by [`db_import_apply`]. Mirrors
/// `lfs_core::archive::ApplyResult` field-for-field.
///
/// `config_json` carries the staged `config.json` payload back to
/// the Dart caller — `config.json` is a Dart-managed file artefact,
/// not a DB row, so the apply driver leaves it alone and returns
/// the JSON for the caller to parse + restore. Only populated when
/// the staged archive carried a config entry; `None` otherwise.
class DbApplyResult {
  final PlatformInt64 sessionsApplied;
  final PlatformInt64 keysApplied;
  final PlatformInt64 keysSkippedDedup;
  final PlatformInt64 tagsApplied;
  final PlatformInt64 snippetsApplied;
  final PlatformInt64 knownHostsApplied;
  final PlatformInt64 foldersApplied;
  final PlatformInt64 sessionTagsApplied;
  final PlatformInt64 folderTagsApplied;
  final PlatformInt64 sessionSnippetsApplied;
  final List<String> errors;
  final String? configJson;

  /// Replace-mode-only flag. True when the apply driver hit a
  /// per-row error and rolled the whole transaction back so the
  /// user's pre-import state survives. Caller MUST treat this
  /// as a hard failure (display `errors`, do not act on the
  /// `*_applied` counters) rather than a partial success.
  final bool rolledBack;

  const DbApplyResult({
    required this.sessionsApplied,
    required this.keysApplied,
    required this.keysSkippedDedup,
    required this.tagsApplied,
    required this.snippetsApplied,
    required this.knownHostsApplied,
    required this.foldersApplied,
    required this.sessionTagsApplied,
    required this.folderTagsApplied,
    required this.sessionSnippetsApplied,
    required this.errors,
    this.configJson,
    required this.rolledBack,
  });

  @override
  int get hashCode =>
      sessionsApplied.hashCode ^
      keysApplied.hashCode ^
      keysSkippedDedup.hashCode ^
      tagsApplied.hashCode ^
      snippetsApplied.hashCode ^
      knownHostsApplied.hashCode ^
      foldersApplied.hashCode ^
      sessionTagsApplied.hashCode ^
      folderTagsApplied.hashCode ^
      sessionSnippetsApplied.hashCode ^
      errors.hashCode ^
      configJson.hashCode ^
      rolledBack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbApplyResult &&
          runtimeType == other.runtimeType &&
          sessionsApplied == other.sessionsApplied &&
          keysApplied == other.keysApplied &&
          keysSkippedDedup == other.keysSkippedDedup &&
          tagsApplied == other.tagsApplied &&
          snippetsApplied == other.snippetsApplied &&
          knownHostsApplied == other.knownHostsApplied &&
          foldersApplied == other.foldersApplied &&
          sessionTagsApplied == other.sessionTagsApplied &&
          folderTagsApplied == other.folderTagsApplied &&
          sessionSnippetsApplied == other.sessionSnippetsApplied &&
          errors == other.errors &&
          configJson == other.configJson &&
          rolledBack == other.rolledBack;
}

/// Decode a QR / paste-link payload (deflated + base64url JSON,
/// or v1 legacy raw base64url JSON), stage the resulting
/// `PendingImport` under a freshly-generated handle id, and
/// return the sanitised preview. Mirrors `db_import_open` for
/// the QR / deeplink paths so the apply driver sees the same
/// shape regardless of whether the bytes came from a `.lfs`
/// archive or a QR scan.
///
/// `payload` is the value of the `d=` query parameter from a
/// `letsflutssh://import?d=...` deeplink. The Dart caller may
/// also pass the full URI — the leading `letsflutssh://import?d=`
/// is stripped automatically.
/// Pre-decrypt classifier for a candidate `.lfs` file. Mirrors
/// `lfs_core::archive::probe::ProbeKind` so the Dart file-picker
/// can branch on a typed enum without having to interpret a magic
/// byte / size threshold itself.
enum DbArchiveProbeKind {
  /// Doesn't start with the ZIP local-file-header magic — almost
  /// certainly an encrypted `.lfs` (random 32-byte salt prefix).
  /// Caller surfaces the password prompt.
  encryptedLfs,

  /// Plain ZIP carrying at least one of our marker entries.
  /// Caller imports without a password.
  unencryptedLfs,

  /// Anything else — non-ZIP, ZIP without our markers (an `.apk`
  /// picked by mistake), file too big, malformed ZIP, missing
  /// file. Caller refuses the import with a friendly toast.
  notLfs,
}

/// Mirror of `ExportInput`. Pulled verbatim across the FRB
/// boundary; the orchestrator owns the actual archive composition.
class DbExportInput {
  final DbExportOptions options;
  final List<String> selectedSessionIds;
  final List<String> selectedEmptyFolders;
  final String configJson;
  final PlatformInt64 schemaVersion;
  final String? appVersion;

  /// Empty bytes → no encryption, raw ZIP. Non-empty → an
  /// Argon2id + AES-GCM envelope under the canonical
  /// `LFSE`-magic header. Wire shape is `Vec<u8>` so the Dart
  /// caller stays on `Uint8List.fromList(utf8.encode(text))`,
  /// mirroring the master-password / keychain-gate /
  /// tier-orchestrator family.
  final Uint8List masterPassword;
  final int kdfMemoryKib;
  final int kdfIterations;
  final int kdfParallelism;
  final PlatformInt64 createdAtMs;

  const DbExportInput({
    required this.options,
    required this.selectedSessionIds,
    required this.selectedEmptyFolders,
    required this.configJson,
    required this.schemaVersion,
    this.appVersion,
    required this.masterPassword,
    required this.kdfMemoryKib,
    required this.kdfIterations,
    required this.kdfParallelism,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      options.hashCode ^
      selectedSessionIds.hashCode ^
      selectedEmptyFolders.hashCode ^
      configJson.hashCode ^
      schemaVersion.hashCode ^
      appVersion.hashCode ^
      masterPassword.hashCode ^
      kdfMemoryKib.hashCode ^
      kdfIterations.hashCode ^
      kdfParallelism.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbExportInput &&
          runtimeType == other.runtimeType &&
          options == other.options &&
          selectedSessionIds == other.selectedSessionIds &&
          selectedEmptyFolders == other.selectedEmptyFolders &&
          configJson == other.configJson &&
          schemaVersion == other.schemaVersion &&
          appVersion == other.appVersion &&
          masterPassword == other.masterPassword &&
          kdfMemoryKib == other.kdfMemoryKib &&
          kdfIterations == other.kdfIterations &&
          kdfParallelism == other.kdfParallelism &&
          createdAtMs == other.createdAtMs;
}

/// Mirror of `ExportOptions` over the FRB boundary. Field-for-field
/// copy of the Dart `ExportOptions` toggle bag.
class DbExportOptions {
  final bool includeSessions;
  final bool includeKnownHosts;
  final bool includeConfig;
  final bool includeTags;
  final bool includeSnippets;
  final bool includeAllManagerKeys;
  final bool hasManagerKeys;

  const DbExportOptions({
    required this.includeSessions,
    required this.includeKnownHosts,
    required this.includeConfig,
    required this.includeTags,
    required this.includeSnippets,
    required this.includeAllManagerKeys,
    required this.hasManagerKeys,
  });

  @override
  int get hashCode =>
      includeSessions.hashCode ^
      includeKnownHosts.hashCode ^
      includeConfig.hashCode ^
      includeTags.hashCode ^
      includeSnippets.hashCode ^
      includeAllManagerKeys.hashCode ^
      hasManagerKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbExportOptions &&
          runtimeType == other.runtimeType &&
          includeSessions == other.includeSessions &&
          includeKnownHosts == other.includeKnownHosts &&
          includeConfig == other.includeConfig &&
          includeTags == other.includeTags &&
          includeSnippets == other.includeSnippets &&
          includeAllManagerKeys == other.includeAllManagerKeys &&
          hasManagerKeys == other.hasManagerKeys;
}

/// Mirror of `lfs_core::archive::ImportMode`.
enum DbImportMode { merge, replace }

/// Result of a successful preview — the registered handle id
/// the Dart caller passes back to the apply / drop endpoints,
/// plus the sanitised preview.
class DbImportOpenResult {
  final String handleId;
  final DbImportPreview preview;

  const DbImportOpenResult({required this.handleId, required this.preview});

  @override
  int get hashCode => handleId.hashCode ^ preview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbImportOpenResult &&
          runtimeType == other.runtimeType &&
          handleId == other.handleId &&
          preview == other.preview;
}

/// FRB mirror of `lfs_core::archive::ImportPreview`. Sanitised
/// counts + session labels — the apply side reads the full
/// payload from the registry handle, so the preview is the only
/// thing that crosses the boundary outwards.
class DbImportPreview {
  final PlatformInt64 schemaVersion;
  final PlatformInt64 sessionCount;
  final List<String> sessionLabels;
  final PlatformInt64 managerKeyCount;
  final PlatformInt64 tagCount;
  final PlatformInt64 snippetCount;
  final PlatformInt64 emptyFolderCount;
  final bool hasConfig;
  final bool hasKnownHosts;

  const DbImportPreview({
    required this.schemaVersion,
    required this.sessionCount,
    required this.sessionLabels,
    required this.managerKeyCount,
    required this.tagCount,
    required this.snippetCount,
    required this.emptyFolderCount,
    required this.hasConfig,
    required this.hasKnownHosts,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      sessionCount.hashCode ^
      sessionLabels.hashCode ^
      managerKeyCount.hashCode ^
      tagCount.hashCode ^
      snippetCount.hashCode ^
      emptyFolderCount.hashCode ^
      hasConfig.hashCode ^
      hasKnownHosts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbImportPreview &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          sessionCount == other.sessionCount &&
          sessionLabels == other.sessionLabels &&
          managerKeyCount == other.managerKeyCount &&
          tagCount == other.tagCount &&
          snippetCount == other.snippetCount &&
          emptyFolderCount == other.emptyFolderCount &&
          hasConfig == other.hasConfig &&
          hasKnownHosts == other.hasKnownHosts;
}

class DbQrExportInput {
  final DbQrExportOptions options;
  final List<String> selectedSessionIds;
  final List<String> selectedEmptyFolders;
  final String? configJson;

  const DbQrExportInput({
    required this.options,
    required this.selectedSessionIds,
    required this.selectedEmptyFolders,
    this.configJson,
  });

  @override
  int get hashCode =>
      options.hashCode ^
      selectedSessionIds.hashCode ^
      selectedEmptyFolders.hashCode ^
      configJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbQrExportInput &&
          runtimeType == other.runtimeType &&
          options == other.options &&
          selectedSessionIds == other.selectedSessionIds &&
          selectedEmptyFolders == other.selectedEmptyFolders &&
          configJson == other.configJson;
}

/// Mirror of `QrExportOptions` over the FRB boundary.
class DbQrExportOptions {
  final bool includeSessions;
  final bool includeConfig;
  final bool includeKnownHosts;
  final bool includePasswords;
  final bool includeEmbeddedKeys;
  final bool includeManagerKeys;
  final bool includeAllManagerKeys;
  final bool includeTags;
  final bool includeSnippets;

  const DbQrExportOptions({
    required this.includeSessions,
    required this.includeConfig,
    required this.includeKnownHosts,
    required this.includePasswords,
    required this.includeEmbeddedKeys,
    required this.includeManagerKeys,
    required this.includeAllManagerKeys,
    required this.includeTags,
    required this.includeSnippets,
  });

  @override
  int get hashCode =>
      includeSessions.hashCode ^
      includeConfig.hashCode ^
      includeKnownHosts.hashCode ^
      includePasswords.hashCode ^
      includeEmbeddedKeys.hashCode ^
      includeManagerKeys.hashCode ^
      includeAllManagerKeys.hashCode ^
      includeTags.hashCode ^
      includeSnippets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbQrExportOptions &&
          runtimeType == other.runtimeType &&
          includeSessions == other.includeSessions &&
          includeConfig == other.includeConfig &&
          includeKnownHosts == other.includeKnownHosts &&
          includePasswords == other.includePasswords &&
          includeEmbeddedKeys == other.includeEmbeddedKeys &&
          includeManagerKeys == other.includeManagerKeys &&
          includeAllManagerKeys == other.includeAllManagerKeys &&
          includeTags == other.includeTags &&
          includeSnippets == other.includeSnippets;
}

/// Pre-parsed JSON entries staged directly in the import
/// registry, bypassing the LFSE decrypt + zip parse path.
/// Used by Dart consumers that already hold the JSON payloads
/// in memory (QR import, OpenSSH import, the legacy Dart-side
/// archive decrypt flow) so they can route the apply step
/// through the Rust driver without round-tripping the bytes
/// back through a temp file.
///
/// Every field is optional — missing entries no-op on the
/// apply side, same as the LFSE path.
class DbStagedImport {
  final String? manifestJson;
  final String? sessionsJson;
  final String? keysJson;
  final String? tagsJson;
  final String? sessionTagsJson;
  final String? folderTagsJson;
  final String? snippetsJson;
  final String? sessionSnippetsJson;
  final String? emptyFoldersJson;
  final String? configJson;
  final String? knownHostsText;

  const DbStagedImport({
    this.manifestJson,
    this.sessionsJson,
    this.keysJson,
    this.tagsJson,
    this.sessionTagsJson,
    this.folderTagsJson,
    this.snippetsJson,
    this.sessionSnippetsJson,
    this.emptyFoldersJson,
    this.configJson,
    this.knownHostsText,
  });

  @override
  int get hashCode =>
      manifestJson.hashCode ^
      sessionsJson.hashCode ^
      keysJson.hashCode ^
      tagsJson.hashCode ^
      sessionTagsJson.hashCode ^
      folderTagsJson.hashCode ^
      snippetsJson.hashCode ^
      sessionSnippetsJson.hashCode ^
      emptyFoldersJson.hashCode ^
      configJson.hashCode ^
      knownHostsText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbStagedImport &&
          runtimeType == other.runtimeType &&
          manifestJson == other.manifestJson &&
          sessionsJson == other.sessionsJson &&
          keysJson == other.keysJson &&
          tagsJson == other.tagsJson &&
          sessionTagsJson == other.sessionTagsJson &&
          folderTagsJson == other.folderTagsJson &&
          snippetsJson == other.snippetsJson &&
          sessionSnippetsJson == other.sessionSnippetsJson &&
          emptyFoldersJson == other.emptyFoldersJson &&
          configJson == other.configJson &&
          knownHostsText == other.knownHostsText;
}
