// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `require_db`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Compose and (optionally) encrypt the `.lfs` archive entirely
/// inside Rust. Plaintext credentials never cross the FRB boundary
/// outbound — the bytes flow DB → JSON → ZIP → AES-GCM and only the
/// finished archive returns to Dart.
Future<Uint8List> dbExportArchive({required DbExportInput input}) =>
    RustLib.instance.api.crateApiArchiveDbExportArchive(input: input);

/// Mirror of `ExportInput`. Pulled verbatim across the FRB
/// boundary; the orchestrator owns the actual archive composition.
class DbExportInput {
  final DbExportOptions options;
  final List<String> selectedSessionIds;
  final List<String> selectedEmptyFolders;
  final String configJson;
  final PlatformInt64 schemaVersion;
  final String? appVersion;

  /// Empty string → no encryption, raw ZIP. Non-empty → Argon2id
  /// + AES-GCM envelope under the canonical `LFSE`-magic header.
  final String masterPassword;
  final int kdfMemoryKib;
  final int kdfIterations;
  final int kdfParallelism;
  final PlatformInt64 createdAtMs;

  const DbExportInput({
    required this.options,
    required this.selectedSessionIds,
    required this.selectedEmptyFolders,
    required this.configJson,
    required this.schemaVersion,
    this.appVersion,
    required this.masterPassword,
    required this.kdfMemoryKib,
    required this.kdfIterations,
    required this.kdfParallelism,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      options.hashCode ^
      selectedSessionIds.hashCode ^
      selectedEmptyFolders.hashCode ^
      configJson.hashCode ^
      schemaVersion.hashCode ^
      appVersion.hashCode ^
      masterPassword.hashCode ^
      kdfMemoryKib.hashCode ^
      kdfIterations.hashCode ^
      kdfParallelism.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbExportInput &&
          runtimeType == other.runtimeType &&
          options == other.options &&
          selectedSessionIds == other.selectedSessionIds &&
          selectedEmptyFolders == other.selectedEmptyFolders &&
          configJson == other.configJson &&
          schemaVersion == other.schemaVersion &&
          appVersion == other.appVersion &&
          masterPassword == other.masterPassword &&
          kdfMemoryKib == other.kdfMemoryKib &&
          kdfIterations == other.kdfIterations &&
          kdfParallelism == other.kdfParallelism &&
          createdAtMs == other.createdAtMs;
}

/// Mirror of `ExportOptions` over the FRB boundary. Field-for-field
/// copy of the Dart `ExportOptions` toggle bag.
class DbExportOptions {
  final bool includeSessions;
  final bool includeKnownHosts;
  final bool includeConfig;
  final bool includeTags;
  final bool includeSnippets;
  final bool includeAllManagerKeys;
  final bool hasManagerKeys;

  const DbExportOptions({
    required this.includeSessions,
    required this.includeKnownHosts,
    required this.includeConfig,
    required this.includeTags,
    required this.includeSnippets,
    required this.includeAllManagerKeys,
    required this.hasManagerKeys,
  });

  @override
  int get hashCode =>
      includeSessions.hashCode ^
      includeKnownHosts.hashCode ^
      includeConfig.hashCode ^
      includeTags.hashCode ^
      includeSnippets.hashCode ^
      includeAllManagerKeys.hashCode ^
      hasManagerKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbExportOptions &&
          runtimeType == other.runtimeType &&
          includeSessions == other.includeSessions &&
          includeKnownHosts == other.includeKnownHosts &&
          includeConfig == other.includeConfig &&
          includeTags == other.includeTags &&
          includeSnippets == other.includeSnippets &&
          includeAllManagerKeys == other.includeAllManagerKeys &&
          hasManagerKeys == other.hasManagerKeys;
}
