// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'auth_compose.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Compose the credential overlay + return the typed ref the
/// connect actor dispatches against. Every secret byte stages
/// inside Rust — the Dart `ConnectionManager` no longer copies
/// plaintext through the SecretStore on the connect path.
Future<DbPreparedAuth> connectionPrepareAuth({
  required DbPrepareAuthInput input,
}) =>
    RustLib.instance.api.crateApiAuthComposeConnectionPrepareAuth(input: input);

/// FRB mirror of `lfs_core::connection::auth_compose::PrepareAuthInput`.
class DbPrepareAuthInput {
  final String? sessionId;
  final String keyId;
  final String keyData;
  final String password;
  final String passphrase;

  const DbPrepareAuthInput({
    this.sessionId,
    required this.keyId,
    required this.keyData,
    required this.password,
    required this.passphrase,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      keyId.hashCode ^
      keyData.hashCode ^
      password.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbPrepareAuthInput &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          keyId == other.keyId &&
          keyData == other.keyData &&
          password == other.password &&
          passphrase == other.passphrase;
}

class DbPreparedAuth {
  /// Tagged auth ref — Dart pattern-matches on the variant.
  final DbPreparedAuthRef auth;

  /// Every SecretStore id the caller must drop after the
  /// connect attempt settles. Empty when every staged secret
  /// belongs to a longer-lived owner (saved-session or
  /// manager-key without a typed passphrase).
  final List<String> transientSecretIds;

  const DbPreparedAuth({required this.auth, required this.transientSecretIds});

  @override
  int get hashCode => auth.hashCode ^ transientSecretIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbPreparedAuth &&
          runtimeType == other.runtimeType &&
          auth == other.auth &&
          transientSecretIds == other.transientSecretIds;
}

@freezed
sealed class DbPreparedAuthRef with _$DbPreparedAuthRef {
  const DbPreparedAuthRef._();

  /// Password auth — `secret_id` points at the staged password.
  const factory DbPreparedAuthRef.password({required String secretId}) =
      DbPreparedAuthRef_Password;

  /// Pubkey auth — `key_secret_id` points at the staged private
  /// key PEM. `passphrase_secret_id` is `Some(id)` when a
  /// passphrase was staged alongside; `None` for unencrypted keys.
  const factory DbPreparedAuthRef.pubkey({
    required String keySecretId,
    String? passphraseSecretId,
  }) = DbPreparedAuthRef_Pubkey;

  /// Pubkey + OpenSSH-certificate auth — `cert_secret_id` points
  /// at the staged cert blob paired with `key_secret_id`. Picked
  /// ahead of `Pubkey` whenever the manager key has a cert
  /// attached.
  const factory DbPreparedAuthRef.pubkeyCert({
    required String keySecretId,
    required String certSecretId,
    String? passphraseSecretId,
  }) = DbPreparedAuthRef_PubkeyCert;
}
