// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> biometricVaultLinuxTpmReady() =>
    RustLib.instance.api.crateApiBiometricKeyVaultBiometricVaultLinuxTpmReady();

Future<bool> biometricVaultLinuxIsStored() =>
    RustLib.instance.api.crateApiBiometricKeyVaultBiometricVaultLinuxIsStored();

/// Seal the SecretStore entry under `secret_id` into
/// `biometric_vault.tpm` (under the pinned support dir) keyed by the
/// current fprintd enrolment hash. Bytes never cross the FRB boundary.
Future<void> biometricVaultLinuxStoreFromSecret({required String secretId}) =>
    RustLib.instance.api
        .crateApiBiometricKeyVaultBiometricVaultLinuxStoreFromSecret(
          secretId: secretId,
        );

/// Unseal `biometric_vault.tpm` (under the pinned support dir) into
/// the SecretStore under `secret_id`. Returns `true` when bytes were
/// staged, `false` for "no vault on disk / fprintd unavailable / wrong
/// auth (re-enrolment)" — the caller routes those cases back to
/// the master-password dialog.
Future<bool> biometricVaultLinuxReadToSecret({required String secretId}) =>
    RustLib.instance.api
        .crateApiBiometricKeyVaultBiometricVaultLinuxReadToSecret(
          secretId: secretId,
        );

Future<void> biometricVaultLinuxClear() =>
    RustLib.instance.api.crateApiBiometricKeyVaultBiometricVaultLinuxClear();
