// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Resolve a pending biometric probe with the Dart-plugin
/// answer. `available` reflects `canCheckBiometrics() &&
/// hasEnrolment()`; `classifier_code` carries the per-platform
/// classifier (`ios_passcode_not_set` /
/// `android_no_enrolment` / `linux_no_fprintd` / etc) so the
/// UI shows an actionable hint. Empty when `available == true`.
///
/// Returns `true` when a receiver was actually woken; `false`
/// for an unknown / already-resolved prompt id.
bool biometricProbePromptResolve({
  required String promptId,
  required bool available,
  required String classifierCode,
}) => RustLib.instance.api
    .crateApiBiometricProbePromptBiometricProbePromptResolve(
      promptId: promptId,
      available: available,
      classifierCode: classifierCode,
    );

/// Cancel a pending probe without resolving — capabilities
/// cache abandoned the await (shutdown, fresh probe started).
/// Idempotent on a missing id.
void biometricProbePromptCancel({required String promptId}) => RustLib
    .instance
    .api
    .crateApiBiometricProbePromptBiometricProbePromptCancel(promptId: promptId);
