// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'ssh.dart';
part 'bus.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Direct connect entry point. Bypasses the bus because connect is
/// a request/response operation: the Dart caller awaits the result
/// to learn whether the actor reached `Connected`. Lifecycle events
/// (`ConnectionStateChanged`, `ConnectionProgress`) still fan out
/// over the bus for any subscribed view.
///
/// The driver inside `lfs_core::connection` dispatches onto the
/// `connect_*_with_secret_owned` family so the entire future chain
/// (`wrap_async → connect_async → Session::connect_*_with_secret_owned`)
/// keeps an unambiguous `Send + 'static` shape — no `&str` HRTB
/// auto-trait propagation between the layers.
Future<void> connectionConnect({
  required String id,
  required BusConnectArgs args,
}) => RustLib.instance.api.crateApiBusConnectionConnect(id: id, args: args);

/// Pull the live `SshSession` handle off a connected actor. Returns
/// `Ok(None)` when the actor is missing or hasn't reached the
/// `Connected` state yet — the caller can subscribe to
/// `ConnectionStateChanged` events to learn when to retry. The
/// returned wrapper shares the underlying `Arc<Session>` with the
/// actor so channel ops (`open_shell`, `open_sftp`, …) drive the
/// same russh session the actor parked on `Connected`. Callers
/// must NOT call `disconnect()` on the returned wrapper — that
/// would only clear the wrapper's own slot, leaving the actor's
/// session live but no longer reachable through this handle.
/// Tear-down belongs to the actor (`bus_dispatch(ConnectionDisconnect)`).
Future<SshSession?> connectionGetSession({required String id}) =>
    RustLib.instance.api.crateApiBusConnectionGetSession(id: id);

/// Dispatch a typed command. Single entry point Dart calls for
/// every operation; the Rust side routes by command variant.
Future<void> busDispatch({required BusCommand command}) =>
    RustLib.instance.api.crateApiBusBusDispatch(command: command);

/// Subscribe to events filtered by [`BusTopic`]. Yields the matching
/// events to the Dart `StreamSink` until the sink rejects an
/// `add` (Dart side cancelled the subscription).
///
/// Drop semantics: when the Dart subscription is cancelled, the
/// returned future returns from `sink.add` with `Err`, the loop
/// exits, the `broadcast::Receiver` drops, and the broker
/// auto-detaches. No explicit unsubscribe is needed.
Stream<BusEvent> busSubscribe({required BusTopic topic}) =>
    RustLib.instance.api.crateApiBusBusSubscribe(topic: topic);

@freezed
sealed class BusCommand with _$BusCommand {
  const BusCommand._();

  /// Smoke command — emits `Echoed` with the same payload.
  const factory BusCommand.noopEcho({required String payload}) =
      BusCommand_NoopEcho;

  /// Remove an actor from the registry. Idempotent on a
  /// missing id.
  const factory BusCommand.connectionDisconnect({required String id}) =
      BusCommand_ConnectionDisconnect;

  /// Tear down every active connection actor.
  const factory BusCommand.connectionDisconnectAll() =
      BusCommand_ConnectionDisconnectAll;

  /// Auto-lock — pointer activity ping.
  const factory BusCommand.autoLockOnPointerActivity() =
      BusCommand_AutoLockOnPointerActivity;

  /// Auto-lock — lifecycle change.
  const factory BusCommand.autoLockOnLifecycleChange({
    required bool background,
  }) = BusCommand_AutoLockOnLifecycleChange;

  /// Auto-lock — set the idle timeout in minutes (0 = off).
  const factory BusCommand.autoLockSetTimeout({
    required PlatformInt64 minutes,
  }) = BusCommand_AutoLockSetTimeout;

  /// Auto-lock — explicit lock request.
  const factory BusCommand.autoLockRequestLock() =
      BusCommand_AutoLockRequestLock;

  /// Auto-lock — unlock signal from the Dart-side dialog.
  const factory BusCommand.autoLockUnlock() = BusCommand_AutoLockUnlock;
}

/// Inputs to a connect command — FRB mirror of
/// `lfs_core::connection::ConnectArgs`.
class BusConnectArgs {
  final String label;
  final String? sessionId;
  final String host;
  final int port;
  final String user;
  final BusConnectAuthRef auth;
  final String? bastionId;
  final bool internal;

  const BusConnectArgs({
    required this.label,
    this.sessionId,
    required this.host,
    required this.port,
    required this.user,
    required this.auth,
    this.bastionId,
    required this.internal,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      sessionId.hashCode ^
      host.hashCode ^
      port.hashCode ^
      user.hashCode ^
      auth.hashCode ^
      bastionId.hashCode ^
      internal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusConnectArgs &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          sessionId == other.sessionId &&
          host == other.host &&
          port == other.port &&
          user == other.user &&
          auth == other.auth &&
          bastionId == other.bastionId &&
          internal == other.internal;
}

@freezed
sealed class BusConnectAuthRef with _$BusConnectAuthRef {
  const BusConnectAuthRef._();

  const factory BusConnectAuthRef.password({required String secretId}) =
      BusConnectAuthRef_Password;
  const factory BusConnectAuthRef.pubkey({
    required String keySecretId,
    String? passphraseSecretId,
  }) = BusConnectAuthRef_Pubkey;
  const factory BusConnectAuthRef.pubkeyCert({
    required String keySecretId,
    required String certSecretId,
    String? passphraseSecretId,
  }) = BusConnectAuthRef_PubkeyCert;
  const factory BusConnectAuthRef.agent() = BusConnectAuthRef_Agent;
}

/// Connection progress phase — FRB mirror of
/// `lfs_core::connection::ConnectionPhase`.
enum BusConnectionPhase {
  socketConnect,
  hostKeyVerify,
  authenticate,
  openChannel,
}

/// Connection lifecycle state — FRB mirror of
/// `lfs_core::connection::ConnectionState`.
enum BusConnectionState { disconnected, connecting, connected }

@freezed
sealed class BusEvent with _$BusEvent {
  const BusEvent._();

  /// Smoke event. Foundation plumbing test only — no domain
  /// state behind it.
  const factory BusEvent.echoed({required String payload}) = BusEvent_Echoed;

  /// Connection state machine transitioned.
  const factory BusEvent.connectionStateChanged({
    required String id,
    required BusConnectionState state,
  }) = BusEvent_ConnectionStateChanged;

  /// Per-step progress fan-out during connect / reconnect.
  const factory BusEvent.connectionProgress({
    required String id,
    required BusProgressStep step,
  }) = BusEvent_ConnectionProgress;

  /// Connect-time error recorded against an actor.
  const factory BusEvent.connectionError({
    required String id,
    required String detail,
  }) = BusEvent_ConnectionError;

  /// Actor removed from the registry (manual disconnect or
  /// parent of a disconnected bastion chain).
  const factory BusEvent.connectionRemoved({required String id}) =
      BusEvent_ConnectionRemoved;

  /// Auto-lock — fired when the idle timer expires, the app
  /// backgrounds with a non-zero timeout, or the user explicitly
  /// requests a lock.
  const factory BusEvent.autoLockLocked() = BusEvent_AutoLockLocked;

  /// Auto-lock — fired after the Dart unlock dialog supplies
  /// a fresh key + reopens the DB.
  const factory BusEvent.autoLockUnlocked() = BusEvent_AutoLockUnlocked;

  /// Auto-lock — fired when the configured idle timeout
  /// changes. Carries the new value in minutes (0 = off).
  const factory BusEvent.autoLockTimeoutChanged({
    required PlatformInt64 minutes,
  }) = BusEvent_AutoLockTimeoutChanged;

  /// Recorder — recording actor entered the registry.
  const factory BusEvent.recorderStarted({
    required String id,
    required String path,
  }) = BusEvent_RecorderStarted;

  /// Recorder — recording actor left the registry.
  const factory BusEvent.recorderStopped({required String id}) =
      BusEvent_RecorderStopped;

  /// Recorder — chunk written; carries running byte total.
  const factory BusEvent.recorderBytesWritten({
    required String id,
    required BigInt totalBytes,
  }) = BusEvent_RecorderBytesWritten;

  /// Transfer queue — task entered the queue.
  const factory BusEvent.transferTaskAdded({required String id}) =
      BusEvent_TransferTaskAdded;

  /// Transfer queue — task transitioned to a new state.
  const factory BusEvent.transferTaskState({
    required String id,
    required BusTaskState state,
  }) = BusEvent_TransferTaskState;

  /// Transfer queue — bytes-done counter advanced.
  const factory BusEvent.transferTaskProgress({
    required String id,
    required BigInt bytesDone,
    required BigInt bytesTotal,
  }) = BusEvent_TransferTaskProgress;

  /// Transfer queue — terminal failure on a task.
  const factory BusEvent.transferTaskError({
    required String id,
    required String detail,
  }) = BusEvent_TransferTaskError;

  /// Port forward — rule actor entered the registry.
  const factory BusEvent.portForwardRegistered({required String id}) =
      BusEvent_PortForwardRegistered;

  /// Port forward — rule status transitioned.
  const factory BusEvent.portForwardStatus({
    required String id,
    required BusRuleStatus status,
    String? detail,
  }) = BusEvent_PortForwardStatus;

  /// Port forward — rule actor left the registry.
  const factory BusEvent.portForwardRemoved({required String id}) =
      BusEvent_PortForwardRemoved;
}

/// Connection progress step — FRB mirror of
/// `lfs_core::connection::ProgressStep`.
class BusProgressStep {
  final BusConnectionPhase phase;
  final BusStepStatus status;
  final String? detail;

  const BusProgressStep({
    required this.phase,
    required this.status,
    this.detail,
  });

  @override
  int get hashCode => phase.hashCode ^ status.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusProgressStep &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          status == other.status &&
          detail == other.detail;
}

/// Rule status — FRB mirror of `lfs_core::portforward::RuleStatus`.
enum BusRuleStatus { idle, listening, error }

/// Step status — FRB mirror of `lfs_core::connection::StepStatus`.
enum BusStepStatus { inProgress, success, failed }

/// Task state — FRB mirror of `lfs_core::transfer::TaskState`.
enum BusTaskState { queued, running, completed, failed, cancelled }

/// Topic tag the Dart subscriber picks. The FRB-visible mirror of
/// `lfs_core::bus::EventTopic` — bumped in lockstep when new
/// domains are added.
enum BusTopic {
  diagnostics,
  connection,
  portForward,
  transfer,
  recorder,
  autoLock,
  import_,
}
