// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'ssh.dart';
part 'bus.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Direct connect entry point. Bypasses the bus because connect is
/// a request/response operation: the Dart caller awaits the result
/// to learn whether the actor reached `Connected`. Lifecycle events
/// (`ConnectionStateChanged`, `ConnectionProgress`) still fan out
/// over the bus for any subscribed view.
///
/// The driver inside `lfs_core::connection` dispatches onto the
/// `connect_*_with_secret_owned` family so the entire future chain
/// (`wrap_async → connect_async → Session::connect_*_with_secret_owned`)
/// keeps an unambiguous `Send + 'static` shape — no `&str` HRTB
/// auto-trait propagation between the layers.
Future<void> connectionConnect({
  required String id,
  required BusConnectArgs args,
}) => RustLib.instance.api.crateApiBusConnectionConnect(id: id, args: args);

/// Pull the live `SshSession` handle off a connected actor. Returns
/// `Ok(None)` when the actor is missing or hasn't reached the
/// `Connected` state yet — the caller can subscribe to
/// `ConnectionStateChanged` events to learn when to retry. The
/// returned wrapper shares the underlying `Arc<Session>` with the
/// actor so channel ops (`open_shell`, `open_sftp`, …) drive the
/// same russh session the actor parked on `Connected`. Callers
/// must NOT call `disconnect()` on the returned wrapper — that
/// would only clear the wrapper's own slot, leaving the actor's
/// session live but no longer reachable through this handle.
/// Tear-down belongs to the actor (`bus_dispatch(ConnectionDisconnect)`).
Future<SshSession?> connectionGetSession({required String id}) =>
    RustLib.instance.api.crateApiBusConnectionGetSession(id: id);

/// Dispatch a typed command. Single entry point Dart calls for
/// every operation; the Rust side routes by command variant.
Future<void> busDispatch({required BusCommand command}) =>
    RustLib.instance.api.crateApiBusBusDispatch(command: command);

/// Subscribe to events filtered by [`BusTopic`]. Yields the matching
/// events to the Dart `StreamSink` until the sink rejects an
/// `add` (Dart side cancelled the subscription).
///
/// Drop semantics: when the Dart subscription is cancelled, the
/// returned future returns from `sink.add` with `Err`, the loop
/// exits, the `broadcast::Receiver` drops, and the broker
/// auto-detaches. No explicit unsubscribe is needed.
Stream<BusEvent> busSubscribe({required BusTopic topic}) =>
    RustLib.instance.api.crateApiBusBusSubscribe(topic: topic);

@freezed
sealed class BusCommand with _$BusCommand {
  const BusCommand._();

  /// Smoke command — emits `Echoed` with the same payload.
  const factory BusCommand.noopEcho({required String payload}) =
      BusCommand_NoopEcho;

  /// Remove an actor from the registry. Idempotent on a
  /// missing id.
  const factory BusCommand.connectionDisconnect({required String id}) =
      BusCommand_ConnectionDisconnect;

  /// Tear down every active connection actor.
  const factory BusCommand.connectionDisconnectAll() =
      BusCommand_ConnectionDisconnectAll;

  /// Auto-lock — pointer activity ping.
  const factory BusCommand.autoLockOnPointerActivity() =
      BusCommand_AutoLockOnPointerActivity;

  /// Auto-lock — lifecycle change.
  const factory BusCommand.autoLockOnLifecycleChange({
    required bool background,
  }) = BusCommand_AutoLockOnLifecycleChange;

  /// Auto-lock — set the idle timeout in minutes (0 = off).
  const factory BusCommand.autoLockSetTimeout({
    required PlatformInt64 minutes,
  }) = BusCommand_AutoLockSetTimeout;

  /// Auto-lock — explicit lock request.
  const factory BusCommand.autoLockRequestLock() =
      BusCommand_AutoLockRequestLock;

  /// Auto-lock — unlock signal from the Dart-side dialog.
  const factory BusCommand.autoLockUnlock() = BusCommand_AutoLockUnlock;

  /// TOFU prompt response — Dart UI's host-key dialog resolved.
  /// Wakes the russh handler that fired the matching request.
  const factory BusCommand.knownHostPromptResponse({
    required String promptId,
    required bool accepted,
  }) = BusCommand_KnownHostPromptResponse;
}

/// Inputs to a connect command — FRB mirror of
/// `lfs_core::connection::ConnectArgs`.
class BusConnectArgs {
  final String label;
  final String? sessionId;
  final String host;
  final int port;
  final String user;
  final BusConnectAuthRef auth;
  final String? bastionId;
  final bool internal;

  const BusConnectArgs({
    required this.label,
    this.sessionId,
    required this.host,
    required this.port,
    required this.user,
    required this.auth,
    this.bastionId,
    required this.internal,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      sessionId.hashCode ^
      host.hashCode ^
      port.hashCode ^
      user.hashCode ^
      auth.hashCode ^
      bastionId.hashCode ^
      internal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusConnectArgs &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          sessionId == other.sessionId &&
          host == other.host &&
          port == other.port &&
          user == other.user &&
          auth == other.auth &&
          bastionId == other.bastionId &&
          internal == other.internal;
}

@freezed
sealed class BusConnectAuthRef with _$BusConnectAuthRef {
  const BusConnectAuthRef._();

  const factory BusConnectAuthRef.password({required String secretId}) =
      BusConnectAuthRef_Password;
  const factory BusConnectAuthRef.pubkey({
    required String keySecretId,
    String? passphraseSecretId,
  }) = BusConnectAuthRef_Pubkey;
  const factory BusConnectAuthRef.pubkeyCert({
    required String keySecretId,
    required String certSecretId,
    String? passphraseSecretId,
  }) = BusConnectAuthRef_PubkeyCert;

  /// FIDO2 hardware-bound `sk-*` SSH key. Carries the captured
  /// `id_*.pub` body + the opaque CTAP2 credential id + the
  /// `application` RP-id (typically `ssh:`). `pin_secret_id`
  /// resolves a transient PIN staged by the Dart caller before
  /// dispatch — `None` for touch-only credentials.
  const factory BusConnectAuthRef.pubkeySk({
    required String publicOpenssh,
    required Uint8List credentialId,
    required String application,
    String? pinSecretId,
  }) = BusConnectAuthRef_PubkeySk;
  const factory BusConnectAuthRef.agent() = BusConnectAuthRef_Agent;
}

/// Connection progress phase — FRB mirror of
/// `lfs_core::connection::ConnectionPhase`.
enum BusConnectionPhase {
  socketConnect,
  hostKeyVerify,
  authenticate,
  openChannel,
}

/// Connection lifecycle state — FRB mirror of
/// `lfs_core::connection::ConnectionState`.
enum BusConnectionState { disconnected, connecting, connected }

@freezed
sealed class BusEvent with _$BusEvent {
  const BusEvent._();

  /// Smoke event. Foundation plumbing test only — no domain
  /// state behind it.
  const factory BusEvent.echoed({required String payload}) = BusEvent_Echoed;

  /// Connection state machine transitioned.
  const factory BusEvent.connectionStateChanged({
    required String id,
    required BusConnectionState state,
  }) = BusEvent_ConnectionStateChanged;

  /// Per-step progress fan-out during connect / reconnect.
  const factory BusEvent.connectionProgress({
    required String id,
    required BusProgressStep step,
  }) = BusEvent_ConnectionProgress;

  /// Connect-time error recorded against an actor.
  const factory BusEvent.connectionError({
    required String id,
    required String detail,
  }) = BusEvent_ConnectionError;

  /// Actor removed from the registry (manual disconnect or
  /// parent of a disconnected bastion chain).
  const factory BusEvent.connectionRemoved({required String id}) =
      BusEvent_ConnectionRemoved;

  /// User-visible Connected count changed. Excludes internal
  /// bastion hops. Foreground-service binding consumes this to
  /// gate the Android persistent-notification service.
  const factory BusEvent.connectionActiveCountChanged({
    required PlatformInt64 count,
  }) = BusEvent_ConnectionActiveCountChanged;

  /// Auto-lock — fired when the idle timer expires, the app
  /// backgrounds with a non-zero timeout, or the user explicitly
  /// requests a lock.
  const factory BusEvent.autoLockLocked() = BusEvent_AutoLockLocked;

  /// Auto-lock — fired after the Dart unlock dialog supplies
  /// a fresh key + reopens the DB.
  const factory BusEvent.autoLockUnlocked() = BusEvent_AutoLockUnlocked;

  /// Auto-lock — fired when the configured idle timeout
  /// changes. Carries the new value in minutes (0 = off).
  const factory BusEvent.autoLockTimeoutChanged({
    required PlatformInt64 minutes,
  }) = BusEvent_AutoLockTimeoutChanged;

  /// Recorder — recording actor entered the registry.
  const factory BusEvent.recorderStarted({
    required String id,
    required String path,
  }) = BusEvent_RecorderStarted;

  /// Recorder — recording actor left the registry.
  const factory BusEvent.recorderStopped({required String id}) =
      BusEvent_RecorderStopped;

  /// Recorder — chunk written; carries running byte total.
  const factory BusEvent.recorderBytesWritten({
    required String id,
    required BigInt totalBytes,
  }) = BusEvent_RecorderBytesWritten;

  /// Recorder — running total crossed the per-file cap; the
  /// Dart shim subscribes, prepares a fresh path, and fires
  /// `recorder_queue_enqueue_rotate` to roll the recording over.
  const factory BusEvent.recorderRotateRequested({
    required String id,
    required BigInt bytesWritten,
  }) = BusEvent_RecorderRotateRequested;

  /// Recorder — `record_header` / `record_event` / `rotate_to` /
  /// `close_with_io` returned an error. Dart subscribes, flips
  /// the recording row to an error chip, and surfaces the
  /// detail in the row tooltip. Worker keeps draining its
  /// mailbox so transient failures on a single frame do not
  /// stop subsequent ones.
  const factory BusEvent.recorderWriteFailed({
    required String id,
    required String kind,
    required String detail,
  }) = BusEvent_RecorderWriteFailed;

  /// Transfer queue — task entered the queue.
  const factory BusEvent.transferTaskAdded({required String id}) =
      BusEvent_TransferTaskAdded;

  /// Transfer queue — task transitioned to a new state.
  const factory BusEvent.transferTaskState({
    required String id,
    required BusTaskState state,
  }) = BusEvent_TransferTaskState;

  /// Transfer queue — bytes-done counter advanced.
  const factory BusEvent.transferTaskProgress({
    required String id,
    required BigInt bytesDone,
    required BigInt bytesTotal,
  }) = BusEvent_TransferTaskProgress;

  /// Transfer queue — terminal failure on a task.
  const factory BusEvent.transferTaskError({
    required String id,
    required String detail,
  }) = BusEvent_TransferTaskError;

  /// Port forward — rule actor entered the registry.
  const factory BusEvent.portForwardRegistered({required String id}) =
      BusEvent_PortForwardRegistered;

  /// Port forward — rule status transitioned.
  const factory BusEvent.portForwardStatus({
    required String id,
    required BusRuleStatus status,
    String? detail,
  }) = BusEvent_PortForwardStatus;

  /// Port forward — rule actor left the registry.
  const factory BusEvent.portForwardRemoved({required String id}) =
      BusEvent_PortForwardRemoved;

  /// Auto-update — bytes-written tick during a streaming
  /// download. `total_bytes` is `None` when the server did not
  /// declare a `Content-Length`.
  const factory BusEvent.updateDownloadProgress({
    required String url,
    required BigInt writtenBytes,
    BigInt? totalBytes,
  }) = BusEvent_UpdateDownloadProgress;

  /// Auto-update — HTTP done; verifying SHA + signed manifest.
  const factory BusEvent.updateVerifyingStarted({required String url}) =
      BusEvent_UpdateVerifyingStarted;

  /// Auto-update — verification passed; asset is on disk at
  /// `path` ready for the install step.
  const factory BusEvent.updateDownloadCompleted({
    required String url,
    required String path,
  }) = BusEvent_UpdateDownloadCompleted;

  /// Known-hosts table mutated.
  const factory BusEvent.knownHostsChanged() = BusEvent_KnownHostsChanged;

  /// Sessions / folders tables mutated.
  const factory BusEvent.sessionsChanged() = BusEvent_SessionsChanged;

  /// `config.json` save landed — carries the freshly-written
  /// JSON so subscribers swap in the canonical state without
  /// a follow-up `config_store_get_json` round-trip.
  const factory BusEvent.configChanged({required String json}) =
      BusEvent_ConfigChanged;

  /// Tier state machine transitioned. `state_wire_name` is
  /// `locked` / `unlocking` / `unlocked` / `wiping`.
  const factory BusEvent.tierStateChanged({required String stateWireName}) =
      BusEvent_TierStateChanged;

  /// Connection actor needs a password / passphrase for the
  /// saved session — Dart subscriber renders the dialog,
  /// dispatches the response command back. `kind_wire_name`
  /// is `password` or `passphrase`.
  const factory BusEvent.credentialPromptRequest({
    required String promptId,
    required String sessionId,
    required String kindWireName,
  }) = BusEvent_CredentialPromptRequest;

  /// Capabilities orchestrator needs the OS-keychain
  /// reachability answer. Dart subscriber pings the platform
  /// keychain and dispatches the `KeyringProbeResult` wire
  /// name (`"available"` / `"linuxNoSecretService"` /
  /// `"probeFailed"`).
  const factory BusEvent.keychainProbePromptRequest({
    required String promptId,
  }) = BusEvent_KeychainProbePromptRequest;

  /// Capabilities orchestrator needs the hardware-vault
  /// probe code on Apple / Android / Windows. Dart
  /// subscriber calls `HardwareTierVault.probeDetail()` —
  /// which routes through FRB into
  /// `lfs_os_security::hardware_tier_vault::probe_detail`
  /// — and dispatches the platform reason code verbatim.
  const factory BusEvent.hardwareVaultProbePromptRequest({
    required String promptId,
  }) = BusEvent_HardwareVaultProbePromptRequest;

  /// T2 tier-unlock orchestrator needs the hardware vault
  /// to unseal the DB key. Dart subscriber calls
  /// `HardwareTierVault.read(pin)` which routes through FRB
  /// into the per-platform Rust vault (Apple SE / Android
  /// Keystore / Windows CNG / Linux TPM2 subprocess);
  /// resolves with the unsealed bytes / wrong-PIN signal /
  /// plugin error via the
  /// `hardware_vault_unlock_prompt_resolve*` shims. `pin`
  /// is `None` for the passwordless variant.
  const factory BusEvent.hardwareVaultUnlockPromptRequest({
    required String promptId,
    String? pin,
  }) = BusEvent_HardwareVaultUnlockPromptRequest;

  /// Hardware-vault seal — fired by the T2 first-launch
  /// orchestrator. Dart subscriber takes the staged bytes via
  /// `secrets_take(db_key_secret_id)` and (when present)
  /// `secrets_take(pin_secret_id)`, wraps them via
  /// `HardwareTierVault.store(dbKey: bytes, pin: pin)`;
  /// resolves via `hardware_vault_seal_prompt_resolve*` shims.
  /// `pin_secret_id` is `None` for the passwordless variant.
  /// The plaintext DB key + PIN never enter the broadcast channel
  /// or cross the FRB boundary inline — only opaque ids do.
  const factory BusEvent.hardwareVaultSealPromptRequest({
    required String promptId,
    required String dbKeySecretId,
    String? pinSecretId,
  }) = BusEvent_HardwareVaultSealPromptRequest;

  /// Security capabilities cache snapshot updated. `json` is
  /// the freshly-cached snapshot in the `lfs_core::security::
  /// capabilities` snake_case JSON shape; an empty string
  /// signals an explicit `clear` (Dart subscriber flips back
  /// to the neutral "probing…" state).
  const factory BusEvent.securityCapabilitiesChanged({required String json}) =
      BusEvent_SecurityCapabilitiesChanged;

  /// TOFU prompt — russh saw an unknown / changed host key.
  /// Subscribers (Dart UI) surface the host-key dialog and
  /// dispatch [`BusCommand::KnownHostPromptResponse`] back.
  const factory BusEvent.knownHostPromptRequest({
    required String promptId,
    required String host,
    required PlatformInt64 port,
    required String keyType,
    required String fingerprint,
    required BusKnownHostPromptKind kind,
  }) = BusEvent_KnownHostPromptRequest;

  /// TOFU prompt resolved — fired after the dispatcher wakes the
  /// awaiting handler. Diagnostic only (the matching handler
  /// already woke); UI may use it to dismiss any lingering toast.
  const factory BusEvent.knownHostPromptResolved({
    required String promptId,
    required bool accepted,
  }) = BusEvent_KnownHostPromptResolved;

  /// Rust-core log line. Dart `AppLogger` subscribes to
  /// [`BusTopic::CoreLog`] and folds the line into
  /// `letsflutssh.log`. `level_wire_name` is one of
  /// `"info"` / `"warn"` / `"error"` so the Dart shim maps it
  /// onto its own `LogLevel` enum without an extra translation
  /// table.
  const factory BusEvent.coreLog({
    required String levelWireName,
    required String name,
    required String message,
  }) = BusEvent_CoreLog;

  /// In-process ssh-agent endpoint parked a signer waiting on a
  /// per-key confirmation prompt. Dart subscribes to
  /// [`BusTopic::SshAgent`] and mounts an
  /// `AgentSignatureRequestDialog`; the dialog dispatches the
  /// user's verdict via
  /// `ssh_agent_respond_to_signature_request(request_id, decision)`.
  ///
  /// `request_id` is the opaque correlation id; `key_id` /
  /// `key_label` identify the stored row. `requester` carries the
  /// best-effort process name (`None` on macOS where the BSD
  /// socket layer does not expose a pid).
  const factory BusEvent.sshAgentSignaturePrompt({
    required String requestId,
    required String keyId,
    required String keyLabel,
    String? requester,
  }) = BusEvent_SshAgentSignaturePrompt;
}

/// FRB mirror of `lfs_core::bus::KnownHostPromptKind`.
enum BusKnownHostPromptKind { newHost, keyChanged }

/// Connection progress step — FRB mirror of
/// `lfs_core::connection::ProgressStep`.
class BusProgressStep {
  final BusConnectionPhase phase;
  final BusStepStatus status;
  final String? detail;

  const BusProgressStep({
    required this.phase,
    required this.status,
    this.detail,
  });

  @override
  int get hashCode => phase.hashCode ^ status.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusProgressStep &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          status == other.status &&
          detail == other.detail;
}

/// Rule status — FRB mirror of `lfs_core::portforward::RuleStatus`.
enum BusRuleStatus { idle, listening, error }

/// Step status — FRB mirror of `lfs_core::connection::StepStatus`.
enum BusStepStatus { inProgress, success, failed }

/// Task state — FRB mirror of `lfs_core::transfer::TaskState`.
enum BusTaskState { queued, running, completed, failed, cancelled }

/// Topic tag the Dart subscriber picks. The FRB-visible mirror of
/// `lfs_core::bus::EventTopic` — bumped in lockstep when new
/// domains are added.
enum BusTopic {
  diagnostics,
  connection,
  portForward,
  transfer,
  recorder,
  autoLock,
  import_,
  update,
  knownHosts,
  sessions,
  config,
  tier,
  securityPrompt,
  securityCapabilities,

  /// Rust-core log fan-out. Dart `AppLogger` subscribes here +
  /// folds every line into the same on-disk `letsflutssh.log`
  /// the Dart-side calls write through.
  coreLog,

  /// In-process ssh-agent endpoint — per-key confirmation
  /// prompts when an external SSH client requests a signature
  /// against a key whose `agent_policy = 'ask'`.
  sshAgent,
}
