// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'bus.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Dispatch a typed command. Single entry point Dart calls for
/// every operation; the Rust side routes by command variant.
Future<void> busDispatch({required BusCommand command}) =>
    RustLib.instance.api.crateApiBusBusDispatch(command: command);

/// Subscribe to events filtered by [`BusTopic`]. Yields the matching
/// events to the Dart `StreamSink` until the sink rejects an
/// `add` (Dart side cancelled the subscription).
///
/// Drop semantics: when the Dart subscription is cancelled, the
/// returned future returns from `sink.add` with `Err`, the loop
/// exits, the `broadcast::Receiver` drops, and the broker
/// auto-detaches. No explicit unsubscribe is needed.
Stream<BusEvent> busSubscribe({required BusTopic topic}) =>
    RustLib.instance.api.crateApiBusBusSubscribe(topic: topic);

@freezed
sealed class BusCommand with _$BusCommand {
  const BusCommand._();

  /// 5.0 smoke command — emits `Echoed` with the same payload.
  const factory BusCommand.noopEcho({required String payload}) =
      BusCommand_NoopEcho;
}

@freezed
sealed class BusEvent with _$BusEvent {
  const BusEvent._();

  /// 5.0 smoke event. Foundation plumbing test only — no domain
  /// state behind it.
  const factory BusEvent.echoed({required String payload}) = BusEvent_Echoed;
}

/// Topic tag the Dart subscriber picks. The FRB-visible mirror of
/// `lfs_core::bus::EventTopic` — bumped in lockstep when sub-phases
/// add new domains.
enum BusTopic {
  diagnostics,
  connection,
  portForward,
  transfer,
  recorder,
  autoLock,
  import_,
}
