// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// FRB mirror of `lfs_core::security::capabilities::SecurityCapabilities`.
/// Field shape matches the Dart `SecurityCapabilities` class
/// 1:1 — the Dart wrapper just unboxes into its own constructor.
class DbSecurityCapabilitiesSnapshot {
  final bool keychainAvailable;
  final bool hardwareVaultAvailable;
  final bool biometricAvailable;
  final bool fprintdAvailable;
  final bool isLinuxHost;

  /// Wire name (`"available"` / `"linuxNoSecretService"` /
  /// `"probeFailed"`) of the keychain probe outcome. Mirrors
  /// the Dart `KeyringProbeResult.name` getter byte-for-byte.
  final String keychainProbeWireName;

  /// Raw platform-specific hardware-vault detail code. The
  /// Dart `hardwareProbeDetailText` mapper converts this to
  /// localised reason copy.
  final String hardwareProbeCode;

  const DbSecurityCapabilitiesSnapshot({
    required this.keychainAvailable,
    required this.hardwareVaultAvailable,
    required this.biometricAvailable,
    required this.fprintdAvailable,
    required this.isLinuxHost,
    required this.keychainProbeWireName,
    required this.hardwareProbeCode,
  });

  @override
  int get hashCode =>
      keychainAvailable.hashCode ^
      hardwareVaultAvailable.hashCode ^
      biometricAvailable.hashCode ^
      fprintdAvailable.hashCode ^
      isLinuxHost.hashCode ^
      keychainProbeWireName.hashCode ^
      hardwareProbeCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSecurityCapabilitiesSnapshot &&
          runtimeType == other.runtimeType &&
          keychainAvailable == other.keychainAvailable &&
          hardwareVaultAvailable == other.hardwareVaultAvailable &&
          biometricAvailable == other.biometricAvailable &&
          fprintdAvailable == other.fprintdAvailable &&
          isLinuxHost == other.isLinuxHost &&
          keychainProbeWireName == other.keychainProbeWireName &&
          hardwareProbeCode == other.hardwareProbeCode;
}
