// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Encode the AppConfig blob persisted as `config.json`. Returns
/// the minified JSON string — caller `jsonDecode`s into a
/// `Map<String, dynamic>` for the existing `app_config.dart`
/// consumers (or just writes it straight to disk after a
/// pretty-print pass).
///
/// Caller hands the JSON-string they would have written
/// themselves; this shim re-encodes via the canonical Rust
/// pipeline so the field-name set + default-omit grammar lives
/// one place.
String configAppConfigToJson({required String inputJson}) => RustLib
    .instance
    .api
    .crateApiConfigConfigAppConfigToJson(inputJson: inputJson);

/// Sanitise a JSON-encoded AppConfig blob — clamp every field
/// to its valid range. Returns the canonical JSON string. Same
/// semantics as `AppConfig.sanitized()` Dart-side.
///
/// Used by the load path to turn a pre-Phase-F `config.json` (or
/// a hand-edited / corrupted file) into a known-valid
/// representation before the rest of the app reads it.
String configAppConfigSanitizeJson({required String inputJson}) => RustLib
    .instance
    .api
    .crateApiConfigConfigAppConfigSanitizeJson(inputJson: inputJson);

/// Strip every per-host security field from the JSON blob, then
/// return the trimmed JSON string. Mirror of Dart
/// `AppConfig.toJsonForExport`. Used by the `.lfs` archive
/// exporter so the importing host re-runs the wizard rather than
/// adopting the exporter's tier / probe-cache shape.
String configAppConfigStripForExport({required String inputJson}) => RustLib
    .instance
    .api
    .crateApiConfigConfigAppConfigStripForExport(inputJson: inputJson);

/// Return the JSON encoding of the default `AppConfig` — every
/// field at its baked-in default. Used by the first-launch
/// bootstrap to seed `config.json` before any user interaction.
String configAppConfigDefaultsJson() =>
    RustLib.instance.api.crateApiConfigConfigAppConfigDefaultsJson();

/// Locale codes the app's `app_*.arb` bundles ship for. Mirror of
/// `AppConfig.supportedLocales` Dart-side; exposed via FRB so the
/// validator + Settings dropdown read the same Rust-side const.
List<String> configSupportedLocales() =>
    RustLib.instance.api.crateApiConfigConfigSupportedLocales();

/// Validate a JSON-encoded AppConfig. Returns `Some(message)` on
/// the first failure (terminal → ssh → ui → workers → history)
/// and `None` when every field is in range. Mirror of
/// `AppConfig.validate` Dart-side; the returned message is an
/// English placeholder that the Settings UI translates via the
/// `app_*.arb` validation keys.
String? configAppConfigValidateJson({required String inputJson}) => RustLib
    .instance
    .api
    .crateApiConfigConfigAppConfigValidateJson(inputJson: inputJson);

/// Initialise the process-singleton config store actor against
/// `support_dir`. Loads `<support_dir>/config.json` if present;
/// seeds with `AppConfig::default()` otherwise. Returns the
/// canonical JSON the actor adopted so the Dart caller doesn't
/// need a follow-up `config_store_get_json` round-trip.
///
/// Decision 5 — Rust owns debounce + atomic file I/O + bus
/// event publication. Dart `ConfigNotifier` shrinks to a
/// `BusEvent::ConfigChanged` subscriber + `set_json` calls.
String configStoreInit({required String supportDir}) =>
    RustLib.instance.api.crateApiConfigConfigStoreInit(supportDir: supportDir);

/// Snapshot the actor's current config. Returns `None` before
/// `config_store_init` runs; callers treat that as "use defaults
/// until startup init lands".
String? configStoreGetJson() =>
    RustLib.instance.api.crateApiConfigConfigStoreGetJson();

/// Replace the in-memory state and arm the debounce timer. The
/// disk write is fire-and-forget (300 ms after the last
/// `set_json` call); callers that want save-settled guarantees
/// use [`config_store_flush`].
void configStoreSetJson({required String newJson}) =>
    RustLib.instance.api.crateApiConfigConfigStoreSetJson(newJson: newJson);

/// Force any pending state to disk synchronously. Returns the
/// JSON written (or the current snapshot when nothing was
/// pending). Used at app shutdown / test teardown so the last
/// `set_json` is durable.
String? configStoreFlush() =>
    RustLib.instance.api.crateApiConfigConfigStoreFlush();

/// Drive the debounce loop one tick — caller checks if the
/// pending-flush deadline has passed and flushes if so. Used by
/// the Dart-side periodic ticker (300 ms timer) so the actor
/// doesn't need its own background tokio task. Returns `true`
/// when a flush fired.
bool configStoreTickIfDue() =>
    RustLib.instance.api.crateApiConfigConfigStoreTickIfDue();
