// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Resolve a pending credential prompt with the user's
/// Submit response. `secret_bytes` is the password /
/// passphrase the user typed. `remember_for_session` mirrors
/// the dialog checkbox — true = cache in the per-session
/// SecretStore slot so reconnects skip the dialog.
///
/// Returns `true` when a receiver was actually woken; `false`
/// for an unknown / already-resolved prompt id.
bool credentialPromptResolveSubmit({
  required String promptId,
  required List<int> secretBytes,
  required bool rememberForSession,
}) =>
    RustLib.instance.api.crateApiCredentialPromptCredentialPromptResolveSubmit(
      promptId: promptId,
      secretBytes: secretBytes,
      rememberForSession: rememberForSession,
    );

/// Resolve a pending credential prompt with a Cancel — user
/// dismissed the dialog or tapped Cancel. The connection
/// actor drops the connect attempt with a localised "auth
/// cancelled" error.
bool credentialPromptResolveCancel({required String promptId}) => RustLib
    .instance
    .api
    .crateApiCredentialPromptCredentialPromptResolveCancel(promptId: promptId);

/// Cancel a pending prompt without resolving — the
/// connection actor side abandoned the await (peer drop,
/// shutdown). Idempotent on a missing id.
void credentialPromptCancel({required String promptId}) => RustLib.instance.api
    .crateApiCredentialPromptCredentialPromptCancel(promptId: promptId);
