// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Parse `uri` as a `letsflutssh://connect?host=…&user=…&port=…`
/// link. Returns `None` for any malformed / non-connect URI.
DbConnectLink? parseConnectUri({required String uri}) =>
    RustLib.instance.api.crateApiDeeplinkParseConnectUri(uri: uri);

/// FRB mirror of `lfs_core::deeplink::ConnectLink`. Same shape.
class DbConnectLink {
  final String host;
  final int port;
  final String user;

  const DbConnectLink({
    required this.host,
    required this.port,
    required this.user,
  });

  @override
  int get hashCode => host.hashCode ^ port.hashCode ^ user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbConnectLink &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          user == other.user;
}
