// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'archive.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'deeplink.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `hydrate_preview`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`

/// Parse `uri` as a `letsflutssh://connect?host=…&user=…&port=…`
/// link. Returns `None` for any malformed / non-connect URI.
DbConnectLink? parseConnectUri({required String uri}) =>
    RustLib.instance.api.crateApiDeeplinkParseConnectUri(uri: uri);

/// Dispatch a URI through `lfs_core::deeplink::DeeplinkDispatcher`.
/// Routes to the matching [`DbDeeplinkOutcome`] variant; the Dart
/// caller switches on the variant to drive the right UI action
/// (open terminal, show import dialog, …). Dedup happens inside the
/// singleton dispatcher so cold-start `getInitialLink` +
/// `uriLinkStream` do not double-fire the same payload.
///
/// `async` because future bus-event hooks may push side effects;
/// the inner work today is sync but the FRB shape stays stable.
Future<DbDeeplinkOutcome> deeplinkDispatch({required String uri}) =>
    RustLib.instance.api.crateApiDeeplinkDeeplinkDispatch(uri: uri);

/// FRB mirror of `lfs_core::deeplink::ConnectLink`. Same shape.
class DbConnectLink {
  final String host;
  final int port;
  final String user;

  const DbConnectLink({
    required this.host,
    required this.port,
    required this.user,
  });

  @override
  int get hashCode => host.hashCode ^ port.hashCode ^ user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbConnectLink &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          user == other.user;
}

@freezed
sealed class DbDeeplinkOutcome with _$DbDeeplinkOutcome {
  const DbDeeplinkOutcome._();

  /// `letsflutssh://connect?host=…&user=…[&port=…]`.
  const factory DbDeeplinkOutcome.connect({
    required String host,
    required int port,
    required String user,
  }) = DbDeeplinkOutcome_Connect;

  /// `letsflutssh://import?d=…` decoded successfully. The
  /// pending payload is staged in `AppState::imports` under
  /// `handle_id`; `preview` carries the sanitised counts +
  /// session labels for the dialog (no plaintext entries).
  const factory DbDeeplinkOutcome.qrImport({
    required String handleId,
    required DbImportPreview preview,
  }) = DbDeeplinkOutcome_QrImport;

  /// QR payload carries a wire version newer than this build
  /// understands.
  const factory DbDeeplinkOutcome.qrImportRejected({
    required PlatformInt64 found,
    required PlatformInt64 supported,
  }) = DbDeeplinkOutcome_QrImportRejected;

  /// `file://…/*.lfs` or `content://…/*.lfs`.
  const factory DbDeeplinkOutcome.openLfs({required String path}) =
      DbDeeplinkOutcome_OpenLfs;

  /// `file://…/*.{pem,key,pub}` or `content://…/*.{pem,key,pub}`.
  const factory DbDeeplinkOutcome.openKeyFile({required String path}) =
      DbDeeplinkOutcome_OpenKeyFile;

  /// Recognised URI but no actionable mapping (unknown action,
  /// unsupported extension, unknown scheme).
  const factory DbDeeplinkOutcome.unknown() = DbDeeplinkOutcome_Unknown;

  /// URI matched the dispatcher's last-seen entry inside the
  /// dedup window — Dart UI does nothing.
  const factory DbDeeplinkOutcome.duplicate() = DbDeeplinkOutcome_Duplicate;
}
