// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

/// Store `entries` in the process-singleton clipboard under
/// `tab_id` + `source_pane`. Replaces any prior slot. Empty
/// `entries` are accepted (an "explicit clear via copy" — the
/// `is_set` probe still reports false since the slot's entry
/// list is empty per [`FileBrowserClipboard::is_set`]'s contract).
Future<void> fileClipboardPut({
  required String tabId,
  required String sourcePane,
  required List<DbClipboardEntry> entries,
}) => RustLib.instance.api.crateApiFileClipboardFileClipboardPut(
  tabId: tabId,
  sourcePane: sourcePane,
  entries: entries,
);

/// Take + clear the clipboard slot when it was put by
/// `expected_tab_id` + `expected_source_pane`. Returns `None` for
/// an empty slot or a mismatched source. See
/// [`FileBrowserClipboard::take_for_paste`] for the full
/// "paste-clears" rationale.
Future<List<DbClipboardEntry>?> fileClipboardTake({
  required String expectedTabId,
  required String expectedSourcePane,
}) => RustLib.instance.api.crateApiFileClipboardFileClipboardTake(
  expectedTabId: expectedTabId,
  expectedSourcePane: expectedSourcePane,
);

/// Drop the slot regardless of source. Hosts call this from their
/// own `dispose` so a closing tab can't leave entries pointing at
/// a file system the user can no longer paste against.
Future<void> fileClipboardClear() =>
    RustLib.instance.api.crateApiFileClipboardFileClipboardClear();

/// Whether the clipboard currently holds a non-empty slot. Sync —
/// the UI's paste-enabled gate reads this on every menu render and
/// shouldn't pay an FRB async hop.
bool fileClipboardIsSet() =>
    RustLib.instance.api.crateApiFileClipboardFileClipboardIsSet();

/// Source-tab id of the currently held slot (or `None` for empty).
/// The file-browser tab uses this to decide whether to render its
/// own paste menu item — paste is intentionally scoped to within a
/// single tab.
String? fileClipboardSourceTabId() =>
    RustLib.instance.api.crateApiFileClipboardFileClipboardSourceTabId();

/// FRB mirror of [`lfs_core::clipboard::ClipboardEntry`]. Field set
/// matches verbatim — the four columns the paste path needs.
class DbClipboardEntry {
  final String name;
  final String path;
  final BigInt size;
  final bool isDir;

  const DbClipboardEntry({
    required this.name,
    required this.path,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode =>
      name.hashCode ^ path.hashCode ^ size.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbClipboardEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          size == other.size &&
          isDir == other.isDir;
}
