// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'db.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `into_map`

/// Resolve a folder id to its slash-joined path.
String folderBuildPath({
  required String folderId,
  required List<DbFolder> folders,
}) => RustLib.instance.api.crateApiFolderPathFolderBuildPath(
  folderId: folderId,
  folders: folders,
);

/// Reverse lookup — find the folder id whose path equals
/// [`path`], or `None` for empty / unknown.
String? folderFindIdByPath({
  required String path,
  required List<DbFolder> folders,
}) => RustLib.instance.api.crateApiFolderPathFolderFindIdByPath(
  path: path,
  folders: folders,
);

/// Enumerate every reachable path in the folder tree. Result is
/// sorted + deduped for stable wire shape.
List<String> folderAllPaths({required List<DbFolder> folders}) =>
    RustLib.instance.api.crateApiFolderPathFolderAllPaths(folders: folders);

/// Apply a folder rename across a flat path set: exact matches
/// move; entries under `{old_path}/` have the prefix rewritten.
List<String> folderRenamePathsCascade({
  required List<String> paths,
  required String oldPath,
  required String newPath,
}) => RustLib.instance.api.crateApiFolderPathFolderRenamePathsCascade(
  paths: paths,
  oldPath: oldPath,
  newPath: newPath,
);
