// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Human-readable file size (B / KB / MB / GB).
String formatSize({required PlatformInt64 bytes}) =>
    RustLib.instance.api.crateApiFormatFormatSize(bytes: bytes);

/// Human-readable duration (ms / s / m / h granularity).
String formatDuration({required PlatformInt64 millis}) =>
    RustLib.instance.api.crateApiFormatFormatDuration(millis: millis);
