// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'ssh.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`

/// Start a Rust-driven `-L` local forward listener against the
/// supplied connection actor. Binds `bind_host:bind_port`,
/// resolves the active russh `Session` via the connection
/// registry, and spawns the accept loop that relays each accepted
/// socket through a fresh `direct-tcpip` channel to
/// `target_host:target_port`.
///
/// Returns the actual bound port (matters when the caller passes
/// `0` to let the OS pick). Status events (`Listening` / `Error`)
/// flow onto the bus through the registered rule id; the Dart UI
/// subscribes there as usual.
///
/// `connection_id` must point at a `Connected` actor — without
/// a live session the russh handle is gone and the listener task
/// would fail every accept.
Future<int> portForwardStartLocal({
  required String ruleId,
  required String connectionId,
  required String bindHost,
  required int bindPort,
  required String targetHost,
  required int targetPort,
}) => RustLib.instance.api.crateApiForwardPortForwardStartLocal(
  ruleId: ruleId,
  connectionId: connectionId,
  bindHost: bindHost,
  bindPort: bindPort,
  targetHost: targetHost,
  targetPort: targetPort,
);

/// Stop a listener spawned by [`port_forward_start_local`].
/// Idempotent on a missing rule id — drops the stored handle
/// (which aborts the accept loop and closes the listener
/// socket). Returns `true` when a handle was actually stopped.
Future<bool> portForwardStopLocal({required String ruleId}) =>
    RustLib.instance.api.crateApiForwardPortForwardStopLocal(ruleId: ruleId);

/// Start a Rust-driven `-D` SOCKS5 dynamic-forward listener
/// against the supplied connection actor. Binds
/// `bind_host:bind_port`, resolves the active russh `Session`
/// via the connection registry, and spawns the accept loop that
/// runs the SOCKS5 CONNECT handshake (RFC 1928, NO_AUTH only)
/// per accepted socket and bridges it through a fresh
/// `direct-tcpip` channel to the target the client asked for.
///
/// Returns the actual bound port (matters when the caller
/// passes `0` to let the OS pick). Status events (`Listening` /
/// `Error`) flow onto the bus through the registered rule id;
/// the Dart UI subscribes there as usual.
Future<int> portForwardStartDynamic({
  required String ruleId,
  required String connectionId,
  required String bindHost,
  required int bindPort,
}) => RustLib.instance.api.crateApiForwardPortForwardStartDynamic(
  ruleId: ruleId,
  connectionId: connectionId,
  bindHost: bindHost,
  bindPort: bindPort,
);

/// Stop a SOCKS5 listener spawned by
/// [`port_forward_start_dynamic`]. Same shape as
/// [`port_forward_stop_local`] — both share the registry's
/// listener handle slot.
Future<bool> portForwardStopDynamic({required String ruleId}) =>
    RustLib.instance.api.crateApiForwardPortForwardStopDynamic(ruleId: ruleId);

/// Open a direct-tcpip channel. `host_to_connect` / `port_to_connect`
/// is the remote endpoint reached server-side; `originator_address`
/// / `originator_port` is the local socket peer (used only by the
/// SSH protocol's logging — pass `127.0.0.1` / 0 if absent).
Future<SshForwardChannel> sshOpenDirectTcpip({
  required SshSession session,
  required String hostToConnect,
  required int portToConnect,
  required String originatorAddress,
  required int originatorPort,
}) => RustLib.instance.api.crateApiForwardSshOpenDirectTcpip(
  session: session,
  hostToConnect: hostToConnect,
  portToConnect: portToConnect,
  originatorAddress: originatorAddress,
  originatorPort: originatorPort,
);

/// Ask the server to listen on `address:port` and forward all
/// incoming connections back over this SSH session. Returns the
/// actual bound port — when the caller passes 0, the server picks
/// one and the returned value reports it.
Future<int> sshRequestRemoteForward({
  required SshSession session,
  required String address,
  required int port,
}) => RustLib.instance.api.crateApiForwardSshRequestRemoteForward(
  session: session,
  address: address,
  port: port,
);

/// Withdraw a previously-requested remote forward. Idempotent on
/// the server side (sending CANCEL after the listener is gone is
/// a no-op).
Future<void> sshCancelRemoteForward({
  required SshSession session,
  required String address,
  required int port,
}) => RustLib.instance.api.crateApiForwardSshCancelRemoteForward(
  session: session,
  address: address,
  port: port,
);

/// Wait for the next inbound `-R` forwarded connection. `null` once
/// the session is closed or the receiver was already cancelled.
Future<SshForwardedConnection?> sshNextForwardedConnection({
  required SshSession session,
}) => RustLib.instance.api.crateApiForwardSshNextForwardedConnection(
  session: session,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshForwardChannel>>
abstract class SshForwardChannel implements RustOpaqueInterface {
  /// Half-close the write side. Server typically interprets this
  /// as "client done sending" and closes its end after draining.
  Future<void> eof();

  /// Wait for the next chunk of remote bytes. Returns `null` on
  /// the Dart side once the channel is fully closed.
  Future<Uint8List?> read();

  /// Send bytes to the remote endpoint.
  Future<void> write({required List<int> data});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshForwardedConnection>>
abstract class SshForwardedConnection implements RustOpaqueInterface {
  String get connectedAddress;

  int get connectedPort;

  String get originatorAddress;

  int get originatorPort;

  set connectedAddress(String connectedAddress);

  set connectedPort(int connectedPort);

  set originatorAddress(String originatorAddress);

  set originatorPort(int originatorPort);

  /// Half-close our write side of the channel.
  Future<void> eof();

  /// Wait for the next chunk of bytes from the originator. `null`
  /// once the channel closes.
  Future<Uint8List?> read();

  /// Send bytes to the originator (to whoever connected to the
  /// server-side listener).
  Future<void> write({required List<int> data});
}
