// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'ssh.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `into_core`, `u16_port`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `hash`

/// Validate a single port-field input from the rule editor. The
/// `Form` field validator returns `None` when the input is a port
/// inside `[1, 65535]`, else
/// [`DbPortForwardFieldValidationError::PortOutOfRange`]. Sync —
/// the parse + range check is two CPU instructions and the editor
/// calls this per keystroke.
DbPortForwardFieldValidationError? portForwardValidatePortField({
  required String raw,
}) =>
    RustLib.instance.api.crateApiForwardPortForwardValidatePortField(raw: raw);

/// Validate a single host-field input from the rule editor. Routes
/// through [`lfs_core::portforward::validate_host_field`] — Dynamic
/// forwards always pass (no remote endpoint to reach); static
/// forwards require a non-empty trimmed value.
DbPortForwardFieldValidationError? portForwardValidateHostField({
  required String raw,
  required DbPortForwardKind kind,
}) => RustLib.instance.api.crateApiForwardPortForwardValidateHostField(
  raw: raw,
  kind: kind,
);

/// Parse a stored `port_forward_rules.kind` wire-string into the
/// typed enum. The FRB sync shim around
/// [`RuleKind::from_wire_name`] — used by the DB-row mapper
/// Dart-side after a `port_forward_rules.kind` column read.
/// Unknown / empty strings fold to [`DbPortForwardKind::Local`]
/// so a future variant added to a newer build cannot brick a
/// legacy stored row.
DbPortForwardKind portForwardKindFromWire({required String value}) =>
    RustLib.instance.api.crateApiForwardPortForwardKindFromWire(value: value);

/// Wire value the typed enum lowers to. The FRB sync shim around
/// [`RuleKind::wire_name`] — needed because FRB lowers Rust's
/// `Dynamic` variant to Dart's `dynamic_` (the trailing underscore
/// dodges the `dynamic` keyword collision) so the Dart enum's
/// `.name` getter does NOT match the DB column for that variant.
/// Callers writing rows to `port_forward_rules.kind` route through
/// this shim so the on-wire byte (`"dynamic"`) stays canonical.
String portForwardKindToWire({required DbPortForwardKind value}) =>
    RustLib.instance.api.crateApiForwardPortForwardKindToWire(value: value);

/// Pre-flight check for a port-forward rule. Returns `None` when
/// the rule's network params are valid for its kind, else the
/// matching reject variant. Takes a typed [`DbPortForwardKind`]
/// so the Dart caller does not round-trip through a wire-string
/// fallback that could silently re-classify a Dynamic rule as
/// Local.
DbPortForwardRuleValidationError? portForwardValidateRule({
  required DbPortForwardKind kind,
  required String bindHost,
  required PlatformInt64 bindPort,
  required String remoteHost,
  required PlatformInt64 remotePort,
}) => RustLib.instance.api.crateApiForwardPortForwardValidateRule(
  kind: kind,
  bindHost: bindHost,
  bindPort: bindPort,
  remoteHost: remoteHost,
  remotePort: remotePort,
);

/// Serialise a rule into canonical JSON. Routes through
/// [`lfs_core::portforward::rule_to_json_string`] so the Rust
/// codec is the single source of truth for the field order, key
/// names, and the empty-description omission rule.
///
/// `created_at_iso8601` on the input is re-parsed into millis +
/// re-formatted so a stray locale string the Dart caller might
/// have built (e.g. a non-UTC `toIso8601String`) round-trips
/// through the canonical formatter — no second on-wire shape.
String portForwardRuleToJsonTyped({required DbPortForwardRuleJson rule}) =>
    RustLib.instance.api.crateApiForwardPortForwardRuleToJsonTyped(rule: rule);

/// Parse a canonical-JSON rule string into the typed mirror.
/// Routes through [`lfs_core::portforward::rule_from_json_string`]
/// so the missing-field defaults (`Local` for kind, `127.0.0.1`
/// for bind_host, `true` for enabled, "now" for `created_at`)
/// stay in sync with the Rust codec. `now_ms` is the fallback the
/// parser stamps when `created_at` is missing or unparseable; the
/// Dart caller passes `DateTime.now().millisecondsSinceEpoch` so a
/// fresh rule built from a partial map carries a sensible
/// timestamp.
DbPortForwardRuleJson portForwardRuleFromJsonTyped({
  required String json,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiForwardPortForwardRuleFromJsonTyped(
  json: json,
  nowMs: nowMs,
);

/// Start a Rust-driven `-L` local forward listener against the
/// supplied connection actor. Returns the actual bound port
/// (matters when the caller passes `0` to let the OS pick).
/// Status events flow onto the bus through the registered rule id.
///
/// All orchestration (resolve session, build factory, bind addr,
/// spawn listener, store handle) lives in
/// `lfs_core::portforward::driver::start_local`. The shim is a
/// pass-through so the adapter stays free of business logic.
Future<int> portForwardStartLocal({
  required String ruleId,
  required String connectionId,
  required String bindHost,
  required int bindPort,
  required String targetHost,
  required int targetPort,
}) => RustLib.instance.api.crateApiForwardPortForwardStartLocal(
  ruleId: ruleId,
  connectionId: connectionId,
  bindHost: bindHost,
  bindPort: bindPort,
  targetHost: targetHost,
  targetPort: targetPort,
);

/// Stop a listener spawned by [`port_forward_start_local`].
/// Idempotent on a missing rule id — drops the stored handle
/// (which aborts the accept loop and closes the listener
/// socket). Returns `true` when a handle was actually stopped.
Future<bool> portForwardStopLocal({required String ruleId}) =>
    RustLib.instance.api.crateApiForwardPortForwardStopLocal(ruleId: ruleId);

/// Start a Rust-driven `-D` SOCKS5 dynamic-forward listener
/// against the supplied connection actor. Same shape as
/// [`port_forward_start_local`] minus the target tuple.
Future<int> portForwardStartDynamic({
  required String ruleId,
  required String connectionId,
  required String bindHost,
  required int bindPort,
}) => RustLib.instance.api.crateApiForwardPortForwardStartDynamic(
  ruleId: ruleId,
  connectionId: connectionId,
  bindHost: bindHost,
  bindPort: bindPort,
);

/// Stop a SOCKS5 listener spawned by
/// [`port_forward_start_dynamic`]. Same shape as
/// [`port_forward_stop_local`] — both share the registry's
/// listener handle slot.
Future<bool> portForwardStopDynamic({required String ruleId}) =>
    RustLib.instance.api.crateApiForwardPortForwardStopDynamic(ruleId: ruleId);

/// Start a Rust-driven `-R` remote-forward against the supplied
/// connection actor. Returns the actual bound port the server
/// accepted (servers may substitute their own when the caller
/// asked for 0).
Future<int> portForwardStartRemote({
  required String ruleId,
  required String connectionId,
  required String bindHost,
  required int bindPort,
  required String targetHost,
  required int targetPort,
}) => RustLib.instance.api.crateApiForwardPortForwardStartRemote(
  ruleId: ruleId,
  connectionId: connectionId,
  bindHost: bindHost,
  bindPort: bindPort,
  targetHost: targetHost,
  targetPort: targetPort,
);

/// Stop a `-R` handle spawned by [`port_forward_start_remote`].
/// Drops the handle (which aborts the bridge task, withdraws the
/// session-level route, and asks the server to stop listening).
/// Idempotent on a missing rule id. The driver awaits the inline
/// `teardown` so the route withdraw + server-side cancel-tcpip
/// complete before this future resolves — no detached cleanup
/// task left racing the runtime shutdown.
Future<bool> portForwardStopRemote({required String ruleId}) =>
    RustLib.instance.api.crateApiForwardPortForwardStopRemote(ruleId: ruleId);

/// Open a direct-tcpip channel. `host_to_connect` / `port_to_connect`
/// is the remote endpoint reached server-side; `originator_address`
/// / `originator_port` is the local socket peer (used only by the
/// SSH protocol's logging — pass `127.0.0.1` / 0 if absent).
Future<SshForwardChannel> sshOpenDirectTcpip({
  required SshSession session,
  required String hostToConnect,
  required int portToConnect,
  required String originatorAddress,
  required int originatorPort,
}) => RustLib.instance.api.crateApiForwardSshOpenDirectTcpip(
  session: session,
  hostToConnect: hostToConnect,
  portToConnect: portToConnect,
  originatorAddress: originatorAddress,
  originatorPort: originatorPort,
);

/// Ask the server to listen on `address:port` and forward all
/// incoming connections back over this SSH session. Returns the
/// actual bound port — when the caller passes 0, the server picks
/// one and the returned value reports it.
Future<int> sshRequestRemoteForward({
  required SshSession session,
  required String address,
  required int port,
}) => RustLib.instance.api.crateApiForwardSshRequestRemoteForward(
  session: session,
  address: address,
  port: port,
);

/// Withdraw a previously-requested remote forward. Idempotent on
/// the server side (sending CANCEL after the listener is gone is
/// a no-op).
Future<void> sshCancelRemoteForward({
  required SshSession session,
  required String address,
  required int port,
}) => RustLib.instance.api.crateApiForwardSshCancelRemoteForward(
  session: session,
  address: address,
  port: port,
);

/// Wait for the next inbound `-R` forwarded connection. `null` once
/// the session is closed or the receiver was already cancelled.
Future<SshForwardedConnection?> sshNextForwardedConnection({
  required SshSession session,
}) => RustLib.instance.api.crateApiForwardSshNextForwardedConnection(
  session: session,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshForwardChannel>>
abstract class SshForwardChannel implements RustOpaqueInterface {
  /// Half-close the write side. Server typically interprets this
  /// as "client done sending" and closes its end after draining.
  Future<void> eof();

  /// Wait for the next chunk of remote bytes. Returns `null` on
  /// the Dart side once the channel is fully closed.
  Future<Uint8List?> read();

  /// Send bytes to the remote endpoint.
  Future<void> write({required List<int> data});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshForwardedConnection>>
abstract class SshForwardedConnection implements RustOpaqueInterface {
  String get connectedAddress;

  int get connectedPort;

  String get originatorAddress;

  int get originatorPort;

  set connectedAddress(String connectedAddress);

  set connectedPort(int connectedPort);

  set originatorAddress(String originatorAddress);

  set originatorPort(int originatorPort);

  /// Half-close our write side of the channel.
  Future<void> eof();

  /// Wait for the next chunk of bytes from the originator. `null`
  /// once the channel closes.
  Future<Uint8List?> read();

  /// Send bytes to the originator (to whoever connected to the
  /// server-side listener).
  Future<void> write({required List<int> data});
}

/// FRB mirror of [`lfs_core::portforward::FieldValidationError`] —
/// per-field rejection for the rule-editor `Form` validators. The
/// Dart caller renders the matching sentinel string under the
/// field (`1–65535` for port, `—` for host). Kept as a typed enum
/// so the Dart side does not substring-match a free-form string.
enum DbPortForwardFieldValidationError {
  /// Port input outside `[1, 65535]`, or non-numeric / empty.
  portOutOfRange,

  /// Host input empty on a non-`Dynamic` forward.
  hostRequired,
}

/// FRB-visible mirror of [`lfs_core::portforward::RuleKind`].
/// Carries the three port-forward kinds across the boundary as a
/// typed enum; Dart consumers pattern-match directly rather than
/// round-tripping the wire-string through a `.fromWire` helper.
///
/// FRB codegen lowers each variant to camelCase Dart matching the
/// wire grammar `RuleKind::wire_name` round-trips byte-identically
/// (`local` / `remote` / `dynamic`).
enum DbPortForwardKind { local, remote, dynamic_ }

/// FRB-visible mirror of [`lfs_core::portforward::AppRule`] — the
/// app-side rule shape (no `session_id`, ISO-8601 `created_at`
/// the way Dart's `DateTime.toIso8601String()` emits when the
/// source is UTC). Distinct from
/// [`crate::api::db::DbPortForwardRule`] which carries the DB-row
/// shape (`session_id` + `created_at_ms`).
///
/// `description` is allowed to be empty; the codec helpers below
/// drop the key on serialise when empty so the wire round-trips
/// byte-identically with the prior Dart codec.
class DbPortForwardRuleJson {
  final String id;
  final DbPortForwardKind kind;
  final String bindHost;
  final PlatformInt64 bindPort;
  final String remoteHost;
  final PlatformInt64 remotePort;
  final String description;
  final bool enabled;
  final PlatformInt64 sortOrder;

  /// ISO-8601 UTC string (`YYYY-MM-DDTHH:MM:SS.mmmZ`). Matches
  /// what `DateTime.toIso8601String()` emits for a UTC source.
  final String createdAtIso8601;

  const DbPortForwardRuleJson({
    required this.id,
    required this.kind,
    required this.bindHost,
    required this.bindPort,
    required this.remoteHost,
    required this.remotePort,
    required this.description,
    required this.enabled,
    required this.sortOrder,
    required this.createdAtIso8601,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      bindHost.hashCode ^
      bindPort.hashCode ^
      remoteHost.hashCode ^
      remotePort.hashCode ^
      description.hashCode ^
      enabled.hashCode ^
      sortOrder.hashCode ^
      createdAtIso8601.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbPortForwardRuleJson &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          bindHost == other.bindHost &&
          bindPort == other.bindPort &&
          remoteHost == other.remoteHost &&
          remotePort == other.remotePort &&
          description == other.description &&
          enabled == other.enabled &&
          sortOrder == other.sortOrder &&
          createdAtIso8601 == other.createdAtIso8601;
}

/// FRB mirror of [`lfs_core::portforward::RuleValidationError`].
/// The Dart caller maps each variant to the matching localised
/// message key; the grammar lives Rust-side so the UI pre-flight
/// + the runtime checks share one source.
enum DbPortForwardRuleValidationError {
  bindPortOutOfRange,
  targetHostRequired,
  targetPortOutOfRange,
  bindHostRequired,
}
