// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dispatch_clear`, `dispatch_read`, `dispatch_store`, `map_hw_vault_error`, `map_linux_vault_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Encode the salt + sealed-blob pair as the JSON envelope written
/// to `hardware_vault.bin` on Linux. Caller writes the returned
/// string's UTF-8 bytes atomically + hardens to 0600.
String hardwareTierVaultEncodeLinuxBlob({
  required List<int> salt,
  required List<int> sealed,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultEncodeLinuxBlob(
      salt: salt,
      sealed: sealed,
    );

/// Parse the on-disk JSON envelope. `Err` on any malformed shape
/// (bad JSON / missing fields / non-string values / invalid base64
/// / empty decoded bytes). The Dart-side `read` treats any decode
/// failure as a "vault corrupt — route back to password unlock"
/// outcome.
DbHardwareTierLinuxBlob hardwareTierVaultDecodeLinuxBlob({
  required String blob,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultDecodeLinuxBlob(blob: blob);

/// Resolve the hardware-tier vault auth value for the
/// (password, biometric) modifier combo. Returns `None` when
/// the chosen modifier has no payload — `password=true` without
/// `typed_password`, `biometric=true` without `fprintd_hash`,
/// either with empty bytes, **or** `password=false &&
/// biometric=false` (the Hardware tier is always password-gated;
/// a "no-secret" call is a misuse).
///
/// FRB layer keeps the boolean wire shape (Dart side already
/// computes `(password, biometric)` from the security profile)
/// and constructs the `AuthIntent` enum here so the core
/// resolver can no longer be foot-gunned by a forgotten flag.
Uint8List? hardwareTierVaultResolveAuthValue({
  required bool password,
  required bool biometric,
  required List<int> salt,
  String? typedPassword,
  Uint8List? fprintdHash,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultResolveAuthValue(
      password: password,
      biometric: biometric,
      salt: salt,
      typedPassword: typedPassword,
      fprintdHash: fprintdHash,
    );

Future<bool> hardwareTierVaultIsAvailable() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultIsAvailable();

Future<String> hardwareTierVaultProbeDetail() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultProbeDetail();

Future<bool> hardwareTierVaultIsStored({required String supportDir}) => RustLib
    .instance
    .api
    .crateApiHardwareTierVaultHardwareTierVaultIsStored(supportDir: supportDir);

Future<bool> hardwareTierVaultIsBiometricPasswordStored({
  required String supportDir,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultIsBiometricPasswordStored(
      supportDir: supportDir,
    );

/// Store the wrapped DB key under the platform's hardware-tier
/// vault. `salt` is required for the Linux TPM2 path (gets
/// co-located inside `hardware_vault.bin`); Apple / Android
/// ignore it and the caller persists it to a sibling
/// `hardware_vault_salt.bin` separately.
Future<void> hardwareTierVaultStore({
  required String supportDir,
  required List<int> dbKey,
  required List<int> salt,
  required List<int> pinHmac,
}) => RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultStore(
  supportDir: supportDir,
  dbKey: dbKey,
  salt: salt,
  pinHmac: pinHmac,
);

/// Variant of [`hardware_tier_vault_store`] that pulls `db_key` from
/// [`lfs_core::secrets::SecretStore`] under [`secret_id`] instead of
/// taking it across the FRB boundary. Same SecretRef shape as
/// [`super::secure_key_storage::secure_storage_write_from_secret`]
/// — bytes never touch the Dart heap on the way to the hardware
/// vault. The SecretStore entry survives the call so the caller can
/// also feed the same id into `db_rekey_from_secret` (rusqlite/
/// SQLCipher rekey) before dropping the ref.
Future<void> hardwareTierVaultStoreFromSecret({
  required String supportDir,
  required String secretId,
  required List<int> salt,
  required List<int> pinHmac,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultStoreFromSecret(
      supportDir: supportDir,
      secretId: secretId,
      salt: salt,
      pinHmac: pinHmac,
    );

/// Generate a fresh 32-byte salt via `OsRng` and write it
/// atomically to `hardware_vault_salt.bin` (Apple / Windows /
/// Android sibling-file path). Returns the bytes so the caller
/// can derive the matching auth value before kicking off the
/// platform vault store. The salt-then-vault ordering is the
/// caller's responsibility — a crash between this write and the
/// vault store leaves the next launch with a sibling salt and no
/// wrapped key, which `is_stored` surfaces as "not configured".
Future<Uint8List> hardwareTierVaultProvisionSalt({
  required String supportDir,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultProvisionSalt(
      supportDir: supportDir,
    );

/// Read the on-disk `hardware_vault_salt.bin` sibling file.
/// `None` for missing or wrong-length files (clean install /
/// truncated / tampered) — caller treats every miss as
/// "no usable salt" and routes the unlock-cancelled path.
Future<Uint8List?> hardwareTierVaultReadSalt({required String supportDir}) =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultReadSalt(
      supportDir: supportDir,
    );

/// Idempotent delete of `hardware_vault_salt.bin`. Used by the
/// tier-reset / tier-switch cascade alongside the platform
/// vault clear so the sibling artefact does not survive into
/// the next configure cycle.
Future<void> hardwareTierVaultDeleteSalt({required String supportDir}) =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultDeleteSalt(
      supportDir: supportDir,
    );

/// Read the on-disk salt for the Linux hardware-vault envelope.
/// Returns `None` for missing / malformed files. No-op `Ok(None)`
/// on non-Linux targets (Apple / Android keep the salt in a
/// sibling `hardware_vault_salt.bin` file Dart-side).
Uint8List? hardwareTierVaultReadBlobSalt({required String supportDir}) =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultReadBlobSalt(
      supportDir: supportDir,
    );

Future<Uint8List?> hardwareTierVaultRead({
  required String supportDir,
  required List<int> pinHmac,
}) => RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultRead(
  supportDir: supportDir,
  pinHmac: pinHmac,
);

/// SecretRef variant of [`hardware_tier_vault_read`]. Unwraps the
/// hardware-bound DB key and stages it in
/// [`lfs_core::secrets::SecretStore`] under `secret_id` so the
/// bytes never cross the FRB boundary. Returns `Ok(true)` on
/// successful unwrap, `Ok(false)` on missing vault file / wrong
/// PIN, `Err(_)` on backend errors.
Future<bool> hardwareTierVaultReadToSecret({
  required String supportDir,
  required List<int> pinHmac,
  required String secretId,
}) =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultReadToSecret(
      supportDir: supportDir,
      pinHmac: pinHmac,
      secretId: secretId,
    );

Future<void> hardwareTierVaultClear({required String supportDir}) => RustLib
    .instance
    .api
    .crateApiHardwareTierVaultHardwareTierVaultClear(supportDir: supportDir);

Future<void> hardwareTierVaultStoreBiometricPassword({
  required String supportDir,
  required List<int> passwordBytes,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultStoreBiometricPassword(
      supportDir: supportDir,
      passwordBytes: passwordBytes,
    );

Future<Uint8List?> hardwareTierVaultReadBiometricPassword({
  required String supportDir,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultReadBiometricPassword(
      supportDir: supportDir,
    );

Future<void> hardwareTierVaultClearBiometricPassword({
  required String supportDir,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultClearBiometricPassword(
      supportDir: supportDir,
    );

/// FRB mirror of `lfs_core::security::hardware_tier_vault::LinuxBlob`.
class DbHardwareTierLinuxBlob {
  final Uint8List salt;
  final Uint8List sealed;

  const DbHardwareTierLinuxBlob({required this.salt, required this.sealed});

  @override
  int get hashCode => salt.hashCode ^ sealed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbHardwareTierLinuxBlob &&
          runtimeType == other.runtimeType &&
          salt == other.salt &&
          sealed == other.sealed;
}
