// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Encode the salt + sealed-blob pair as the JSON envelope written
/// to `hardware_vault.bin` on Linux. Caller writes the returned
/// string's UTF-8 bytes atomically + hardens to 0600.
String hardwareTierVaultEncodeLinuxBlob({
  required List<int> salt,
  required List<int> sealed,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultEncodeLinuxBlob(
      salt: salt,
      sealed: sealed,
    );

/// Parse the on-disk JSON envelope. `Err` on any malformed shape
/// (bad JSON / missing fields / non-string values / invalid base64
/// / empty decoded bytes). The Dart-side `read` treats any decode
/// failure as a "vault corrupt — route back to password unlock"
/// outcome.
DbHardwareTierLinuxBlob hardwareTierVaultDecodeLinuxBlob({
  required String blob,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultDecodeLinuxBlob(blob: blob);

/// Resolve the hardware-tier vault auth value for the
/// (password, biometric) modifier combo. Returns `None` for an
/// inconsistent request (`password=true` without `typed_password`,
/// `biometric=true` without `fprintd_hash`); the empty `Vec` case
/// (passwordless isolation) surfaces as `Some([])`.
///
/// Same auth-value grammar the Linux TPM seal + the Apple /
/// Android / Windows method-channel plugins all derive against —
/// having the resolver Rust-side keeps every platform's vault
/// agreeing on the byte shape.
Uint8List? hardwareTierVaultResolveAuthValue({
  required bool password,
  required bool biometric,
  required List<int> salt,
  String? typedPassword,
  Uint8List? fprintdHash,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultResolveAuthValue(
      password: password,
      biometric: biometric,
      salt: salt,
      typedPassword: typedPassword,
      fprintdHash: fprintdHash,
    );

bool hardwareTierVaultIsAvailable() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultIsAvailable();

String hardwareTierVaultProbeDetail() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultProbeDetail();

bool hardwareTierVaultIsStored({required String supportDir}) => RustLib
    .instance
    .api
    .crateApiHardwareTierVaultHardwareTierVaultIsStored(supportDir: supportDir);

bool hardwareTierVaultIsBiometricPasswordStored({required String supportDir}) =>
    RustLib.instance.api
        .crateApiHardwareTierVaultHardwareTierVaultIsBiometricPasswordStored(
          supportDir: supportDir,
        );

Future<void> hardwareTierVaultStore({
  required String supportDir,
  required List<int> dbKey,
  required List<int> pinHmac,
}) => RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultStore(
  supportDir: supportDir,
  dbKey: dbKey,
  pinHmac: pinHmac,
);

Future<Uint8List?> hardwareTierVaultRead({
  required String supportDir,
  required List<int> pinHmac,
}) => RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultRead(
  supportDir: supportDir,
  pinHmac: pinHmac,
);

Future<void> hardwareTierVaultClear({required String supportDir}) => RustLib
    .instance
    .api
    .crateApiHardwareTierVaultHardwareTierVaultClear(supportDir: supportDir);

Future<void> hardwareTierVaultStoreBiometricPassword({
  required String supportDir,
  required List<int> passwordBytes,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultStoreBiometricPassword(
      supportDir: supportDir,
      passwordBytes: passwordBytes,
    );

Future<Uint8List?> hardwareTierVaultReadBiometricPassword({
  required String supportDir,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultReadBiometricPassword(
      supportDir: supportDir,
    );

Future<void> hardwareTierVaultClearBiometricPassword({
  required String supportDir,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultClearBiometricPassword(
      supportDir: supportDir,
    );

/// FRB mirror of `lfs_core::security::hardware_tier_vault::LinuxBlob`.
class DbHardwareTierLinuxBlob {
  final Uint8List salt;
  final Uint8List sealed;

  const DbHardwareTierLinuxBlob({required this.salt, required this.sealed});

  @override
  int get hashCode => salt.hashCode ^ sealed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbHardwareTierLinuxBlob &&
          runtimeType == other.runtimeType &&
          salt == other.salt &&
          sealed == other.sealed;
}
