// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_auth_for_pin`, `dispatch_clear`, `dispatch_read`, `dispatch_store`, `map_linux_vault_error`, `pinned_support_dir`, `read_existing_salt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Encode the salt + sealed-blob pair as the JSON envelope written
/// to `hardware_vault.bin` on Linux. Caller writes the returned
/// string's UTF-8 bytes atomically + hardens to 0600.
String hardwareTierVaultEncodeLinuxBlob({
  required List<int> salt,
  required List<int> sealed,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultEncodeLinuxBlob(
      salt: salt,
      sealed: sealed,
    );

/// Parse the on-disk JSON envelope. `Err` on any malformed shape
/// (bad JSON / missing fields / non-string values / invalid base64
/// / empty decoded bytes). The Dart-side `read` treats any decode
/// failure as a "vault corrupt — route back to password unlock"
/// outcome.
DbHardwareTierLinuxBlob hardwareTierVaultDecodeLinuxBlob({
  required String blob,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultDecodeLinuxBlob(blob: blob);

/// Resolve the hardware-tier vault auth value for the
/// (password, biometric) modifier combo. Returns `None` when
/// the chosen modifier has no payload — `password=true` without
/// `typed_password`, `biometric=true` without `fprintd_hash`,
/// either with empty bytes, **or** `password=false &&
/// biometric=false` (the Hardware tier is always password-gated;
/// a "no-secret" call is a misuse).
///
/// FRB layer keeps the boolean wire shape (Dart side already
/// computes `(password, biometric)` from the security profile)
/// and constructs the `AuthIntent` enum here so the core
/// resolver can no longer be foot-gunned by a forgotten flag.
Uint8List? hardwareTierVaultResolveAuthValue({
  required bool password,
  required bool biometric,
  required List<int> salt,
  String? typedPassword,
  Uint8List? fprintdHash,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultResolveAuthValue(
      password: password,
      biometric: biometric,
      salt: salt,
      typedPassword: typedPassword,
      fprintdHash: fprintdHash,
    );

Future<bool> hardwareTierVaultIsAvailable() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultIsAvailable();

Future<String> hardwareTierVaultProbeDetail() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultProbeDetail();

Future<bool> hardwareTierVaultIsStored() =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultIsStored();

Future<bool> hardwareTierVaultIsBiometricPasswordStored() => RustLib
    .instance
    .api
    .crateApiHardwareTierVaultHardwareTierVaultIsBiometricPasswordStored();

/// Store the wrapped DB key under the platform's hardware-tier
/// vault. `salt` is required for the Linux TPM2 path (gets
/// co-located inside `hardware_vault.bin`); Apple / Android
/// ignore it and the caller persists it to a sibling
/// `hardware_vault_salt.bin` separately.
Future<void> hardwareTierVaultStore({
  required List<int> dbKey,
  required List<int> salt,
  required List<int> pinHmac,
}) => RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultStore(
  dbKey: dbKey,
  salt: salt,
  pinHmac: pinHmac,
);

/// Combined provision-salt + derive-auth + store. Keeps the PIN
/// String inside the Rust process — it crosses FRB once into this
/// call, the HMAC happens here under the freshly provisioned salt,
/// and the auth value never leaves Rust. Mirrors the salt-then-vault
/// ordering documented on [`hardware_tier_vault_provision_salt`]:
/// a crash between the salt write and the platform store leaves the
/// `is_stored` probe surfacing "not configured" so the next attempt
/// re-provisions cleanly.
///
/// Empty `pin` resolves to an empty auth value — the passwordless
/// arm preserved for the bank-style modifier model. An attacker
/// still needs TPM / Secure Enclave access to unseal (cold-disk
/// theft is still mitigated); there is simply no user-typed gate
/// on top.
Future<void> hardwareTierVaultStoreWithPin({
  required List<int> dbKey,
  required String pin,
}) =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultStoreWithPin(
      dbKey: dbKey,
      pin: pin,
    );

/// Variant of [`hardware_tier_vault_store`] that pulls `db_key` from
/// [`lfs_core::secrets::SecretStore`] under [`secret_id`] instead of
/// taking it across the FRB boundary. Same SecretRef shape as
/// [`super::secure_key_storage::secure_storage_write_from_secret`]
/// — bytes never touch the Dart heap on the way to the hardware
/// vault. The SecretStore entry survives the call so the caller can
/// also feed the same id into `db_rekey_from_secret` (rusqlite/
/// SQLCipher rekey) before dropping the ref.
Future<void> hardwareTierVaultStoreFromSecret({
  required String secretId,
  required List<int> salt,
  required List<int> pinHmac,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultStoreFromSecret(
      secretId: secretId,
      salt: salt,
      pinHmac: pinHmac,
    );

/// SecretRef + combined-PIN variant of [`hardware_tier_vault_store`].
/// Pulls the DB key from [`lfs_core::secrets::SecretStore`] under
/// `secret_id` and HMACs the typed `pin` under a freshly provisioned
/// salt — both the DB-key bytes and the auth value stay Rust-side.
/// PIN crosses FRB once into this call and never returns.
Future<void> hardwareTierVaultStoreFromSecretWithPin({
  required String secretId,
  required String pin,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultStoreFromSecretWithPin(
      secretId: secretId,
      pin: pin,
    );

/// Generate a fresh 32-byte salt via `OsRng` and write it
/// atomically to `hardware_vault_salt.bin` (Apple / Windows /
/// Android sibling-file path). Returns the bytes so the caller
/// can derive the matching auth value before kicking off the
/// platform vault store. The salt-then-vault ordering is the
/// caller's responsibility — a crash between this write and the
/// vault store leaves the next launch with a sibling salt and no
/// wrapped key, which `is_stored` surfaces as "not configured".
Future<Uint8List> hardwareTierVaultProvisionSalt() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultProvisionSalt();

/// Read the on-disk `hardware_vault_salt.bin` sibling file.
/// `None` for missing or wrong-length files (clean install /
/// truncated / tampered) — caller treats every miss as
/// "no usable salt" and routes the unlock-cancelled path.
Future<Uint8List?> hardwareTierVaultReadSalt() =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultReadSalt();

/// Idempotent delete of `hardware_vault_salt.bin`. Used by the
/// tier-reset / tier-switch cascade alongside the platform
/// vault clear so the sibling artefact does not survive into
/// the next configure cycle.
Future<void> hardwareTierVaultDeleteSalt() =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultDeleteSalt();

/// Change the password (PIN) protecting the hardware-tier vault.
///
/// Verification + re-seal in one call: reads the vault under the old
/// PIN to prove ownership, clears the old artefacts, and stores the
/// DB key under a freshly provisioned salt sealed to the new PIN.
///
/// The DB key comes from the active [`SecretStore`] slot (same as
/// the tier-switch path) so it never touches the Dart heap.
///
/// `Ok(())` when the old PIN is correct and the new PIN stores
/// cleanly. `Err` on wrong PIN (reads fail → `None`) or storage
/// failure (bad vault, IO error, TPM error).
Future<void> hardwareTierVaultChangePin({
  required String oldPin,
  required String newPin,
}) => RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultChangePin(
  oldPin: oldPin,
  newPin: newPin,
);

/// Read the on-disk salt for the Linux hardware-vault envelope.
/// Returns `None` for missing / malformed files. No-op `Ok(None)`
/// on non-Linux targets (Apple / Android keep the salt in a
/// sibling `hardware_vault_salt.bin` file Dart-side).
Uint8List? hardwareTierVaultReadBlobSalt() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultReadBlobSalt();

Future<Uint8List?> hardwareTierVaultRead({required List<int> pinHmac}) =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultRead(
      pinHmac: pinHmac,
    );

/// Combined read-salt + derive-auth + unseal. Resolves the on-disk
/// salt for the current target (Linux pulls it from inside
/// `hardware_vault.bin`; Apple / Android / Windows read the sibling
/// `hardware_vault_salt.bin`), HMACs `pin` under that salt, and asks
/// the platform vault to unwrap the DB key. PIN crosses FRB once
/// into this call and never returns.
///
/// `Ok(None)` covers every miss the existing
/// [`hardware_tier_vault_read`] returns `Ok(None)` for (missing
/// salt / vault, wrong PIN). Empty `pin` derives the empty
/// auth value — a vault sealed under the passwordless arm unseals
/// the same way.
Future<Uint8List?> hardwareTierVaultReadWithPin({required String pin}) =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultReadWithPin(
      pin: pin,
    );

/// SecretRef variant of [`hardware_tier_vault_read`]. Unwraps the
/// hardware-bound DB key and stages it in
/// [`lfs_core::secrets::SecretStore`] under `secret_id` so the
/// bytes never cross the FRB boundary. Returns `Ok(true)` on
/// successful unwrap, `Ok(false)` on missing vault file / wrong
/// PIN, `Err(_)` on backend errors.
Future<bool> hardwareTierVaultReadToSecret({
  required List<int> pinHmac,
  required String secretId,
}) =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultReadToSecret(
      pinHmac: pinHmac,
      secretId: secretId,
    );

Future<void> hardwareTierVaultClear() =>
    RustLib.instance.api.crateApiHardwareTierVaultHardwareTierVaultClear();

Future<void> hardwareTierVaultStoreBiometricPassword({
  required List<int> passwordBytes,
}) => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultStoreBiometricPassword(
      passwordBytes: passwordBytes,
    );

Future<Uint8List?> hardwareTierVaultReadBiometricPassword() => RustLib
    .instance
    .api
    .crateApiHardwareTierVaultHardwareTierVaultReadBiometricPassword();

Future<void> hardwareTierVaultClearBiometricPassword() => RustLib.instance.api
    .crateApiHardwareTierVaultHardwareTierVaultClearBiometricPassword();

/// FRB mirror of `lfs_core::security::hardware_tier_vault::LinuxBlob`.
class DbHardwareTierLinuxBlob {
  final Uint8List salt;
  final Uint8List sealed;

  const DbHardwareTierLinuxBlob({required this.salt, required this.sealed});

  @override
  int get hashCode => salt.hashCode ^ sealed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbHardwareTierLinuxBlob &&
          runtimeType == other.runtimeType &&
          salt == other.salt &&
          sealed == other.sealed;
}
