// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'installer.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

/// Open `path` under the host's default handler for `platform`
/// (`linux` / `macos` / `windows`). Any other platform string
/// surfaces as [`InstallerLaunchOutcome::UnsupportedPlatform`]
/// without ever reaching a spawn. The Dart caller
/// (`UpdateService.openFile`) maps each variant onto a UI
/// surface — `Launched` returns `true`, every other variant
/// returns `false` and lets the Settings page fall back to
/// opening the GitHub release page in a browser.
///
/// See `lfs_os_security::installer_launch::open_installer_file`
/// for the per-platform binding and the Windows allowlist
/// rationale.
Future<InstallerLaunchOutcome> openInstallerFile({
  required String path,
  required String platform,
}) => RustLib.instance.api.crateApiInstallerOpenInstallerFile(
  path: path,
  platform: platform,
);

/// Replace the running AppImage (`appimage_path` = `$APPIMAGE`) with the
/// verified download at `new_path`, then spawn the new image. On
/// [`AppImageApplyOutcome::Relaunched`] the Dart caller exits the old
/// process. Linux AppImage channel only — Dart gates on the detected
/// install method before calling. See
/// `lfs_os_security::installer_launch::replace_appimage_and_relaunch`.
Future<AppImageApplyOutcome> replaceAppimageAndRelaunch({
  required String newPath,
  required String appimagePath,
}) => RustLib.instance.api.crateApiInstallerReplaceAppimageAndRelaunch(
  newPath: newPath,
  appimagePath: appimagePath,
);

@freezed
sealed class AppImageApplyOutcome with _$AppImageApplyOutcome {
  const AppImageApplyOutcome._();

  /// New image in place and the new process spawned. Dart exits the
  /// old process so only the new instance remains.
  const factory AppImageApplyOutcome.relaunched() =
      AppImageApplyOutcome_Relaunched;

  /// Empty `$APPIMAGE` path or the downloaded image was missing.
  const factory AppImageApplyOutcome.invalidInput({required String reason}) =
      AppImageApplyOutcome_InvalidInput;

  /// Copy / chmod / rename failed; the live image is untouched.
  const factory AppImageApplyOutcome.replaceFailed({
    required String stage,
    required String error,
  }) = AppImageApplyOutcome_ReplaceFailed;

  /// New image is in place but spawning it failed; the next manual
  /// launch picks up the new version.
  const factory AppImageApplyOutcome.relaunchFailed({required String error}) =
      AppImageApplyOutcome_RelaunchFailed;
}

@freezed
sealed class InstallerLaunchOutcome with _$InstallerLaunchOutcome {
  const InstallerLaunchOutcome._();

  /// Subprocess spawned and exited zero. The OS handler has
  /// accepted the path; whether the user completes the
  /// install from here is outside the app's loop.
  const factory InstallerLaunchOutcome.launched() =
      InstallerLaunchOutcome_Launched;

  /// Windows arm only — the path carried at least one
  /// `cmd.exe` metacharacter and was refused before any
  /// spawn. See `lfs_os_security::installer_launch` for the
  /// attack model the allowlist defends against.
  const factory InstallerLaunchOutcome.refusedUnsafePath() =
      InstallerLaunchOutcome_RefusedUnsafePath;

  /// The `platform` argument did not match `"linux"` /
  /// `"macos"` / `"windows"`. Used by Dart to short-circuit
  /// on iOS / Android / `"unknown"` hosts where there is no
  /// installer-launch primitive to call.
  const factory InstallerLaunchOutcome.unsupportedPlatform() =
      InstallerLaunchOutcome_UnsupportedPlatform;

  /// Spawn happened but the helper either failed to launch
  /// the program (executable missing, permission denied) or
  /// the program exited non-zero. `exit_code` is the
  /// process exit code when the program ran; `-1` when the
  /// failure was a spawn error rather than a non-zero exit.
  /// `stderr` carries whatever the helper / program wrote
  /// to stderr.
  const factory InstallerLaunchOutcome.launchFailed({
    required int exitCode,
    required String stderr,
  }) = InstallerLaunchOutcome_LaunchFailed;
}
