// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Resolve a pending L2 keychain pepper read with the bytes
/// the Dart subscriber pulled from
/// `flutter_secure_storage`. Pass an empty `Vec` to mean
/// "entry missing / read failed" — same shape the Rust caller
/// routes through the L2 reset path.
///
/// Returns `true` when a receiver was actually woken; `false`
/// for an unknown / already-resolved prompt id (caller can
/// log the orphan).
bool keychainPepperPromptResolve({
  required String promptId,
  required List<int> pepperBytes,
}) => RustLib.instance.api
    .crateApiKeychainPepperPromptKeychainPepperPromptResolve(
      promptId: promptId,
      pepperBytes: pepperBytes,
    );

/// Cancel a pending prompt without resolving — used by the
/// Dart subscriber when it can't dispatch the keychain read
/// (e.g. the user interrupted the flow with a tier reset
/// from the lock screen). Idempotent on a missing id.
void keychainPepperPromptCancel({required String promptId}) => RustLib
    .instance
    .api
    .crateApiKeychainPepperPromptKeychainPepperPromptCancel(promptId: promptId);

/// L2 keychain-password gate verify — composes disk-blob
/// read + keychain-pepper prompt round-trip + HMAC compare
/// into one async FRB call. Returns `Ok(true)` on a match,
/// `Ok(false)` for every other outcome (file missing /
/// corrupt blob / pepper missing / HMAC mismatch / cancelled
/// prompt). `Err` is reserved for unrecoverable filesystem
/// errors.
///
/// Caller is the Dart unlock dialog; the Dart subscriber for
/// `BusEvent::KeychainPepperPromptRequest` performs the
/// `flutter_secure_storage.read` call after seeing the
/// request and dispatches the response via
/// [`keychain_pepper_prompt_resolve`].
Future<bool> keychainPasswordGateVerify({
  required String supportDir,
  required String password,
}) =>
    RustLib.instance.api.crateApiKeychainPepperPromptKeychainPasswordGateVerify(
      supportDir: supportDir,
      password: password,
    );
