// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Parse a single known_hosts line into zero or more entries.
List<DbParsedHostEntry> knownHostsParseLine({required String line}) => RustLib
    .instance
    .api
    .crateApiKnownHostsParserKnownHostsParseLine(line: line);

class DbParsedHostEntry {
  final String hostPort;
  final String keyType;
  final String keyBase64;

  const DbParsedHostEntry({
    required this.hostPort,
    required this.keyType,
    required this.keyBase64,
  });

  @override
  int get hashCode => hostPort.hashCode ^ keyType.hashCode ^ keyBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbParsedHostEntry &&
          runtimeType == other.runtimeType &&
          hostPort == other.hostPort &&
          keyType == other.keyType &&
          keyBase64 == other.keyBase64;
}
