// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_db_entry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<DbLocalFileEntry>> localFsList({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsList(path: path);

/// List `path` for the file-browser view — same as
/// [`local_fs_list`] but with Windows Hidden / System files already
/// dropped so the pane matches Explorer. Identical to
/// [`local_fs_list`] on every non-Windows target. The Dart
/// `LocalFS.list` routes here so the hidden-name filter no longer
/// loops Dart-side; the upload walker keeps [`local_fs_list`] so
/// directory uploads still carry hidden files.
Future<List<DbLocalFileEntry>> localFsListVisible({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsListVisible(path: path);

/// Recursively enumerate every leaf file under `root`, skipping
/// symlinks and validating each name, in one FRB call. Replaces the
/// Dart per-level `list` recursion in the upload walker — the Dart
/// caller enqueues one transfer task per returned entry (re-joining
/// `rel_path` onto the local source + remote destination) and keeps
/// the per-file conflict-resolution UI. `max_depth` caps recursion
/// (the file browser passes 100).
Future<List<DbFlatFileEntry>> localFsFlatWalkFiles({
  required String root,
  required int maxDepth,
}) => RustLib.instance.api.crateApiLocalFsLocalFsFlatWalkFiles(
  root: root,
  maxDepth: maxDepth,
);

/// Stat `path` following symlinks. `None` means "does not
/// exist"; other I/O failures (permission denied, broken disk)
/// surface as `Err`. The transfer walker uses this to read size
/// and mtime for the change-detected replace path; the file pane
/// uses it as a one-trip "exists?" probe.
Future<DbLocalFileEntry?> localFsStat({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsStat(path: path);

/// Stat `path` without following symlinks. The returned
/// entry's `is_symlink` is `true` when the path itself is a
/// symlink, regardless of target type — matches Dart's
/// `FileSystemEntity.typeSync(path, followLinks: false)`.
Future<DbLocalFileEntry?> localFsSymlinkStat({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsSymlinkStat(path: path);

Future<List<String>> localFsListDirectories({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsListDirectories(path: path);

Future<void> localFsMkdir({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsMkdir(path: path);

Future<void> localFsRemove({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsRemove(path: path);

Future<void> localFsRemoveDir({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsRemoveDir(path: path);

Future<void> localFsRename({
  required String oldPath,
  required String newPath,
}) => RustLib.instance.api.crateApiLocalFsLocalFsRename(
  oldPath: oldPath,
  newPath: newPath,
);

Future<BigInt> localFsDirSize({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsDirSize(path: path);

/// Copy a single file. Replaces the destination if it exists.
/// Symmetric with [`local_fs_copy_recursive_no_symlinks`] so the
/// file-browser drop path stays Rust-side across both branches.
Future<void> localFsCopyFile({required String src, required String dst}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsCopyFile(src: src, dst: dst);

/// Recursively copy a directory tree. Refuses to traverse
/// symlinks: a symlink at the root returns
/// `Err("symlink_in_source")`, symlinks inside the tree are
/// silently skipped, and recursion is bounded by `max_depth`.
/// The Dart file-browser drop path passes 100.
Future<void> localFsCopyRecursiveNoSymlinks({
  required String src,
  required String dst,
  required int maxDepth,
}) => RustLib.instance.api.crateApiLocalFsLocalFsCopyRecursiveNoSymlinks(
  src: src,
  dst: dst,
  maxDepth: maxDepth,
);

/// Android shared-storage initial-dir probe. Stats
/// `/storage/emulated/0`, then stats and lists `Download` to
/// detect MANAGE_EXTERNAL_STORAGE (a permissive root listing
/// succeeds on scoped storage even when the child is locked).
/// `None` means the probe failed; the Dart caller falls back
/// to `getExternalStorageDirectory()` (Flutter plugin path,
/// no Rust analog). `home_dir` is the canonical shared root
/// (`/storage/emulated/0` on most devices).
Future<String?> localFsAndroidInitialDir({required String homeDir}) => RustLib
    .instance
    .api
    .crateApiLocalFsLocalFsAndroidInitialDir(homeDir: homeDir);

/// One leaf file from [`local_fs_flat_walk_files`]. `rel_path` is
/// `/`-joined relative to the walk root; every segment has passed
/// the safe-entry-name guard Rust-side.
class DbFlatFileEntry {
  final String relPath;
  final BigInt size;

  const DbFlatFileEntry({required this.relPath, required this.size});

  @override
  int get hashCode => relPath.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbFlatFileEntry &&
          runtimeType == other.runtimeType &&
          relPath == other.relPath &&
          size == other.size;
}

class DbLocalFileEntry {
  final String name;
  final String path;
  final BigInt size;
  final int mode;
  final PlatformInt64 modTimeUnixMs;
  final bool isDir;

  /// `true` only when the entry was produced by
  /// [`local_fs_symlink_stat`] and the path is itself a
  /// symbolic link. List / stat results report `false`.
  final bool isSymlink;

  const DbLocalFileEntry({
    required this.name,
    required this.path,
    required this.size,
    required this.mode,
    required this.modTimeUnixMs,
    required this.isDir,
    required this.isSymlink,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      size.hashCode ^
      mode.hashCode ^
      modTimeUnixMs.hashCode ^
      isDir.hashCode ^
      isSymlink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbLocalFileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          size == other.size &&
          mode == other.mode &&
          modTimeUnixMs == other.modTimeUnixMs &&
          isDir == other.isDir &&
          isSymlink == other.isSymlink;
}
