// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_db_entry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<DbLocalFileEntry>> localFsList({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsList(path: path);

/// Stat `path` following symlinks. `None` means "does not
/// exist"; other I/O failures (permission denied, broken disk)
/// surface as `Err`. The transfer walker uses this to read size
/// and mtime for the change-detected replace path; the file pane
/// uses it as a one-trip "exists?" probe.
Future<DbLocalFileEntry?> localFsStat({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsStat(path: path);

/// Stat `path` without following symlinks. The returned
/// entry's `is_symlink` is `true` when the path itself is a
/// symlink, regardless of target type — matches Dart's
/// `FileSystemEntity.typeSync(path, followLinks: false)`.
Future<DbLocalFileEntry?> localFsSymlinkStat({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsSymlinkStat(path: path);

Future<List<String>> localFsListDirectories({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsListDirectories(path: path);

Future<void> localFsMkdir({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsMkdir(path: path);

Future<void> localFsRemove({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsRemove(path: path);

Future<void> localFsRemoveDir({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsRemoveDir(path: path);

Future<void> localFsRename({
  required String oldPath,
  required String newPath,
}) => RustLib.instance.api.crateApiLocalFsLocalFsRename(
  oldPath: oldPath,
  newPath: newPath,
);

Future<BigInt> localFsDirSize({required String path}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsDirSize(path: path);

Future<List<String>> localFsWindowsHiddenNames({required String dir}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsWindowsHiddenNames(dir: dir);

/// Copy a single file. Replaces the destination if it exists.
/// Symmetric with [`local_fs_copy_recursive_no_symlinks`] so the
/// file-browser drop path stays Rust-side across both branches.
Future<void> localFsCopyFile({required String src, required String dst}) =>
    RustLib.instance.api.crateApiLocalFsLocalFsCopyFile(src: src, dst: dst);

/// Recursively copy a directory tree. Refuses to traverse
/// symlinks: a symlink at the root returns
/// `Err("symlink_in_source")`, symlinks inside the tree are
/// silently skipped, and recursion is bounded by `max_depth`.
/// The Dart file-browser drop path passes 100, matching the
/// constant it previously enforced inline.
Future<void> localFsCopyRecursiveNoSymlinks({
  required String src,
  required String dst,
  required int maxDepth,
}) => RustLib.instance.api.crateApiLocalFsLocalFsCopyRecursiveNoSymlinks(
  src: src,
  dst: dst,
  maxDepth: maxDepth,
);

class DbLocalFileEntry {
  final String name;
  final String path;
  final BigInt size;
  final int mode;
  final PlatformInt64 modTimeUnixMs;
  final bool isDir;

  /// `true` only when the entry was produced by
  /// [`local_fs_symlink_stat`] and the path is itself a
  /// symbolic link. List / stat results report `false`.
  final bool isSymlink;

  const DbLocalFileEntry({
    required this.name,
    required this.path,
    required this.size,
    required this.mode,
    required this.modTimeUnixMs,
    required this.isDir,
    required this.isSymlink,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      size.hashCode ^
      mode.hashCode ^
      modTimeUnixMs.hashCode ^
      isDir.hashCode ^
      isSymlink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbLocalFileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          size == other.size &&
          mode == other.mode &&
          modTimeUnixMs == other.modTimeUnixMs &&
          isDir == other.isDir &&
          isSymlink == other.isSymlink;
}
