// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String redactSecrets({required String input}) =>
    RustLib.instance.api.crateApiLogSanitizeRedactSecrets(input: input);

String sanitizeErrorMessage({required String input}) =>
    RustLib.instance.api.crateApiLogSanitizeSanitizeErrorMessage(input: input);
