// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Returns `true` when the self-sign cert exists in the user's
/// login keychain. Read-only — never mutates the keychain. On
/// non-macOS hosts always returns `false` so the settings UI
/// keeps showing "Enable secure tiers" rather than failing
/// loudly on the wrong OS.
Future<bool> macosResignHasIdentity() =>
    RustLib.instance.api.crateApiMacosResignMacosResignHasIdentity();

/// Make sure the self-sign cert exists in the keychain. Returns
/// `true` when a fresh cert was created in this call (the macOS
/// password prompt fired); `false` when an existing one was
/// reused silently.
Future<bool> macosResignEnsureIdentity() =>
    RustLib.instance.api.crateApiMacosResignMacosResignEnsureIdentity();

/// Re-sign the bundle at `bundle_path` leaf-first with the
/// self-sign cert. Caller must have run
/// [`macos_resign_ensure_identity`] earlier.
Future<MacosResignOutcome> macosResignBundle({required String bundlePath}) =>
    RustLib.instance.api.crateApiMacosResignMacosResignBundle(
      bundlePath: bundlePath,
    );

/// Drop the self-sign identity + cert from the user's login
/// keychain.
Future<void> macosResignUninstallIdentity() =>
    RustLib.instance.api.crateApiMacosResignMacosResignUninstallIdentity();

/// FRB-visible mirror of
/// `lfs_os_security::macos::code_signing::ResignOutcome`. One
/// variant per Dart settings-UI branch.
enum MacosResignOutcome { succeeded, cancelledOrFailed, bundleNotWritable }
