// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `support_dir`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Pin the support directory inside the
/// `lfs_core::security::master_password` singleton; subsequent
/// per-call FRB shims read from the pin instead of taking the
/// path per call. The pin lives in core so per-tier unlock
/// orchestrators (`tier_unlock_orchestrator`) can share the
/// same lookup without crossing crate boundaries through a
/// re-export hack.
///
/// Production callers resolve the path once via Dart's
/// `getApplicationSupportDirectory()` plugin call at app
/// startup and forward it here; subsequent inits are no-ops
/// (the first pin wins). Returns the canonical path the actor
/// adopted so a caller can confirm the bind without a re-read.
String masterPasswordInit({required String supportDir}) => RustLib.instance.api
    .crateApiMasterPasswordMasterPasswordInit(supportDir: supportDir);

/// True when `credentials.kdf` exists under the pinned support
/// dir — the master-password tier is enabled. `Err` only when the
/// pin has not been set (FRB-callable misorder), not when the file
/// is absent (that is the documented `Ok(false)`).
bool masterPasswordIsEnabled() =>
    RustLib.instance.api.crateApiMasterPasswordMasterPasswordIsEnabled();

/// Encode the algo-id + Argon2id params block to the 10-byte
/// big-endian shape `credentials.kdf` stores after the magic +
/// version header. Lets the Dart `KdfParams.encode` route
/// through the canonical Rust serialiser instead of carrying its
/// own `ByteData.setUint32` block.
Uint8List kdfParamsEncode({
  required int memoryKib,
  required int iterations,
  required int parallelism,
}) => RustLib.instance.api.crateApiMasterPasswordKdfParamsEncode(
  memoryKib: memoryKib,
  iterations: iterations,
  parallelism: parallelism,
);

/// Decode the 10-byte algo-id + Argon2id params block. Returns
/// `Err(message)` for unknown algo ids, truncated buffers, and
/// values outside the sanity ceilings (see `KdfParams::decode`).
/// Wire-shape parity with the Dart `KdfParams.decode` was the
/// deliberate goal — both halves now read the same canonical
/// validator.
DbKdfParams kdfParamsDecode({required List<int> bytes}) =>
    RustLib.instance.api.crateApiMasterPasswordKdfParamsDecode(bytes: bytes);

/// Enable master-password protection: fresh salt + Argon2id derive +
/// atomic write of the KDF record + verifier files. Returns the
/// derived key — the caller re-encrypts the SQLCipher store with it.
Future<Uint8List> masterPasswordEnable({
  required List<int> password,
  required DbKdfParams params,
}) => RustLib.instance.api.crateApiMasterPasswordMasterPasswordEnable(
  password: password,
  params: params,
);

/// SecretRef variant of [`master_password_enable`]. Stages the
/// derived key directly into [`lfs_core::secrets::SecretStore`]
/// under [`secret_id`] instead of returning the bytes over FRB.
/// Caller routes the same id through `db_rekey_from_secret` /
/// `db_init_from_secret` so the AES bytes never touch the Dart
/// heap.
///
/// Idempotent on `secret_id` collision: replaces any prior value at
/// the same id (the previous `Zeroizing` buffer scrubs on drop).
Future<void> masterPasswordEnableToSecret({
  required List<int> password,
  required DbKdfParams params,
  required String secretId,
}) => RustLib.instance.api.crateApiMasterPasswordMasterPasswordEnableToSecret(
  password: password,
  params: params,
  secretId: secretId,
);

/// Verify the old password, then re-key under the new one. Returns
/// the new derived key. `Err("Current password is incorrect")` on
/// wrong old password — the Dart `MasterPasswordException` wrapper
/// surfaces it to the change-password dialog.
Future<Uint8List> masterPasswordChange({
  required List<int> oldPassword,
  required List<int> newPassword,
  required DbKdfParams params,
}) => RustLib.instance.api.crateApiMasterPasswordMasterPasswordChange(
  oldPassword: oldPassword,
  newPassword: newPassword,
  params: params,
);

/// SecretRef variant of [`master_password_change`]. Stages the
/// freshly-derived key directly into
/// [`lfs_core::secrets::SecretStore`] under [`secret_id`] instead
/// of returning the bytes over FRB. Caller routes the same id
/// through `db_rekey_from_secret` so the AES bytes never touch the
/// Dart heap — finishes the master-password SecretRef family
/// alongside `master_password_enable_to_secret` and
/// `master_password_verify_and_derive_to_secret`.
///
/// Idempotent on `secret_id` collision: replaces any prior value
/// at the same id (the previous `Zeroizing` buffer scrubs on drop).
/// `Err("Current password is incorrect")` on wrong old password —
/// the SecretStore stays untouched.
Future<void> masterPasswordChangeToSecret({
  required List<int> oldPassword,
  required List<int> newPassword,
  required DbKdfParams params,
  required String secretId,
}) => RustLib.instance.api.crateApiMasterPasswordMasterPasswordChangeToSecret(
  oldPassword: oldPassword,
  newPassword: newPassword,
  params: params,
  secretId: secretId,
);

/// Drop the KDF + verifier files. Caller is responsible for
/// re-encrypting stores with a fresh random key + writing
/// `credentials.key`.
void masterPasswordDisable() =>
    RustLib.instance.api.crateApiMasterPasswordMasterPasswordDisable();

/// Drop everything: KDF + verifier + key file. Destructive — only
/// the forgotten-password reset flow uses this once the user has
/// confirmed the data loss.
void masterPasswordReset() =>
    RustLib.instance.api.crateApiMasterPasswordMasterPasswordReset();

/// Single-KDF unlock: derive the key, decrypt-and-match the verifier,
/// return `Some(key)` on success or `None` on a wrong password.
/// `Err` is reserved for "the tier is not enabled" / "files corrupt".
Future<Uint8List?> masterPasswordVerifyAndDerive({
  required List<int> password,
}) => RustLib.instance.api.crateApiMasterPasswordMasterPasswordVerifyAndDerive(
  password: password,
);

/// SecretRef variant of [`master_password_verify_and_derive`].
/// Stages the derived key directly into
/// [`lfs_core::secrets::SecretStore`] under `secret_id` (no FRB
/// byte-crossing). Returns:
/// * `Ok(true)` when the password was correct and bytes landed
///   under `secret_id`.
/// * `Ok(false)` on wrong password (no SecretStore mutation).
/// * `Err(_)` for "tier not enabled" / "files corrupt".
Future<bool> masterPasswordVerifyAndDeriveToSecret({
  required List<int> password,
  required String secretId,
}) => RustLib.instance.api
    .crateApiMasterPasswordMasterPasswordVerifyAndDeriveToSecret(
      password: password,
      secretId: secretId,
    );

/// FRB mirror of `lfs_core::security::master_password::KdfParams`.
/// The Dart side passes the production defaults from
/// `KdfParams.productionDefaults`; tests override with a cheaper
/// profile so unit-test cycles don't spend seconds each.
class DbKdfParams {
  final int memoryKib;
  final int iterations;
  final int parallelism;

  const DbKdfParams({
    required this.memoryKib,
    required this.iterations,
    required this.parallelism,
  });

  @override
  int get hashCode =>
      memoryKib.hashCode ^ iterations.hashCode ^ parallelism.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbKdfParams &&
          runtimeType == other.runtimeType &&
          memoryKib == other.memoryKib &&
          iterations == other.iterations &&
          parallelism == other.parallelism;
}
