// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Target version this build supports for `config.json`. Used by
/// the legacy-state probe in `SecurityInitController` to detect
/// configs below the current schema floor without duplicating the
/// `SchemaVersions::CONFIG` literal Dart-side.
int migrationConfigTargetVersion() =>
    RustLib.instance.api.crateApiMigrationMigrationConfigTargetVersion();

/// Target `schema_version` this build stamps into `.lfs` archive
/// manifests and accepts on import. Reads
/// `lfs_core::migration::SchemaVersions::ARCHIVE` so the constant
/// lives one place across the workspace.
int migrationArchiveTargetVersion() =>
    RustLib.instance.api.crateApiMigrationMigrationArchiveTargetVersion();

/// Read the on-disk `config.json` schema version. Returns `-1`
/// when the file is absent. Returns `Err` when the file is present
/// but corrupt (missing `config_schema_version`, malformed JSON,
/// etc.) — Dart caller surfaces the failure as a fatal startup
/// error. Used by the legacy-state probe in
/// `SecurityInitController` to detect a config below the current
/// schema floor *after* the migration runner has already walked
/// every chain it knows about.
///
/// Async + `spawn_blocking` — the read touches the filesystem and
/// must not stall the FRB worker thread. The earlier sync shape
/// happened to work because Dart only calls this once at startup,
/// but a future test that drives the path from inside an event
/// loop would block.
Future<int> migrationConfigVersionOnDisk({required String supportDir}) =>
    RustLib.instance.api.crateApiMigrationMigrationConfigVersionOnDisk(
      supportDir: supportDir,
    );

/// Run every registered artefact's migration chain against the
/// app-support directory at `support_dir`. Idempotent — running
/// twice in a row on a healthy install returns a no-op
/// [`DbMigrationReport`]. The Dart caller surfaces any non-no-op
/// failure via the corrupt-data dialog and refuses to start the
/// unlock flow.
///
/// Async + `spawn_blocking` — the runner walks every artefact's
/// on-disk chain (read + parse + maybe-rewrite per artefact);
/// keeping it sync would block the FRB worker thread for the
/// duration. Today the chain is short on healthy installs (every
/// artefact is at the current version, no work to do), but a
/// migration that touches several artefacts could run for tens
/// of milliseconds and that is unbounded enough to deserve the
/// spawn_blocking wrapper.
Future<DbMigrationReport> migrationRunOnStartup({required String supportDir}) =>
    RustLib.instance.api.crateApiMigrationMigrationRunOnStartup(
      supportDir: supportDir,
    );

/// FRB mirror of [`lfs_core::migration::Report`].
class DbMigrationReport {
  final List<DbMigrationStep> steps;
  final List<DbUnsupportedFutureVersion> futureVersions;
  final String? fatalError;

  const DbMigrationReport({
    required this.steps,
    required this.futureVersions,
    this.fatalError,
  });

  @override
  int get hashCode =>
      steps.hashCode ^ futureVersions.hashCode ^ fatalError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbMigrationReport &&
          runtimeType == other.runtimeType &&
          steps == other.steps &&
          futureVersions == other.futureVersions &&
          fatalError == other.fatalError;
}

/// FRB mirror of [`lfs_core::migration::Step`].
class DbMigrationStep {
  final String artefactId;
  final int fromVersion;
  final int toVersion;
  final bool succeeded;
  final String? error;

  const DbMigrationStep({
    required this.artefactId,
    required this.fromVersion,
    required this.toVersion,
    required this.succeeded,
    this.error,
  });

  @override
  int get hashCode =>
      artefactId.hashCode ^
      fromVersion.hashCode ^
      toVersion.hashCode ^
      succeeded.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbMigrationStep &&
          runtimeType == other.runtimeType &&
          artefactId == other.artefactId &&
          fromVersion == other.fromVersion &&
          toVersion == other.toVersion &&
          succeeded == other.succeeded &&
          error == other.error;
}

/// FRB mirror of [`lfs_core::migration::UnsupportedFutureVersion`].
class DbUnsupportedFutureVersion {
  final String artefactId;
  final int onDiskVersion;
  final int knownTargetVersion;

  const DbUnsupportedFutureVersion({
    required this.artefactId,
    required this.onDiskVersion,
    required this.knownTargetVersion,
  });

  @override
  int get hashCode =>
      artefactId.hashCode ^
      onDiskVersion.hashCode ^
      knownTargetVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbUnsupportedFutureVersion &&
          runtimeType == other.runtimeType &&
          artefactId == other.artefactId &&
          onDiskVersion == other.onDiskVersion &&
          knownTargetVersion == other.knownTargetVersion;
}
