// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'ssh_config.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Parse an OpenSSH config blob and produce the import preview.
/// `base_dir` anchors relative `Include` paths (Dart passes
/// `<home>/.ssh` by convention); `key_label_suffix` is the
/// date-stamp the importer appends to suggested key labels.
DbOpenSshImportPreview opensshConfigBuildPreview({
  required String configContent,
  required String folderLabel,
  required String keyLabelSuffix,
  required String baseDir,
  required int maxIncludeDepth,
}) => RustLib.instance.api.crateApiOpensshConfigImportOpensshConfigBuildPreview(
  configContent: configContent,
  folderLabel: folderLabel,
  keyLabelSuffix: keyLabelSuffix,
  baseDir: baseDir,
  maxIncludeDepth: maxIncludeDepth,
);

/// Expand a leading `~` in `path` against the user's home
/// directory. Surface used by the Dart `OpenSshConfigImporter.expandHome`
/// callers (settings dialogs, key-manager forms).
String opensshConfigExpandHome({required String path}) => RustLib.instance.api
    .crateApiOpensshConfigImportOpensshConfigExpandHome(path: path);

class DbOpenSshImportKey {
  final String id;
  final String label;
  final String privatePem;
  final String publicOpenssh;
  final String keyType;
  final String fingerprint;
  final PlatformInt64 createdAtUnixMs;

  const DbOpenSshImportKey({
    required this.id,
    required this.label,
    required this.privatePem,
    required this.publicOpenssh,
    required this.keyType,
    required this.fingerprint,
    required this.createdAtUnixMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      privatePem.hashCode ^
      publicOpenssh.hashCode ^
      keyType.hashCode ^
      fingerprint.hashCode ^
      createdAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbOpenSshImportKey &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          privatePem == other.privatePem &&
          publicOpenssh == other.publicOpenssh &&
          keyType == other.keyType &&
          fingerprint == other.fingerprint &&
          createdAtUnixMs == other.createdAtUnixMs;
}

class DbOpenSshImportPreview {
  final List<DbOpenSshImportSession> sessions;
  final List<DbOpenSshImportKey> keys;
  final int parsedHosts;
  final List<String> hostsWithMissingKeys;
  final List<String> hostsWithEncryptedKeys;

  const DbOpenSshImportPreview({
    required this.sessions,
    required this.keys,
    required this.parsedHosts,
    required this.hostsWithMissingKeys,
    required this.hostsWithEncryptedKeys,
  });

  @override
  int get hashCode =>
      sessions.hashCode ^
      keys.hashCode ^
      parsedHosts.hashCode ^
      hostsWithMissingKeys.hashCode ^
      hostsWithEncryptedKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbOpenSshImportPreview &&
          runtimeType == other.runtimeType &&
          sessions == other.sessions &&
          keys == other.keys &&
          parsedHosts == other.parsedHosts &&
          hostsWithMissingKeys == other.hostsWithMissingKeys &&
          hostsWithEncryptedKeys == other.hostsWithEncryptedKeys;
}

class DbOpenSshImportSession {
  final String id;
  final String label;
  final String folder;
  final String host;
  final int port;
  final String user;
  final DbOpenSshAuthType authType;
  final String keyId;

  const DbOpenSshImportSession({
    required this.id,
    required this.label,
    required this.folder,
    required this.host,
    required this.port,
    required this.user,
    required this.authType,
    required this.keyId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      folder.hashCode ^
      host.hashCode ^
      port.hashCode ^
      user.hashCode ^
      authType.hashCode ^
      keyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbOpenSshImportSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          folder == other.folder &&
          host == other.host &&
          port == other.port &&
          user == other.user &&
          authType == other.authType &&
          keyId == other.keyId;
}
