// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'os_security.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Apply whatever startup hardening the current platform supports.
/// Idempotent — re-running a process where hardening already
/// landed is a no-op. Returns the per-step outcomes for the
/// caller to log.
List<DbHardeningStep> osSecurityApplyStartupHardening() =>
    RustLib.instance.api.crateApiOsSecurityOsSecurityApplyStartupHardening();

/// Page-lock `len` bytes at `addr`. Returns `true` on success.
/// `addr` is the integer address of a Dart-side native buffer
/// (e.g. `Pointer.address`); the kernel reads the address-range
/// descriptor and never derefs into Dart heap.
bool osSecurityLockMemory({required BigInt addr, required BigInt len}) =>
    RustLib.instance.api.crateApiOsSecurityOsSecurityLockMemory(
      addr: addr,
      len: len,
    );

/// Reverse of [`os_security_lock_memory`]. Errors swallowed —
/// best-effort cleanup.
void osSecurityUnlockMemory({required BigInt addr, required BigInt len}) =>
    RustLib.instance.api.crateApiOsSecurityOsSecurityUnlockMemory(
      addr: addr,
      len: len,
    );

/// Set `NSURLIsExcludedFromBackupKey = true` on the app-support
/// directory (pinned at `config_store_init`) so iCloud Backup /
/// iTunes / Time Machine skip it. No-op on Linux / Windows / Android.
/// Returns the underlying Foundation error string when the call fails
/// on Apple.
void osSecurityExcludeSupportDirFromBackup() => RustLib.instance.api
    .crateApiOsSecurityOsSecurityExcludeSupportDirFromBackup();

/// Write `text` to the system clipboard with the per-platform
/// "do not sync / do not history" flags applied in the same write
/// session — Windows cloud-clipboard opt-out, macOS NSPasteboard
/// transient/concealed types, iOS `UIPasteboard.localOnly`,
/// Android `ClipDescription.EXTRA_IS_SENSITIVE` via JNI. Linux
/// uses arboard for the basic write (no cloud default to opt out
/// of). The Dart wrapper routes every platform through this one
/// call.
void osSecuritySetSecureClipboard({required String text}) => RustLib
    .instance
    .api
    .crateApiOsSecurityOsSecuritySetSecureClipboard(text: text);

/// Compare-and-clear orchestrator for the auto-wipe contract. Read
/// the current clipboard; if its SHA-256 hex digest equals
/// `expected_sha256_hex`, overwrite the slot with an empty string
/// through the same audit perimeter as
/// [`os_security_set_secure_clipboard`] (so the empty payload still
/// carries the per-platform "do not sync, do not history" markers);
/// otherwise no-op.
///
/// Plaintext never crosses FRB on the wipe path — the Dart caller
/// stages only the digest. The single audit perimeter for clipboard
/// reads + writes is in `lfs_os_security`; the FRB layer marshals
/// the hex string in and the bool out.
///
/// Returns `Ok(true)` when the clear ran; `Ok(false)` when the
/// clipboard drifted (user copied something else, contents were
/// non-text, or the system clipboard was unreachable — every
/// non-clear branch maps to `false`). `Err` surfaces only on a
/// Rust-side write failure during the follow-up empty-string
/// write — the read itself never errors out.
bool osSecuritySecureClipboardCompareAndClear({
  required String expectedSha256Hex,
}) => RustLib.instance.api
    .crateApiOsSecurityOsSecuritySecureClipboardCompareAndClear(
      expectedSha256Hex: expectedSha256Hex,
    );

/// Probe the platform's biometric backend. Apple uses
/// `LAContext.canEvaluatePolicy` via objc2; Windows uses
/// `UserConsentVerifier.CheckAvailabilityAsync` via the
/// `windows` crate; Android calls `BiometricManager.canAuthenticate`
/// via JNI. Linux short-circuits — the Dart wrapper routes Linux
/// through fprintd directly so the daemon-missing /
/// reader-absent / no-finger-enrolled distinction stays visible
/// to the Settings UI.
Future<DbBiometricAvailability> osSecurityBiometricAvailability() =>
    RustLib.instance.api.crateApiOsSecurityOsSecurityBiometricAvailability();

/// Show the OS biometric prompt with the localised reason text.
/// Resolves to `true` only on a successful authenticate; every
/// failure mode (cancel / no-match / hardware error / timeout /
/// platform-unsupported) maps to `false` so the Dart caller has
/// one branch to handle.
Future<bool> osSecurityBiometricAuthenticate({required String reason}) =>
    RustLib.instance.api.crateApiOsSecurityOsSecurityBiometricAuthenticate(
      reason: reason,
    );

/// Probe the *current* tracer state. Reads `/proc/self/status` →
/// `TracerPid` on Linux/Android, `sysctl KERN_PROC_PID` →
/// `P_TRACED` on macOS, `IsDebuggerPresent` on Windows; returns
/// `false` on iOS (sandbox blocks `ptrace`-style probes from
/// store-signed apps). Fail-safe: any I/O error in the probe
/// returns `false` rather than asserting "definitely clean" —
/// an unreadable `/proc` is not the same as "no debugger".
///
/// Pairs with [`os_security_apply_startup_hardening`]: the
/// startup pass BLOCKS new attaches via `PR_SET_DUMPABLE` /
/// `PT_DENY_ATTACH` / `SetErrorMode`; this probe READS the
/// post-hardening attach state so callers can react to a
/// debugger that landed despite the block (e.g. development
/// build with `setpcap` cap_sys_ptrace), or a debug-signed
/// macOS bundle where `PT_DENY_ATTACH` is no-op.
///
/// Caller policy is intentionally not auto-terminate — the
/// security stack reads the bool and decides response.
/// Canonical wiring: [`SecurityInitController`] short-circuits
/// the biometric shortcut on a positive probe so the user
/// re-authenticates with the typed secret rather than
/// releasing the OS-stored password into a debugger-attached
/// process.
bool osSecurityIsBeingDebugged() =>
    RustLib.instance.api.crateApiOsSecurityOsSecurityIsBeingDebugged();

/// Subscribe to OS session-lock events. Yields one `()` per OS
/// lock transition. Currently fires on Linux only (logind via
/// zbus); macOS + Windows keep their existing native plugins
/// because both are window/run-loop bound. The Dart caller
/// short-circuits before invoking on platforms where the Rust
/// listener is a no-op.
Stream<void> osSecuritySessionLockSubscribe() =>
    RustLib.instance.api.crateApiOsSecurityOsSecuritySessionLockSubscribe();

@freezed
sealed class DbBiometricAvailability with _$DbBiometricAvailability {
  const DbBiometricAvailability._();

  /// `Ok` mapped to this variant — biometrics ready.
  const factory DbBiometricAvailability.available() =
      DbBiometricAvailability_Available;
  const factory DbBiometricAvailability.platformUnsupported() =
      DbBiometricAvailability_PlatformUnsupported;
  const factory DbBiometricAvailability.noSensor() =
      DbBiometricAvailability_NoSensor;
  const factory DbBiometricAvailability.notEnrolled() =
      DbBiometricAvailability_NotEnrolled;
  const factory DbBiometricAvailability.systemServiceMissing() =
      DbBiometricAvailability_SystemServiceMissing;
  const factory DbBiometricAvailability.probe(String field0) =
      DbBiometricAvailability_Probe;
}

/// Per-step result reported by [`os_security_apply_startup_hardening`].
/// `code` carries the underlying syscall return code (0 = POSIX
/// success). `error` is `None` on success.
class DbHardeningStep {
  final String label;
  final PlatformInt64 code;
  final String? error;

  const DbHardeningStep({required this.label, required this.code, this.error});

  @override
  int get hashCode => label.hashCode ^ code.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbHardeningStep &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          code == other.code &&
          error == other.error;
}
