// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`

/// Expand a leading `~` against the running process's home
/// directory. See [`lfs_core::path::expand_tilde`] for the
/// resolution rules.
String pathExpandTilde({required String path}) =>
    RustLib.instance.api.crateApiPathPathExpandTilde(path: path);

/// Atomic byte write — writes [`bytes`] to `<path>.tmp`, hardens
/// the tmp file to owner-only perms, then renames to [`path`].
/// Caller is responsible for ensuring the parent directory exists.
///
/// Sync because the per-call work is one `write` syscall + one
/// `rename` syscall; the bytes themselves rarely top a few KiB
/// (KDF salt, marker payloads, sealed-blob envelopes, rate-limit
/// state). The Dart `writeBytesAtomic` shipped sync to the same
/// callers; routing through FRB sync preserves the contract.
void pathWriteBytesAtomic({required String path, required List<int> bytes}) =>
    RustLib.instance.api.crateApiPathPathWriteBytesAtomic(
      path: path,
      bytes: bytes,
    );

/// Tighten [`path`] to owner-only perms — `chmod 600` on Unix
/// (incl. Android / iOS, where it is redundant under the OS app
/// sandbox but harmless), an owner-only DACL via the Win32 security
/// APIs on Windows. Best-effort: returns the OS error as
/// `Err(String)` for the caller to log, never panics.
///
/// Async + `spawn_blocking` keeps the perm-tighten off the FRB
/// worker's event loop. The underlying ops are fast filesystem-
/// metadata syscalls (no subprocess on any platform), so a sync
/// shim would also work; the uniform async signature is kept to
/// avoid splitting per-OS API surfaces.
Future<void> pathHardenFilePerms({required String path}) =>
    RustLib.instance.api.crateApiPathPathHardenFilePerms(path: path);

/// Extract the basename portion of [`path`], normalising Windows
/// `\` separators to `/` first. Mirrors the Dart
/// `KeyFileHelper.basename` shape so file pickers + importers
/// share one rule.
String pathBasename({required String path}) =>
    RustLib.instance.api.crateApiPathPathBasename(path: path);

/// True when [`path`] contains a `..` segment after normalising
/// Windows separators. Used by the OpenSSH-config importer to
/// short-circuit traversal-style `IdentityFile` entries before
/// trying to read the file.
bool pathIsSuspicious({required String path}) =>
    RustLib.instance.api.crateApiPathPathIsSuspicious(path: path);

/// True when [`name`] is a single safe directory-entry name to join
/// onto a download destination. SFTP servers supply entry names as
/// untrusted bytes; the directory-walk download path rejects any
/// name that could escape the user-chosen folder (path separator,
/// `.`/`..` traversal, NUL, whitespace-only). Interior spaces are
/// allowed. See [`lfs_core::path::is_safe_transfer_entry_name`].
bool pathIsSafeEntryName({required String name}) =>
    RustLib.instance.api.crateApiPathPathIsSafeEntryName(name: name);

/// Parent directory of `path`, or `null` when the path has no
/// parent (POSIX / SFTP root, a Windows drive root, an empty
/// string, or a bare relative segment). The file pane's `navigateUp`
/// and the `RemoteFS.exists` dirname fallback both route here so the
/// Windows / POSIX parent grammar lives one place. See
/// [`lfs_core::path::parent`].
String? pathParent({required String path, required DbPathStyle style}) =>
    RustLib.instance.api.crateApiPathPathParent(path: path, style: style);

/// Shorten a path to its last two non-empty segments, prefixed
/// with `.../`. Used by the transfer panel + history rows to
/// keep long paths readable in narrow row widths without losing
/// the trailing context.
String pathShortenToTwoSegments({required String path}) =>
    RustLib.instance.api.crateApiPathPathShortenToTwoSegments(path: path);

/// Generate the `n`-th `"stem (N)ext"` sibling-name candidate
/// next to [`path`]. Caller checks whether the candidate exists
/// and increments `n`; the helper only constructs the name
/// (matches GNOME Files / Finder splitting — only the final
/// extension is preserved). `posix=true` selects `/` as the
/// dirname separator.
String pathSiblingCandidate({
  required String path,
  required int n,
  required bool posix,
}) => RustLib.instance.api.crateApiPathPathSiblingCandidate(
  path: path,
  n: n,
  posix: posix,
);

/// Separator family for [`path_parent`] — mirrors
/// `lfs_core::path::PathStyle`. `Auto` infers from the string (a
/// `\` or a `X:` drive prefix selects Windows rules); the file pane
/// passes `Auto` so one call handles the Windows local pane and the
/// forward-slash SFTP pane.
enum DbPathStyle { posix, windows, auto }
