// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rate_limit.dart';

/// Register or refresh the persisted rate-limiter for `id`. The
/// actor reads the on-disk frame synchronously (small file,
/// negligible per-call cost) so the returned snapshot reflects
/// the post-restart state immediately. Subsequent calls under the
/// same `id` reuse the cache until a `clear` drops it.
///
/// `file_path` is the absolute path to the `rate_limit_state.bin`
/// file (Dart resolves it via `getApplicationSupportDirectory`).
/// `hmac_key` is the 32-byte HMAC key derived from the L2 gate's
/// keychain pepper.
DbRateLimitStatus persistedRateLimitActorInitOrGet({
  required String id,
  required String filePath,
  required List<int> hmacKey,
}) => RustLib.instance.api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorInitOrGet(
      id: id,
      filePath: filePath,
      hmacKey: hmacKey,
    );

/// Snapshot the limiter under `id`. Returns the zero baseline for
/// an unknown id — the Dart wrapper falls back to "no cooldown"
/// before the first `init_or_get` settles.
DbRateLimitStatus persistedRateLimitActorStatus({required String id}) => RustLib
    .instance
    .api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorStatus(id: id);

/// Bump the failure counter + arm the next-retry deadline +
/// schedule a disk write. Returns the new status snapshot so the
/// caller can render the cooldown without a follow-up status
/// call.
DbRateLimitStatus persistedRateLimitActorRecordFailure({required String id}) =>
    RustLib.instance.api
        .crateApiPersistedRateLimitActorPersistedRateLimitActorRecordFailure(
          id: id,
        );

/// Wipe the failure counter so the next unlock starts fresh.
void persistedRateLimitActorRecordSuccess({required String id}) => RustLib
    .instance
    .api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorRecordSuccess(
      id: id,
    );

/// Drop the registry entry + best-effort delete the on-disk
/// file. Used on logout / wipe-all so a re-enable starts from
/// zero.
void persistedRateLimitActorClear({required String id}) => RustLib.instance.api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorClear(id: id);
