// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Uint8List persistedRateLimitEncode({
  required PlatformInt64 failureCount,
  PlatformInt64? nextRetryAtMillis,
  required List<int> hmacKey,
}) => RustLib.instance.api.crateApiPersistedRateLimitPersistedRateLimitEncode(
  failureCount: failureCount,
  nextRetryAtMillis: nextRetryAtMillis,
  hmacKey: hmacKey,
);

/// Parse + HMAC-verify the on-disk frame. Returns `None` for a
/// tamper / corruption signal so the Dart caller falls through to
/// "no state on disk" without surfacing the parse error.
DbPersistedRateLimitState? persistedRateLimitDecode({
  required List<int> bytes,
  required List<int> hmacKey,
}) => RustLib.instance.api.crateApiPersistedRateLimitPersistedRateLimitDecode(
  bytes: bytes,
  hmacKey: hmacKey,
);

/// FRB mirror of
/// `lfs_core::security::persisted_rate_limit::PersistedState`.
class DbPersistedRateLimitState {
  final PlatformInt64 failureCount;
  final PlatformInt64? nextRetryAtMillis;

  const DbPersistedRateLimitState({
    required this.failureCount,
    this.nextRetryAtMillis,
  });

  @override
  int get hashCode => failureCount.hashCode ^ nextRetryAtMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbPersistedRateLimitState &&
          runtimeType == other.runtimeType &&
          failureCount == other.failureCount &&
          nextRetryAtMillis == other.nextRetryAtMillis;
}
