// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rate_limit.dart';

/// Register or refresh the persisted rate-limiter for `id`. The
/// actor reads the on-disk frame synchronously (small file,
/// negligible per-call cost) so the returned snapshot reflects
/// the post-restart state immediately. Subsequent calls under the
/// same `id` reuse the cache until a `clear` drops it.
///
/// The state file is `rate_limit_state.bin` under the app-support
/// directory pinned at `config_store_init` — resolved Rust-side, so
/// Dart no longer threads a path in. `hmac_key` is the 32-byte HMAC
/// key derived from the T1+pw gate's keychain pepper. Falls back to
/// the in-memory baseline (no cooldown) when the pin is not yet set.
DbRateLimitStatus persistedRateLimitActorInitOrGet({
  required String id,
  required List<int> hmacKey,
}) => RustLib.instance.api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorInitOrGet(
      id: id,
      hmacKey: hmacKey,
    );

/// Snapshot the limiter under `id`. Returns the zero baseline for
/// an unknown id — the Dart wrapper falls back to "no cooldown"
/// before the first `init_or_get` settles.
DbRateLimitStatus persistedRateLimitActorStatus({required String id}) => RustLib
    .instance
    .api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorStatus(id: id);

/// Bump the failure counter + arm the next-retry deadline +
/// schedule a disk write. Returns the new status snapshot so the
/// caller can render the cooldown without a follow-up status
/// call.
DbRateLimitStatus persistedRateLimitActorRecordFailure({required String id}) =>
    RustLib.instance.api
        .crateApiPersistedRateLimitActorPersistedRateLimitActorRecordFailure(
          id: id,
        );

/// Wipe the failure counter so the next unlock starts fresh.
void persistedRateLimitActorRecordSuccess({required String id}) => RustLib
    .instance
    .api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorRecordSuccess(
      id: id,
    );

/// Drop the registry entry + best-effort delete the on-disk
/// file. Used on logout / wipe-all so a re-enable starts from
/// zero.
void persistedRateLimitActorClear({required String id}) => RustLib.instance.api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorClear(id: id);

/// Await the most-recent in-flight disk write for `id`. Returns
/// immediately when nothing is pending. Tests that observe on-disk
/// state can block on this deterministically — the alternative
/// (sleep-and-pray heuristic) races on slow runners.
Future<void> persistedRateLimitActorFlush({required String id}) => RustLib
    .instance
    .api
    .crateApiPersistedRateLimitActorPersistedRateLimitActorFlush(id: id);
