// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'archive.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `require_db`

/// Size of the QR payload (`d=` value) for the current selection,
/// in bytes (deflated + base64url-encoded). Reads sessions / keys /
/// tags / snippets straight from the open SQLCipher connection by
/// id so the manager-key PEM never crosses the FRB boundary into
/// Dart memory.
///
/// Wire-shape parity with [`crate::api::archive::db_export_qr_payload`]
/// (the production producer) — both routes through
/// `lfs_core::archive::qr_export_payload_size`, so the gauge value
/// the Dart UI reads is the same number the user would actually
/// get if they hit Export now.
int qrEstimateExportSize({required DbQrExportInput input}) =>
    RustLib.instance.api.crateApiQrComposeQrEstimateExportSize(input: input);
