// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Deflate + base64url encode the JSON payload, returning the
/// `?d=` query value ready to embed in a `letsflutssh://import?d=…`
/// deeplink. Caller composes the surrounding URI Dart-side.
String qrCodecCompressToPayload({required String json}) => RustLib.instance.api
    .crateApiQrCodecEncodeQrCodecCompressToPayload(json: json);

/// Convenience — returns just the encoded byte count for the
/// live size-estimation getters in the unified export controller.
/// Avoids the round-trip cost of returning the full string when
/// the caller only renders a "fits in QR" gauge against a length.
int qrCodecCompressToPayloadSize({required String json}) => RustLib.instance.api
    .crateApiQrCodecEncodeQrCodecCompressToPayloadSize(json: json);

/// Build the v4 QR per-session compact map and return it as a
/// JSON-encoded string. The Dart caller decodes it into a
/// `Map<String, dynamic>` and inserts it under the outer
/// payload's `"s"` array — same shape the production
/// `lfs_core::archive::qr_export_payload` writer emits, so both
/// halves of the in-memory and DB-backed encoders agree on the
/// field-name grammar (`l` / `h` / `u` / `p` / `g` / `a` / `ki`
/// / `mg` / `pw`).
///
/// `port == 22`, `auth_type == "password"`, empty `folder`, and
/// missing `key_short` collapse out of the map (default-omit). The
/// `pw` field is gated behind `include_passwords` because QR
/// codes are camera-readable and silently embedding plaintext
/// passwords would be a security regression.
String qrCodecEncodeSessionCompact({required QrSessionCompactInputs inputs}) =>
    RustLib.instance.api.crateApiQrCodecEncodeQrCodecEncodeSessionCompact(
      inputs: inputs,
    );

/// FRB-mirror of [`lfs_core::qr_codec_encode::SessionCompactInputs`].
/// Owned-string fields cross the FRB boundary one copy each — the
/// inner call borrows them as `&str` after assembly.
class QrSessionCompactInputs {
  final String label;
  final String host;
  final String user;
  final int port;
  final String folder;
  final String authType;
  final String? keyShort;
  final bool isManager;
  final bool includePasswords;

  /// Lossy-decoded as UTF-8 inside the shim — invalid sequences
  /// collapse to empty, same fallback shape the prior
  /// `password: String` signature produced for malformed input.
  final Uint8List password;

  const QrSessionCompactInputs({
    required this.label,
    required this.host,
    required this.user,
    required this.port,
    required this.folder,
    required this.authType,
    this.keyShort,
    required this.isManager,
    required this.includePasswords,
    required this.password,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      host.hashCode ^
      user.hashCode ^
      port.hashCode ^
      folder.hashCode ^
      authType.hashCode ^
      keyShort.hashCode ^
      isManager.hashCode ^
      includePasswords.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrSessionCompactInputs &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          host == other.host &&
          user == other.user &&
          port == other.port &&
          folder == other.folder &&
          authType == other.authType &&
          keyShort == other.keyShort &&
          isManager == other.isManager &&
          includePasswords == other.includePasswords &&
          password == other.password;
}
