// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'webdav.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Parse `endpoint` + `region` and return the S3 session's host
/// + port projection. Empty `endpoint` falls back to
/// `s3.<region>.amazonaws.com` (canonical AWS endpoint;
/// `us-east-1` default when `region` empty). Explicit `:port`
/// wins; `http://` no-port defaults to 80; everything else to
/// 443. Used by the session-edit dialog to populate the legacy
/// `sessions.host` / `.port` columns.
DbServerAddressFields s3ServerAddressFromEndpoint({
  required String endpoint,
  required String region,
}) => RustLib.instance.api.crateApiS3S3ServerAddressFromEndpoint(
  endpoint: endpoint,
  region: region,
);

Future<S3Connection> s3Connect({required S3ConnectRequest req}) =>
    RustLib.instance.api.crateApiS3S3Connect(req: req);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<S3Connection>>
abstract class S3Connection implements RustOpaqueInterface {
  /// Recursive prefix size. Walks `ListObjectsV2` continuation
  /// tokens server-side; one FRB call regardless of prefix depth.
  Future<BigInt> dirSize({required String path});

  /// Generate a time-limited presigned `GET` URL for `key` under
  /// `bucket`. `expires_seconds` clamps to AWS's 7-day maximum.
  Future<String> generatePresignedUrl({
    required String bucket,
    required String key,
    required int expiresSeconds,
  });

  /// Fetch the full body. Buffered into a `Vec<u8>` — large-file
  /// streaming through a FRB `StreamSink` is a follow-up.
  Future<Uint8List> getFull({required String path});

  /// List one directory level. Common prefixes surface as
  /// directories (matching SFTP's `is_dir` flag) so the Dart
  /// browser renders them identically to a real directory.
  Future<List<S3DirEntry>> list({required String path});

  /// Synthesise a directory marker — `PUT` a 0-byte object whose
  /// key ends with `/`. S3 has no native directories; the file
  /// browser's mkdir contract maps to this convention.
  Future<void> mkdir({required String path});

  /// Upload `body` to `path`. Routes through the multipart
  /// orchestrator when the body is above the 8 MiB threshold;
  /// otherwise single-shot `PUT`.
  Future<void> putFull({required String path, required List<int> body});

  /// DELETE one object.
  Future<void> remove({required String path});

  /// Server-side copy + delete. Not atomic — a reader between the
  /// two calls observes both the source and target object.
  Future<void> rename({required String from, required String to});

  /// HEAD the object. Errors when the key does not exist.
  Future<S3FileMetadata> stat({required String path});
}

/// Open an S3 session.
///
/// `secret_key_secret_id` is the SecretStore id under which the
/// secret access key has been staged (canonical form
/// `session.s3.<session_id>`). The connect path resolves the id,
/// builds the `S3Config`, constructs the `S3Client`, and runs a
/// `ListObjectsV2` against `default_bucket` (or the empty bucket
/// when none is configured) as a connect probe — so a bad
/// credential / wrong region / missing bucket surfaces at connect
/// time rather than at the first list.
/// Configuration tuple for [`s3_connect`]. Bundled into a struct
/// because the field count would otherwise cross clippy's
/// `too_many_arguments` ceiling — every field is a connect-time
/// required input (none has a meaningful default the call site
/// could omit), so factoring them out of the positional argument
/// list is a readability win as well.
class S3ConnectRequest {
  final String connectionId;
  final String accessKeyId;
  final String secretKeySecretId;
  final String region;
  final String endpoint;
  final bool pathStyle;
  final String defaultBucket;
  final String defaultPrefix;

  /// PEM blob (one or more `-----BEGIN CERTIFICATE-----` blocks)
  /// added as an additional root for the reqwest client. `None`
  /// falls back to the system trust store.
  final String? trustedCertPem;

  /// Last-resort skip-all-cert-verification toggle. The dialog
  /// renders an explicit MITM warning before letting the user
  /// flip it on.
  final bool insecureSkipVerify;

  const S3ConnectRequest({
    required this.connectionId,
    required this.accessKeyId,
    required this.secretKeySecretId,
    required this.region,
    required this.endpoint,
    required this.pathStyle,
    required this.defaultBucket,
    required this.defaultPrefix,
    this.trustedCertPem,
    required this.insecureSkipVerify,
  });

  @override
  int get hashCode =>
      connectionId.hashCode ^
      accessKeyId.hashCode ^
      secretKeySecretId.hashCode ^
      region.hashCode ^
      endpoint.hashCode ^
      pathStyle.hashCode ^
      defaultBucket.hashCode ^
      defaultPrefix.hashCode ^
      trustedCertPem.hashCode ^
      insecureSkipVerify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is S3ConnectRequest &&
          runtimeType == other.runtimeType &&
          connectionId == other.connectionId &&
          accessKeyId == other.accessKeyId &&
          secretKeySecretId == other.secretKeySecretId &&
          region == other.region &&
          endpoint == other.endpoint &&
          pathStyle == other.pathStyle &&
          defaultBucket == other.defaultBucket &&
          defaultPrefix == other.defaultPrefix &&
          trustedCertPem == other.trustedCertPem &&
          insecureSkipVerify == other.insecureSkipVerify;
}

/// One directory entry surfaced by [`S3Connection::list`]. Field
/// set mirrors the SFTP / WebDAV shape so the Dart `RemoteFileSystem`
/// facade hands every transport the same `FileEntry` row.
class S3DirEntry {
  final String name;
  final String path;
  final bool isDir;
  final BigInt size;

  /// Unix epoch milliseconds. `null` on the Dart side when the
  /// server omitted the modification timestamp.
  final PlatformInt64? modifiedUnixMs;

  const S3DirEntry({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
    this.modifiedUnixMs,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      modifiedUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is S3DirEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size &&
          modifiedUnixMs == other.modifiedUnixMs;
}

/// File metadata surfaced by [`S3Connection::stat`].
class S3FileMetadata {
  final bool isDir;
  final BigInt size;
  final PlatformInt64? modifiedUnixMs;

  const S3FileMetadata({
    required this.isDir,
    required this.size,
    this.modifiedUnixMs,
  });

  @override
  int get hashCode => isDir.hashCode ^ size.hashCode ^ modifiedUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is S3FileMetadata &&
          runtimeType == other.runtimeType &&
          isDir == other.isDir &&
          size == other.size &&
          modifiedUnixMs == other.modifiedUnixMs;
}
