// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Encode a [`SecurityCapabilities`] snapshot into the JSON wire
/// format the wizard persists inside `config.json` under
/// `security_probe_cache`. Returns the minified JSON string —
/// caller stores it as a Dart `Map<String, dynamic>` after a
/// `jsonDecode` round-trip.
///
/// Inputs come unpacked because FRB cannot derive a struct mirror
/// for `SecurityCapabilities` without re-encoding the
/// `KeyringProbeResult` enum + every field. A flat parameter list
/// keeps the Dart side from having to mirror the enum twice (once
/// in the Rust DTO, once in its own `KeyringProbeResult`).
String securityCapabilitiesToJson({
  required bool keychainAvailable,
  required bool hardwareVaultAvailable,
  required bool biometricAvailable,
  required bool fprintdAvailable,
  required bool isLinuxHost,
  required String keychainProbeWireName,
  required String hardwareProbeCode,
}) =>
    RustLib.instance.api.crateApiSecurityCapabilitiesSecurityCapabilitiesToJson(
      keychainAvailable: keychainAvailable,
      hardwareVaultAvailable: hardwareVaultAvailable,
      biometricAvailable: biometricAvailable,
      fprintdAvailable: fprintdAvailable,
      isLinuxHost: isLinuxHost,
      keychainProbeWireName: keychainProbeWireName,
      hardwareProbeCode: hardwareProbeCode,
    );

/// Parse a `security_probe_cache` JSON snapshot. Returns `None` for
/// any malformed shape (non-object root, unknown enum case,
/// missing required strings) so the Dart caller falls through to
/// "no cache" and reprobes.
DbSecurityCapabilities? securityCapabilitiesFromJson({required String json}) =>
    RustLib.instance.api
        .crateApiSecurityCapabilitiesSecurityCapabilitiesFromJson(json: json);

/// FRB-side mirror of the parsed snapshot. Returned as a flat DTO
/// so the Dart caller can rebuild `SecurityCapabilities` without
/// re-importing the enum from a generated file.
class DbSecurityCapabilities {
  final bool keychainAvailable;
  final bool hardwareVaultAvailable;
  final bool biometricAvailable;
  final bool fprintdAvailable;
  final bool isLinuxHost;

  /// Stable Dart `name` for `KeyringProbeResult` — `available`,
  /// `linuxNoSecretService`, or `probeFailed`.
  final String keychainProbeWireName;
  final String hardwareProbeCode;

  const DbSecurityCapabilities({
    required this.keychainAvailable,
    required this.hardwareVaultAvailable,
    required this.biometricAvailable,
    required this.fprintdAvailable,
    required this.isLinuxHost,
    required this.keychainProbeWireName,
    required this.hardwareProbeCode,
  });

  @override
  int get hashCode =>
      keychainAvailable.hashCode ^
      hardwareVaultAvailable.hashCode ^
      biometricAvailable.hashCode ^
      fprintdAvailable.hashCode ^
      isLinuxHost.hashCode ^
      keychainProbeWireName.hashCode ^
      hardwareProbeCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSecurityCapabilities &&
          runtimeType == other.runtimeType &&
          keychainAvailable == other.keychainAvailable &&
          hardwareVaultAvailable == other.hardwareVaultAvailable &&
          biometricAvailable == other.biometricAvailable &&
          fprintdAvailable == other.fprintdAvailable &&
          isLinuxHost == other.isLinuxHost &&
          keychainProbeWireName == other.keychainProbeWireName &&
          hardwareProbeCode == other.hardwareProbeCode;
}
