// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `plaintext_export_tmp_path`, `recordings_root_for_migrate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `hash`

/// Parse a stored tier wire-string into the typed enum. Returns
/// `None` for an unknown / empty string so the caller can decide
/// whether to fall through to plaintext (config-load path) or
/// surface the misuse (typed FRB caller). Mirrors the
/// [`SecurityTier::from_wire_name`] semantics — only the four tier
/// wire names are recognised; a password-gated Keychain rides the
/// `modifiers.password` flag, so there is no `keychain_with_password`
/// wire string to parse.
DbSecurityTier? securityTierFromWire({required String value}) => RustLib
    .instance
    .api
    .crateApiSecurityConfigSecurityTierFromWire(value: value);

/// Wire value the typed enum lowers to. The FRB sync shim around
/// [`SecurityTier::wire_name`] — Dart-side consumers route through
/// this helper instead of `.name` so any future variant added to a
/// build whose Dart name diverges from the wire grammar (a keyword
/// collision forces FRB to append `_`) keeps the on-wire byte
/// canonical.
String securityTierToWire({required DbSecurityTier value}) =>
    RustLib.instance.api.crateApiSecurityConfigSecurityTierToWire(value: value);

/// Encode the `SecurityConfig` blob persisted under
/// `config.json::security`. Returns the minified JSON string —
/// caller `jsonDecode`s into a `Map<String, dynamic>` for the
/// existing `app_config.dart` consumers. Takes the typed
/// [`DbSecurityTier`] so the wire-name validation lives Rust-side
/// and the Dart caller can't pass a typo.
String securityConfigToJson({
  required DbSecurityTier tier,
  required bool password,
  required bool biometric,
}) => RustLib.instance.api.crateApiSecurityConfigSecurityConfigToJson(
  tier: tier,
  password: password,
  biometric: biometric,
);

/// Encode the modifiers blob alone — used by callers that want to
/// re-serialise `SecurityTierModifiers` without going through the
/// outer `SecurityConfig` wrapper.
String securityTierModifiersToJson({
  required bool password,
  required bool biometric,
}) => RustLib.instance.api.crateApiSecurityConfigSecurityTierModifiersToJson(
  password: password,
  biometric: biometric,
);

/// Compose the JSON payload every tier-apply method writes into the
/// crash-recovery marker file before driving
/// `SecurityTierSwitcher::switch_tier_from_secret`. Bundles the
/// snake-case tier wire-name + modifier object so a crash-recovery
/// path at next launch reconstructs the target config and picks the
/// matching unlock prompt.
///
/// Wire shape: `{"tier": <wire>, "mods": {"password": …, "biometric": …}}`.
/// Single source of truth for the marker grammar — the Dart caller
/// hands the typed tier + modifier flags in, the Rust side emits the
/// canonical string, no Dart-side `jsonEncode` / `jsonDecode` round-
/// trip on the apply path.
String securityTierMarkerPayload({
  required DbSecurityTier tier,
  required bool password,
  required bool biometric,
}) => RustLib.instance.api.crateApiSecurityConfigSecurityTierMarkerPayload(
  tier: tier,
  password: password,
  biometric: biometric,
);

/// Parse the `security` JSON object. Mirrors `SecurityConfig.fromJson`
/// Dart-side: an unknown / missing tier string falls through to
/// `plaintext` so the caller routes into the wizard rather than
/// silently picking an unintended tier; missing modifiers fall back
/// to defaults.
DbSecurityConfig? securityConfigFromJson({required String json}) => RustLib
    .instance
    .api
    .crateApiSecurityConfigSecurityConfigFromJson(json: json);

DbSecurityTierModifiers? securityTierModifiersFromJson({
  required String json,
}) => RustLib.instance.api.crateApiSecurityConfigSecurityTierModifiersFromJson(
  json: json,
);

/// Full T1/T2/T3 → T0 transition for the database and recordings.
///
/// Drives every encrypted artefact back to a plaintext shape:
///
/// 1. **Recordings.** `convert_all_lfsr_to_cast` decrypts each
///    `.lfsr` body (under the current active DB key) and writes a
///    plaintext `.cast` next to it.
/// 2. **SQLite DB.** `Db::export_plaintext_copy` writes a plaintext
///    sqlite copy via `sqlcipher_export` next to the running
///    encrypted file, then closes the handle, deletes the encrypted
///    DB + sidecars, renames the plaintext copy over the original,
///    and re-opens the DB unkeyed.
/// 3. **Active DB-key slot.** Dropped from
///    [`lfs_core::secrets::SecretStore`] — the plaintext DB needs
///    no key.
///
/// Unlike [`master_password::master_password_disable`], this
/// function does NOT wipe credential files (`credentials.kdf`,
/// `credentials.verifier`). The Dart `runVaultClearPlan` handles
/// that separately so the master-password credential wipe only
/// runs when the tier actually used the master password.
///
/// [secret_id] is the SecretStore id holding the current DB key.
/// When `None` the function looks up
/// `ACTIVE_DBKEY_SECRET_ID` automatically. A `None` key with no
/// active handle is a safe no-op (the DB may already be plaintext).
///
/// Sync FRB call — the entire transition runs on a single blocking
/// thread, serialising concurrent FRB calls behind it.
void securitySwitchToPlaintext({String? secretId}) => RustLib.instance.api
    .crateApiSecurityConfigSecuritySwitchToPlaintext(secretId: secretId);

/// Flat DTO for a parsed `SecurityConfig` — typed tier + per-modifier
/// scalars, returned across the FRB boundary so the Dart caller can
/// rebuild its own `SecurityConfig` instance without re-importing
/// the enum from a generated file. The tier rides as a typed
/// [`DbSecurityTier`] (no wire-string round-trip on the Dart side).
class DbSecurityConfig {
  final DbSecurityTier tier;
  final bool password;
  final bool biometric;

  const DbSecurityConfig({
    required this.tier,
    required this.password,
    required this.biometric,
  });

  @override
  int get hashCode => tier.hashCode ^ password.hashCode ^ biometric.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSecurityConfig &&
          runtimeType == other.runtimeType &&
          tier == other.tier &&
          password == other.password &&
          biometric == other.biometric;
}

/// FRB-visible mirror of [`lfs_core::security::SecurityTier`].
/// Carries the four bank-style tier values across the boundary as a
/// typed enum; Dart consumers pattern-match directly rather than
/// round-tripping the wire-string through a `.fromWireName` helper.
///
/// FRB codegen lowers each variant to camelCase Dart matching the
/// wire grammar `SecurityTier::wire_name` round-trips byte-identically
/// (`plaintext` / `keychain` / `hardware` / `paranoid`). None of the
/// variants collide with a Dart reserved word so the `.name` getter
/// matches the wire byte for every value — the dedicated
/// [`security_tier_to_wire`] helper still exists so callers route
/// through the canonical grammar instead of relying on the camelCase
/// coincidence.
enum DbSecurityTier { plaintext, keychain, hardware, paranoid }

/// FRB-side mirror of just the modifiers block.
class DbSecurityTierModifiers {
  final bool password;
  final bool biometric;

  const DbSecurityTierModifiers({
    required this.password,
    required this.biometric,
  });

  @override
  int get hashCode => password.hashCode ^ biometric.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSecurityTierModifiers &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          biometric == other.biometric;
}
