// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Encode the `SecurityConfig` blob persisted under
/// `config.json::security`. Returns the minified JSON string —
/// caller `jsonDecode`s into a `Map<String, dynamic>` for the
/// existing `app_config.dart` consumers.
///
/// `tier_wire_name` must be one of `plaintext`, `keychain`,
/// `keychain_with_password`, `hardware`, `paranoid` (Dart `_tierToString`
/// emits these). Unknown wire names surface as `Err` so the caller
/// surfaces the misuse instead of silently picking plaintext.
String securityConfigToJson({
  required String tierWireName,
  required bool password,
  required bool biometric,
  required bool biometricShortcut,
  required int pinLength,
}) => RustLib.instance.api.crateApiSecurityConfigSecurityConfigToJson(
  tierWireName: tierWireName,
  password: password,
  biometric: biometric,
  biometricShortcut: biometricShortcut,
  pinLength: pinLength,
);

/// Encode the modifiers blob alone — used by callers that want to
/// re-serialise `SecurityTierModifiers` without going through the
/// outer `SecurityConfig` wrapper.
String securityTierModifiersToJson({
  required bool password,
  required bool biometric,
  required bool biometricShortcut,
  required int pinLength,
}) => RustLib.instance.api.crateApiSecurityConfigSecurityTierModifiersToJson(
  password: password,
  biometric: biometric,
  biometricShortcut: biometricShortcut,
  pinLength: pinLength,
);

/// Parse the `security` JSON object. Mirrors `SecurityConfig.fromJson`
/// Dart-side: an unknown / missing tier string falls through to
/// `plaintext` so the caller routes into the wizard rather than
/// silently picking an unintended tier; missing modifiers fall back
/// to defaults.
DbSecurityConfig? securityConfigFromJson({required String json}) => RustLib
    .instance
    .api
    .crateApiSecurityConfigSecurityConfigFromJson(json: json);

DbSecurityTierModifiers? securityTierModifiersFromJson({
  required String json,
}) => RustLib.instance.api.crateApiSecurityConfigSecurityTierModifiersFromJson(
  json: json,
);

/// Flat DTO for a parsed `SecurityConfig` — tier wire name +
/// per-modifier scalars, returned across the FRB boundary so the
/// Dart caller can rebuild its own `SecurityConfig` instance
/// without re-importing the enum from a generated file.
class DbSecurityConfig {
  final String tierWireName;
  final bool password;
  final bool biometric;
  final bool biometricShortcut;
  final int pinLength;

  const DbSecurityConfig({
    required this.tierWireName,
    required this.password,
    required this.biometric,
    required this.biometricShortcut,
    required this.pinLength,
  });

  @override
  int get hashCode =>
      tierWireName.hashCode ^
      password.hashCode ^
      biometric.hashCode ^
      biometricShortcut.hashCode ^
      pinLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSecurityConfig &&
          runtimeType == other.runtimeType &&
          tierWireName == other.tierWireName &&
          password == other.password &&
          biometric == other.biometric &&
          biometricShortcut == other.biometricShortcut &&
          pinLength == other.pinLength;
}

/// FRB-side mirror of just the modifiers block.
class DbSecurityTierModifiers {
  final bool password;
  final bool biometric;
  final bool biometricShortcut;
  final int pinLength;

  const DbSecurityTierModifiers({
    required this.password,
    required this.biometric,
    required this.biometricShortcut,
    required this.pinLength,
  });

  @override
  int get hashCode =>
      password.hashCode ^
      biometric.hashCode ^
      biometricShortcut.hashCode ^
      pinLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSecurityTierModifiers &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          biometric == other.biometric &&
          biometricShortcut == other.biometricShortcut &&
          pinLength == other.pinLength;
}
