// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Case-insensitive substring search across [`label`, `folder`,
/// `host`, `user`]. Returns matched ids in input order.
List<String> sessionsFilter({
  required List<DbSearchableSession> items,
  required String query,
}) => RustLib.instance.api.crateApiSessionsSessionsFilter(
  items: items,
  query: query,
);

/// Validate a session's storable-field set: host non-empty, port in
/// 1..=65535, user non-empty. Returns the user-facing error message
/// or `None` when the session is storable. Same grammar as
/// `Session.validate` Dart-side.
String? sessionsValidateFields({
  required String host,
  required int port,
  required String user,
}) => RustLib.instance.api.crateApiSessionsSessionsValidateFields(
  host: host,
  port: port,
  user: user,
);

/// Count session folders matching [`folder_path`] exactly or sitting
/// under `{folder_path}/`. Empty path counts root-level sessions.
int sessionsCountInFolder({
  required List<String> sessionFolders,
  required String folderPath,
}) => RustLib.instance.api.crateApiSessionsSessionsCountInFolder(
  sessionFolders: sessionFolders,
  folderPath: folderPath,
);

/// Return a label that does not collide with any entry in
/// [`taken`]. Identity for free `base`; otherwise appends
/// `(copy)`, `(copy 2)`, `(copy 3)`, … until a free slot is found.
/// Empty `base` passes through unchanged.
String sessionsUniqueLabel({
  required String base,
  required List<String> taken,
}) => RustLib.instance.api.crateApiSessionsSessionsUniqueLabel(
  base: base,
  taken: taken,
);

/// Searchable Session projection — id + the four fields the UI
/// search bar matches against. The Dart caller projects its
/// domain `Session` list once and feeds it here, avoiding a
/// credential round-trip across FFI.
class DbSearchableSession {
  final String id;
  final String label;
  final String folder;
  final String host;
  final String user;

  const DbSearchableSession({
    required this.id,
    required this.label,
    required this.folder,
    required this.host,
    required this.user,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      folder.hashCode ^
      host.hashCode ^
      user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSearchableSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          folder == other.folder &&
          host == other.host &&
          user == other.user;
}
