// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Case-insensitive substring search across [`label`, `folder`,
/// `host`, `user`]. Returns matched ids in input order.
List<String> sessionsFilter({
  required List<DbSearchableSession> items,
  required String query,
}) => RustLib.instance.api.crateApiSessionsSessionsFilter(
  items: items,
  query: query,
);

/// Searchable Session projection — id + the four fields the UI
/// search bar matches against. The Dart caller projects its
/// domain `Session` list once and feeds it here, avoiding a
/// credential round-trip across FFI.
class DbSearchableSession {
  final String id;
  final String label;
  final String folder;
  final String host;
  final String user;

  const DbSearchableSession({
    required this.id,
    required this.label,
    required this.folder,
    required this.host,
    required this.user,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      folder.hashCode ^
      host.hashCode ^
      user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSearchableSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          folder == other.folder &&
          host == other.host &&
          user == other.user;
}
