// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Render Unix mode bits as `drwxr-xr-x`. `mode == 0` produces
/// `---` (LocalFS entries that didn't fetch perms).
String sftpModeString({required int mode, required bool isDir}) => RustLib
    .instance
    .api
    .crateApiSftpModelsSftpModeString(mode: mode, isDir: isDir);

/// Stable directory-first then by the active column + direction.
/// Returns the sort permutation as indices into the input list —
/// the caller re-keys its FileEntry list against these indices,
/// avoiding a struct round-trip across FFI. Directories always lead
/// regardless of column / direction; only the within-kind order
/// responds to `field` + `ascending`.
Uint32List sftpSortFileEntriesBy({
  required List<DbFileSortKey> keys,
  required DbSortField field,
  required bool ascending,
}) => RustLib.instance.api.crateApiSftpModelsSftpSortFileEntriesBy(
  keys: keys,
  field: field,
  ascending: ascending,
);

/// Classify a directory entry into the icon/colour bucket the file
/// browser renders. Directory + symlink flags take precedence over
/// the name's extension. See [`lfs_core::sftp_models::file_kind`].
DbFileKind sftpFileKind({
  required String name,
  required bool isDir,
  required bool isSymlink,
}) => RustLib.instance.api.crateApiSftpModelsSftpFileKind(
  name: name,
  isDir: isDir,
  isSymlink: isSymlink,
);

/// File classification — mirrors `lfs_core::sftp_models::FileKind`.
/// The Dart side maps each variant to an `IconData` + theme colour
/// (a rendering concern); the classification itself stays Rust-owned.
enum DbFileKind {
  directory,
  symlink,
  image,
  archive,
  code,
  audio,
  video,
  document,
  binary,
  plain,
}

/// Caller-projected sort key — mirrors `lfs_core::sftp_models::SortKey`
/// across the FFI boundary. Carries every sortable axis so the
/// caller never re-implements a per-column comparison Dart-side; the
/// active [`DbSortField`] picks which fields the comparator reads.
class DbFileSortKey {
  final bool isDir;
  final String nameLower;
  final BigInt size;
  final int mode;
  final PlatformInt64 modTimeUnixMs;
  final String ownerLower;

  const DbFileSortKey({
    required this.isDir,
    required this.nameLower,
    required this.size,
    required this.mode,
    required this.modTimeUnixMs,
    required this.ownerLower,
  });

  @override
  int get hashCode =>
      isDir.hashCode ^
      nameLower.hashCode ^
      size.hashCode ^
      mode.hashCode ^
      modTimeUnixMs.hashCode ^
      ownerLower.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbFileSortKey &&
          runtimeType == other.runtimeType &&
          isDir == other.isDir &&
          nameLower == other.nameLower &&
          size == other.size &&
          mode == other.mode &&
          modTimeUnixMs == other.modTimeUnixMs &&
          ownerLower == other.ownerLower;
}

/// Which column the file table is sorted by — mirrors
/// `lfs_core::sftp_models::SortField`.
enum DbSortField { name, size, mode, modified, owner }
