// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Render the snippet command, substituting `{{name}}` tokens
/// against [`context`].
DbRenderedSnippet snippetTemplateRender({
  required String template,
  required List<(String, String)> context,
}) => RustLib.instance.api.crateApiSnippetTemplateSnippetTemplateRender(
  template: template,
  context: context,
);

/// Substitute [`values`] for `{{name}}` tokens left behind by
/// [`snippet_template_render`]. Used by the picker after the
/// prompt dialog collects the user's input for each unresolved
/// token.
String snippetTemplateFillUnresolved({
  required String partiallyRendered,
  required List<(String, String)> values,
}) => RustLib.instance.api.crateApiSnippetTemplateSnippetTemplateFillUnresolved(
  partiallyRendered: partiallyRendered,
  values: values,
);

/// Result of [`snippet_template_render`].
class DbRenderedSnippet {
  final String rendered;

  /// Unknown token names in first-seen order, no duplicates.
  final List<String> unresolved;

  const DbRenderedSnippet({required this.rendered, required this.unresolved});

  @override
  int get hashCode => rendered.hashCode ^ unresolved.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbRenderedSnippet &&
          runtimeType == other.runtimeType &&
          rendered == other.rendered &&
          unresolved == other.unresolved;
}
