// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ssh.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `cancel_remote_forward_inner`, `from_core`, `next_forwarded_connection_inner`, `open_direct_tcpip_inner`, `open_sftp_inner`, `request_remote_forward_inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Probe an SSH server with username + password.
///
/// Returns `Ok(())` on successful auth (server immediately
/// disconnected after); throws a typed Dart exception on connect
/// failure, host-key rejection, or auth failure.
///
/// Sub-phase 1.1 surface — sub-phase 1.3 introduces a long-lived
/// session handle and the full `SshTransport` interface on the Dart
/// side.
Future<void> sshTryConnectPassword({
  required String host,
  required int port,
  required String user,
  required String password,
}) => RustLib.instance.api.crateApiSshSshTryConnectPassword(
  host: host,
  port: port,
  user: user,
  password: password,
);

/// Probe an SSH server with username + private key.
///
/// Accepts OpenSSH PEM (`-----BEGIN OPENSSH PRIVATE KEY-----`) and
/// PuTTY PPK (v2 + v3 / Argon2id, `PuTTY-User-Key-File-...`).
/// `passphrase` is required only when the key file is encrypted.
///
/// Legacy PEM PKCS#1 / PKCS#8 (`-----BEGIN RSA PRIVATE KEY-----`
/// etc.) lands at sub-phase 1.4b.
Future<void> sshTryConnectPubkey({
  required String host,
  required int port,
  required String user,
  required List<int> privateKey,
  String? passphrase,
}) => RustLib.instance.api.crateApiSshSshTryConnectPubkey(
  host: host,
  port: port,
  user: user,
  privateKey: privateKey,
  passphrase: passphrase,
);

/// Connect + authenticate with username + password. Returns a live
/// `SshSession` ready for `open_shell` / future SFTP / port-forward
/// methods.
Future<SshSession> sshConnectPassword({
  required String host,
  required int port,
  required String user,
  required String password,
}) => RustLib.instance.api.crateApiSshSshConnectPassword(
  host: host,
  port: port,
  user: user,
  password: password,
);

/// Connect + authenticate by delegating signing to the system SSH
/// agent ($SSH_AUTH_SOCK on Unix, OpenSSH-style named pipe on Windows,
/// Pageant on Windows fallback). Iterates over the agent's identities
/// in order; first identity the server accepts wins. Errors with
/// `auth failed` only if every identity is rejected (the typical
/// remediation is `ssh-add` of the desired key, then retry).
///
/// **FIDO2 sk-* keys go through this path** — when the agent has
/// security-key identities registered (`ssh-add -K`), the agent
/// itself drives the CTAP2 user-presence prompt; russh just relays
/// the resulting signature. So this function also covers §6.3
/// hardware-token auth without any local FIDO2 stack.
///
/// Implementation: russh's `AgentClient` produces per-method futures
/// that are not `Send` — the all-identities iteration in
/// `Session::connect_agent` therefore can't run inside FRB's
/// `Send + 'static`-bounded async wrapper. We dispatch the work on
/// `tokio::task::spawn_blocking` and drive the future with a fresh
/// runtime handle's `block_on`, keeping the non-Send future on a
/// dedicated blocking-pool thread that never crosses thread
/// boundaries.
Future<SshSession> sshConnectAgent({
  required String host,
  required int port,
  required String user,
}) => RustLib.instance.api.crateApiSshSshConnectAgent(
  host: host,
  port: port,
  user: user,
);

/// Connect + authenticate with an OpenSSH **certificate** (an SSH
/// public key signed by a CA, plus the matching private key).
///
/// `private_key` accepts either OpenSSH PEM (`-----BEGIN OPENSSH
/// PRIVATE KEY-----`) or PuTTY PPK formats (same dispatch as
/// `ssh_connect_pubkey`); `cert` accepts the OpenSSH cert blob (the
/// `-cert.pub` companion file produced by `ssh-keygen -s ca_key
/// id_*.pub`). Server must trust the issuing CA via
/// `TrustedUserCAKeys`.
///
/// Sub-phase 1.12 — §6.2 surface.
Future<SshSession> sshConnectPubkeyCert({
  required String host,
  required int port,
  required String user,
  required List<int> privateKey,
  String? passphrase,
  required List<int> cert,
}) => RustLib.instance.api.crateApiSshSshConnectPubkeyCert(
  host: host,
  port: port,
  user: user,
  privateKey: privateKey,
  passphrase: passphrase,
  cert: cert,
);

/// Connect + authenticate with username + private key. Accepts both
/// OpenSSH PEM and PuTTY PPK formats (see `ssh_try_connect_pubkey`
/// for the format list). `passphrase` is required only when the key
/// file is encrypted.
Future<SshSession> sshConnectPubkey({
  required String host,
  required int port,
  required String user,
  required List<int> privateKey,
  String? passphrase,
}) => RustLib.instance.api.crateApiSshSshConnectPubkey(
  host: host,
  port: port,
  user: user,
  privateKey: privateKey,
  passphrase: passphrase,
);

/// Password auth using a SecretStore-stored password.
Future<SshSession> sshConnectPasswordWithSecret({
  required String host,
  required int port,
  required String user,
  required String passwordSecretId,
}) => RustLib.instance.api.crateApiSshSshConnectPasswordWithSecret(
  host: host,
  port: port,
  user: user,
  passwordSecretId: passwordSecretId,
);

/// Pubkey auth using SecretStore-stored bytes. `passphrase_secret_id`
/// is optional — pass `None` for unencrypted keys.
Future<SshSession> sshConnectPubkeyWithSecret({
  required String host,
  required int port,
  required String user,
  required String keySecretId,
  String? passphraseSecretId,
}) => RustLib.instance.api.crateApiSshSshConnectPubkeyWithSecret(
  host: host,
  port: port,
  user: user,
  keySecretId: keySecretId,
  passphraseSecretId: passphraseSecretId,
);

/// OpenSSH-cert auth using SecretStore-stored bytes.
Future<SshSession> sshConnectPubkeyCertWithSecret({
  required String host,
  required int port,
  required String user,
  required String keySecretId,
  required String certSecretId,
  String? passphraseSecretId,
}) => RustLib.instance.api.crateApiSshSshConnectPubkeyCertWithSecret(
  host: host,
  port: port,
  user: user,
  keySecretId: keySecretId,
  certSecretId: certSecretId,
  passphraseSecretId: passphraseSecretId,
);

/// Password auth tunnelled through `parent`.
Future<SshSession> sshConnectPasswordViaProxy({
  required SshSession parent,
  required String host,
  required int port,
  required String user,
  required String password,
}) => RustLib.instance.api.crateApiSshSshConnectPasswordViaProxy(
  parent: parent,
  host: host,
  port: port,
  user: user,
  password: password,
);

/// Pubkey auth tunnelled through `parent`.
Future<SshSession> sshConnectPubkeyViaProxy({
  required SshSession parent,
  required String host,
  required int port,
  required String user,
  required List<int> privateKey,
  String? passphrase,
}) => RustLib.instance.api.crateApiSshSshConnectPubkeyViaProxy(
  parent: parent,
  host: host,
  port: port,
  user: user,
  privateKey: privateKey,
  passphrase: passphrase,
);

/// OpenSSH cert auth tunnelled through `parent`.
Future<SshSession> sshConnectPubkeyCertViaProxy({
  required SshSession parent,
  required String host,
  required int port,
  required String user,
  required List<int> privateKey,
  String? passphrase,
  required List<int> cert,
}) => RustLib.instance.api.crateApiSshSshConnectPubkeyCertViaProxy(
  parent: parent,
  host: host,
  port: port,
  user: user,
  privateKey: privateKey,
  passphrase: passphrase,
  cert: cert,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshSession>>
abstract class SshSession implements RustOpaqueInterface {
  /// Send `SSH_MSG_DISCONNECT` and tear down. Idempotent — calling
  /// twice (or after `Drop`) is a no-op.
  Future<void> disconnect();

  /// Open a PTY-backed shell channel sized to `cols × rows`.
  /// Returned `SshShell` lives independently of the session — the
  /// session can be dropped while the shell is still in use; russh
  /// then errors out the next read / write.
  Future<SshShell> openShell({required int cols, required int rows});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshShell>>
abstract class SshShell implements RustOpaqueInterface {
  /// Send EOF on stdin. The server typically interprets this as
  /// "user closed stdin" and exits the foreground program.
  Future<void> eof();

  /// Long-running task that pumps shell events into a Dart-side
  /// `Stream<SshShellEvent>`. Returns when the channel closes (the
  /// remote sent `Close` / `Eof`) or when the Dart subscription is
  /// cancelled (sink rejects further `add`s).
  ///
  /// Sub-phase 1.3b surface — the Dart-side terminal widget binds
  /// `terminal.write(...)` to the `Output` / `ExtendedOutput`
  /// variants and surfaces `ExitStatus` / `ExitSignal` to the
  /// connection-state UI. Since `SshShell::next_event` already
  /// serialises the read half through a tokio `Mutex`, calling
  /// this method twice on the same shell would deadlock — caller
  /// must ensure a single subscriber per shell.
  Stream<SshShellEvent> eventsStream();

  /// Wait for the next event from the remote — output bytes,
  /// extended (stderr) bytes, EOF, or an exit-status / exit-signal.
  /// Returns `null` on the Dart side once the channel is fully
  /// closed.
  Future<SshShellEvent?> nextEvent();

  /// Notify the remote of a terminal-window resize. `pix_width` /
  /// `pix_height` default to 0 internally — almost no terminal
  /// cares about pixel dimensions over character cells.
  Future<void> resize({required int cols, required int rows});

  /// Send stdin bytes to the remote shell.
  Future<void> write({required List<int> data});
}

@freezed
sealed class SshShellEvent with _$SshShellEvent {
  const SshShellEvent._();

  const factory SshShellEvent.output(Uint8List field0) = SshShellEvent_Output;
  const factory SshShellEvent.extendedOutput(Uint8List field0) =
      SshShellEvent_ExtendedOutput;
  const factory SshShellEvent.eof() = SshShellEvent_Eof;
  const factory SshShellEvent.exitStatus(int field0) = SshShellEvent_ExitStatus;
  const factory SshShellEvent.exitSignal(String field0) =
      SshShellEvent_ExitSignal;
}
