// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'ssh.dart';
part 'terminal.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `from_core`, `from_core`, `from_core`, `from_core`, `from_core`, `into_core`, `into_core`, `into_core`, `into_core`, `into_core`, `into_core`, `into_core`, `into_core`, `partition_drained`, `pty_write_back_failed_line`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The OneDark default palette as a DTO. The Dart theme layer uses this
/// as the starting point before overriding swatches from AppTheme.
TerminalPalette terminalPaletteDefault() =>
    RustLib.instance.api.crateApiTerminalTerminalPaletteDefault();

/// Open a PTY-backed shell on `session`, build the engine, and return a
/// `TerminalSession` handle. The pump does NOT start here — the caller
/// then calls [`TerminalSession::events`] with a `StreamSink` to begin
/// pumping output. This is where Dart obtains a terminal for a connection.
///
/// Open-shape rationale: the function opens the shell itself rather than
/// taking an already-opened `SshShell`. The terminal must be the
/// **single** consumer of the shell's events (the read-half is a
/// single-reader mutex — two consumers deadlock), so coupling the open to
/// the session makes that ownership unambiguous: a `TerminalSession`
/// always owns the shell it pumps, and there is no window where a Dart
/// `events_stream` could have grabbed the same shell first. The
/// non-terminal `SshShell` / `events_stream` path stays untouched for
/// callers that do not want a terminal model.
///
/// Two-call shape (`open` returns the handle, `events` takes the sink):
/// FRB collapses any function carrying a `StreamSink` parameter into a
/// stream-returning function and drops its `Result` value, so the open
/// could not both return the handle and take the sink. Splitting them
/// also matches the `SshShell::events_stream` idiom — open the resource,
/// then subscribe.
Future<TerminalSession> terminalSessionOpen({
  required SshSession session,
  required int cols,
  required int rows,
  required int scrollback,
  required TerminalPalette palette,
}) => RustLib.instance.api.crateApiTerminalTerminalSessionOpen(
  session: session,
  cols: cols,
  rows: rows,
  scrollback: scrollback,
  palette: palette,
);

/// Build a shell-less replay engine sized `cols × rows` with `scrollback`
/// history lines and `palette` colors. No PTY is opened and no pump task is
/// spawned — the caller feeds bytes with [`TerminalReplay::feed`] and pulls
/// frames with [`TerminalReplay::snapshot`].
TerminalReplay terminalReplayOpen({
  required int cols,
  required int rows,
  required int scrollback,
  required TerminalPalette palette,
}) => RustLib.instance.api.crateApiTerminalTerminalReplayOpen(
  cols: cols,
  rows: rows,
  scrollback: scrollback,
  palette: palette,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TerminalReplay>>
abstract class TerminalReplay implements RustOpaqueInterface {
  /// Wipe the visible grid AND scrollback, homing the cursor. The recording
  /// scrub path calls this before re-feeding `0..target` so alt-screen /
  /// scroll-region / character-attribute modes from the prior position
  /// cannot bleed into the rebuild. Sync — same lock shape as
  /// [`Self::feed`].
  void clear();

  /// Clear any active selection. Sync — same lock shape as [`Self::feed`].
  void clearSelection();

  /// Feed bytes into the engine grid, then drain and DISCARD the engine's
  /// event queue. A replay has no shell to forward `PtyWrite` replies to,
  /// and no host wired to bell / title on these read-only surfaces, so the
  /// drained queue is dropped — but it is still drained so it does not grow
  /// unbounded across a long replay. The caller pulls a fresh snapshot and
  /// repaints itself; no `Wakeup` event stream exists. Sync so a feeder
  /// (progress writer, log viewer, scrub loop) can push a tight burst of
  /// frames and pull one snapshot without an `await` per write — the only
  /// contender for the lock is the feeder's own calls.
  void feed({required List<int> bytes});

  /// Resize the engine grid. There is no remote PTY to notify (shell-less),
  /// so this only reflows the local model. Sync — same lock shape as
  /// [`Self::feed`].
  void resize({required int cols, required int rows});

  /// The text covered by the active selection, or `None` when there is no
  /// selection. Sync — same lock shape as [`Self::feed`].
  String? selectionText();

  /// Replace the color palette (e.g. on a theme toggle). Takes effect on
  /// the next snapshot; already-parsed cells re-resolve their abstract
  /// colors against the new palette. Sync — same lock shape as
  /// [`Self::feed`].
  void setPalette({required TerminalPalette palette});

  /// Set a selection spanning `start` to `end` in absolute grid coordinates
  /// (negative row = scrollback). Read the covered text back with
  /// [`Self::selection_text`]. Sync — the read-only surfaces drive selection
  /// from a pointer drag and pull a fresh snapshot immediately after, so the
  /// same no-`await` lock shape as [`Self::feed`] keeps drag latency low.
  void setSelection({
    required int startRow,
    required int startCol,
    required int endRow,
    required int endCol,
    required TerminalSelectionKind kind,
  });

  /// Build an owned render snapshot of the current viewport. Sync so the
  /// feeder pulls a frame without an `await` per paint — the only contender
  /// for the lock is the feeder's own `feed`, never an async pump.
  TerminalFrame snapshot();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TerminalSession>>
abstract class TerminalSession implements RustOpaqueInterface {
  /// Wipe the terminal: blank the visible grid AND purge the scrollback
  /// history, homing the cursor. The auto-lock / wipe scrub path calls
  /// this when the DB key is cleared so buffered command output cannot be
  /// read back from scrollback — `scroll_to_bottom` only moves the
  /// viewport and would leave the sensitive content in memory.
  ///
  /// Locks the engine, clears, releases, then pushes one `Wakeup` onto the
  /// pump's UI-event stream so the renderer pulls a fresh (now-blank)
  /// snapshot. The sink clone and the `add` run after the engine lock is
  /// dropped — neither lock is held across an `await`. If the pump has not
  /// started (no sink stashed yet) the grid is still cleared; the next
  /// pump output drives the repaint.
  Future<void> clear();

  /// Clear any active selection.
  Future<void> clearSelection();

  /// Start the Rust-owned shell→engine→shell pump and stream UI events to
  /// `sink`. Call exactly once per session — the pump is the single
  /// consumer of the shell's events; a second call would deadlock the two
  /// readers on the shell's read-half mutex. Returns when the shell closes
  /// (remote `Eof` / `next_event` returns `None`) or the Dart `sink`
  /// rejects an `add` (subscription cancelled).
  ///
  /// The pump reads shell output, locks the engine, feeds the bytes,
  /// drains the side-effect queue, releases the lock, then forwards every
  /// `PtyWrite` back to the shell Rust→Rust and pushes the translated
  /// UI events (coalesced `Wakeup`, bell, title, clipboard) to `sink`.
  ///
  /// Recorder / broadcast fork hook: when the live terminal pane moves to
  /// `TerminalSession`, the per-byte fork to the session recorder and the
  /// broadcast controller (today in Dart's `shell_helper.dart`) moves
  /// into the pump body, right after the output bytes are read and before
  /// they are fed into the engine. The loop is shaped so that hook slots
  /// in without reshaping the lock/await ordering.
  Stream<TerminalUiEvent> events();

  /// Encode pasted text against the engine's current mode and write it to
  /// the shell. Under bracketed-paste mode the body is framed with
  /// `\x1b[200~` … `\x1b[201~` (and any embedded terminator stripped per
  /// the paste-safety rule); otherwise the raw bytes go through. Same
  /// lock discipline as [`Self::send_key`].
  Future<void> paste({required String text});

  /// Resize the viewport: the engine reflows the grid and the shell
  /// notifies the remote of the new window size. Both must happen — the
  /// engine for the local model, the `window_change` so the remote PTY
  /// (and any `SIGWINCH`-aware program) sees it.
  Future<void> resize({required int cols, required int rows});

  /// Scroll the viewport by `delta` lines (positive = up into
  /// scrollback, negative = back toward the live screen).
  Future<void> scroll({required int delta});

  /// Jump the viewport to the live screen (bottom).
  Future<void> scrollToBottom();

  /// Scan the grid + scrollback for every literal occurrence of `query`.
  /// Returns matches in absolute grid-line coordinates.
  Future<List<TerminalMatch>> search({required String query});

  /// The text covered by the active selection, or `None` when there is
  /// no selection.
  Future<String?> selectionText();

  /// Encode a key press against the engine's **current** terminal mode
  /// and write the resulting VT bytes to the shell. The mode read is why
  /// this is Rust-side: arrows flip to SS3 form under DECCKM, Enter
  /// becomes CR+LF under LNM, etc., and only the engine holds that state.
  ///
  /// Lock discipline: the engine lock is taken only to read the mode
  /// (a synchronous `Copy` read), released, and the encode + `shell.write`
  /// run after — the lock is never held across the `await`, matching the
  /// pump's discipline. An empty encoding (e.g. an out-of-range F-key)
  /// writes nothing rather than an empty frame.
  Future<void> sendKey({required TerminalKey key});

  /// Encode a mouse event against the engine's current mode and write the
  /// report to the shell. Returns without writing when the running
  /// program does not report that event (no tracking, or a motion event
  /// under a click-only mode) — the renderer only calls this when the
  /// frame already showed tracking is active, but the mode is re-read
  /// here so the gate is authoritative even if the frame the renderer
  /// saw was a tick stale. Same lock discipline as [`Self::send_key`]:
  /// the engine lock is taken only to read the mode and released before
  /// the `shell.write`.
  Future<void> sendMouse({required TerminalMouseInput event});

  /// Replace the color palette (e.g. on theme change). Takes effect on
  /// the next snapshot; already-parsed cells keep their abstract colors
  /// and re-resolve against the new palette.
  Future<void> setPalette({required TerminalPalette palette});

  /// Set a selection spanning `start` to `end` in absolute grid
  /// coordinates (negative row = scrollback). Read the covered text back
  /// with [`Self::selection_text`].
  Future<void> setSelection({
    required int startRow,
    required int startCol,
    required int endRow,
    required int endCol,
    required TerminalSelectionKind kind,
  });

  /// Build an owned render snapshot of the current viewport. Sync so the
  /// renderer pulls a frame without an `await` per paint. Uses
  /// `blocking_lock` because the only writer is the pump, which holds the
  /// lock for a single non-awaiting feed/drain — contention is bounded
  /// and never crosses an `await`.
  TerminalFrame snapshot();

  /// Forward Dart key bytes straight to the remote shell's stdin. The
  /// engine processes only **server output**, never local input — so
  /// input bypasses the engine entirely (the server echoes it back, and
  /// that echo is what the engine renders). Callers that already hold
  /// encoded bytes (snippets, `sendCommand`) use this; live keystrokes
  /// go through [`Self::send_key`] so the encoding reads the live mode.
  Future<void> writeInput({required List<int> bytes});
}

/// One painted cell. `ch` is the primary character as a Unicode scalar
/// (`u32`) — FRB has no `char`, and the renderer re-materialises it with
/// `String.fromCharCode`. `fg`/`bg` are already resolved to concrete RGB
/// (INVERSE/DIM applied) so the renderer never resolves color. `flags`
/// is the raw `alacritty_terminal` attribute bitfield widened to `u32`
/// (the core type is `u16`; FRB marshals `u32` cleanly and the extra
/// bits stay zero).
class TerminalCell {
  final int row;
  final int col;
  final int ch;
  final TerminalColor fg;
  final TerminalColor bg;
  final int flags;

  const TerminalCell({
    required this.row,
    required this.col,
    required this.ch,
    required this.fg,
    required this.bg,
    required this.flags,
  });

  @override
  int get hashCode =>
      row.hashCode ^
      col.hashCode ^
      ch.hashCode ^
      fg.hashCode ^
      bg.hashCode ^
      flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalCell &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          col == other.col &&
          ch == other.ch &&
          fg == other.fg &&
          bg == other.bg &&
          flags == other.flags;
}

/// FRB-friendly 24-bit color — three `u8` channels. Mirrors
/// `lfs_core::terminal::Rgb` without leaking the core type across the
/// boundary (the core `Rgb` lives in a module the bridge must not
/// re-export per the data-ownership pillar).
class TerminalColor {
  final int r;
  final int g;
  final int b;

  const TerminalColor({required this.r, required this.g, required this.b});

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalColor &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b;
}

/// Cursor position + shape for one frame. `row` is in display-viewport
/// coordinates (`0` = top visible line).
class TerminalCursor {
  final int row;
  final int col;
  final TerminalCursorShape shape;
  final bool visible;

  const TerminalCursor({
    required this.row,
    required this.col,
    required this.shape,
    required this.visible,
  });

  @override
  int get hashCode =>
      row.hashCode ^ col.hashCode ^ shape.hashCode ^ visible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalCursor &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          col == other.col &&
          shape == other.shape &&
          visible == other.visible;
}

/// Cursor rendering shape — FRB mirror of
/// `lfs_core::terminal::CursorShape`.
enum TerminalCursorShape { block, underline, beam, hollowBlock, hidden }

/// Complete render state for one paint — FRB mirror of
/// `lfs_core::terminal::Frame`. The `cells` vector is sparse: blank
/// default cells are omitted, so the renderer clears to the background
/// once and overlays only the non-blank cells.
class TerminalFrame {
  final int cols;
  final int rows;
  final TerminalCursor cursor;

  /// How many lines the viewport is scrolled up into scrollback.
  /// `0` = the live screen is showing.
  final int displayOffset;

  /// Total scrollback lines available above the live screen.
  final int historySize;

  /// Mouse-tracking level the running program enabled — the renderer
  /// routes pointer events off this.
  final TerminalMouseTracking mouseTracking;
  final List<TerminalCell> cells;
  final TerminalFrameSelection? selection;

  const TerminalFrame({
    required this.cols,
    required this.rows,
    required this.cursor,
    required this.displayOffset,
    required this.historySize,
    required this.mouseTracking,
    required this.cells,
    this.selection,
  });

  @override
  int get hashCode =>
      cols.hashCode ^
      rows.hashCode ^
      cursor.hashCode ^
      displayOffset.hashCode ^
      historySize.hashCode ^
      mouseTracking.hashCode ^
      cells.hashCode ^
      selection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalFrame &&
          runtimeType == other.runtimeType &&
          cols == other.cols &&
          rows == other.rows &&
          cursor == other.cursor &&
          displayOffset == other.displayOffset &&
          historySize == other.historySize &&
          mouseTracking == other.mouseTracking &&
          cells == other.cells &&
          selection == other.selection;
}

/// Selection span for one frame, in viewport-row coordinates.
class TerminalFrameSelection {
  final int startRow;
  final int startCol;
  final int endRow;
  final int endCol;
  final bool isBlock;

  const TerminalFrameSelection({
    required this.startRow,
    required this.startCol,
    required this.endRow,
    required this.endCol,
    required this.isBlock,
  });

  @override
  int get hashCode =>
      startRow.hashCode ^
      startCol.hashCode ^
      endRow.hashCode ^
      endCol.hashCode ^
      isBlock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalFrameSelection &&
          runtimeType == other.runtimeType &&
          startRow == other.startRow &&
          startCol == other.startCol &&
          endRow == other.endRow &&
          endCol == other.endCol &&
          isBlock == other.isBlock;
}

/// FRB mirror of `lfs_core::terminal::KeyInput` — a normalised key event:
/// the logical key plus the modifier state. The Dart key-event layer
/// builds this from a `LogicalKeyboardKey` + `HardwareKeyboard` modifiers;
/// the encoder (`send_key`) reads the live terminal mode and produces the
/// VT byte sequence.
class TerminalKey {
  final TerminalKeyName name;
  final bool ctrl;
  final bool alt;
  final bool shift;
  final bool meta;

  const TerminalKey({
    required this.name,
    required this.ctrl,
    required this.alt,
    required this.shift,
    required this.meta,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      ctrl.hashCode ^
      alt.hashCode ^
      shift.hashCode ^
      meta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalKey &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          ctrl == other.ctrl &&
          alt == other.alt &&
          shift == other.shift &&
          meta == other.meta;
}

@freezed
sealed class TerminalKeyName with _$TerminalKeyName {
  const TerminalKeyName._();

  const factory TerminalKeyName.char({required int code}) =
      TerminalKeyName_Char;
  const factory TerminalKeyName.enter() = TerminalKeyName_Enter;
  const factory TerminalKeyName.tab() = TerminalKeyName_Tab;
  const factory TerminalKeyName.backspace() = TerminalKeyName_Backspace;
  const factory TerminalKeyName.escape() = TerminalKeyName_Escape;
  const factory TerminalKeyName.up() = TerminalKeyName_Up;
  const factory TerminalKeyName.down() = TerminalKeyName_Down;
  const factory TerminalKeyName.right() = TerminalKeyName_Right;
  const factory TerminalKeyName.left() = TerminalKeyName_Left;
  const factory TerminalKeyName.home() = TerminalKeyName_Home;
  const factory TerminalKeyName.end() = TerminalKeyName_End;
  const factory TerminalKeyName.pageUp() = TerminalKeyName_PageUp;
  const factory TerminalKeyName.pageDown() = TerminalKeyName_PageDown;
  const factory TerminalKeyName.insert() = TerminalKeyName_Insert;
  const factory TerminalKeyName.delete() = TerminalKeyName_Delete;
  const factory TerminalKeyName.f({required int number}) = TerminalKeyName_F;
}

/// One search match — FRB mirror of `lfs_core::terminal::MatchRange`, in
/// absolute grid-line coordinates (negative line = scrollback).
class TerminalMatch {
  final int line;
  final int startCol;
  final int endCol;

  const TerminalMatch({
    required this.line,
    required this.startCol,
    required this.endCol,
  });

  @override
  int get hashCode => line.hashCode ^ startCol.hashCode ^ endCol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalMatch &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          startCol == other.startCol &&
          endCol == other.endCol;
}

/// FRB mirror of `lfs_core::terminal::MouseAction`.
enum TerminalMouseAction { press, release, move }

/// FRB mirror of `lfs_core::terminal::MouseButton`. Wheel up/down ride the
/// same report channel as buttons; `None` is a bare motion with no button.
enum TerminalMouseButton { left, middle, right, wheelUp, wheelDown, none }

/// FRB mirror of `lfs_core::terminal::MouseInput`. `col`/`row` are 1-based
/// cell coordinates as they appear in the report — the Dart layer maps
/// pixels to a 0-based cell and adds 1 before crossing the boundary.
class TerminalMouseInput {
  final TerminalMouseButton button;
  final TerminalMouseAction action;
  final int col;
  final int row;
  final bool shift;
  final bool alt;
  final bool ctrl;

  const TerminalMouseInput({
    required this.button,
    required this.action,
    required this.col,
    required this.row,
    required this.shift,
    required this.alt,
    required this.ctrl,
  });

  @override
  int get hashCode =>
      button.hashCode ^
      action.hashCode ^
      col.hashCode ^
      row.hashCode ^
      shift.hashCode ^
      alt.hashCode ^
      ctrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalMouseInput &&
          runtimeType == other.runtimeType &&
          button == other.button &&
          action == other.action &&
          col == other.col &&
          row == other.row &&
          shift == other.shift &&
          alt == other.alt &&
          ctrl == other.ctrl;
}

/// Which mouse-tracking level the running program enabled — FRB mirror of
/// `lfs_core::terminal::MouseTracking`. The renderer reads it off each
/// frame to route a pointer drag to the program (mouse report) vs locally
/// (text selection), without an extra FFI call per pointer event.
enum TerminalMouseTracking {
  /// No tracking — the pointer drives local selection / scrollback.
  none,

  /// Click-only: press / release, no motion.
  click,

  /// Button-event: press / release + drag (button held).
  buttonEvent,

  /// Any-motion: press / release + drag + bare motion.
  anyMotion,
}

/// FRB-friendly palette: the 16 ANSI base colors plus the default
/// foreground / background / cursor / selection swatches. Converts into
/// the core [`TermPalette`]; the 256-color cube is derived inside the
/// engine, so it is not carried here. The Dart theme layer fills this
/// from AppTheme in a later task.
class TerminalPalette {
  /// Indices 0..16 in NamedColor order: black, red, green, yellow,
  /// blue, magenta, cyan, white, then their eight bright variants.
  final List<TerminalColor> ansi;
  final TerminalColor foreground;
  final TerminalColor background;
  final TerminalColor cursor;
  final TerminalColor selection;

  const TerminalPalette({
    required this.ansi,
    required this.foreground,
    required this.background,
    required this.cursor,
    required this.selection,
  });

  @override
  int get hashCode =>
      ansi.hashCode ^
      foreground.hashCode ^
      background.hashCode ^
      cursor.hashCode ^
      selection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalPalette &&
          runtimeType == other.runtimeType &&
          ansi == other.ansi &&
          foreground == other.foreground &&
          background == other.background &&
          cursor == other.cursor &&
          selection == other.selection;
}

/// Selection geometry — FRB mirror of
/// `lfs_core::terminal::SelectionKind`.
enum TerminalSelectionKind {
  simple,
  block,

  /// Word selection (double-click) — expands to semantic word boundaries.
  semantic,

  /// Whole-line selection (triple-click).
  lines,
}

@freezed
sealed class TerminalUiEvent with _$TerminalUiEvent {
  const TerminalUiEvent._();

  /// Grid content changed — the renderer should pull a fresh snapshot.
  /// Coalesced: one per fed chunk regardless of how many `Repaint`
  /// events the parser raised.
  const factory TerminalUiEvent.wakeup() = TerminalUiEvent_Wakeup;

  /// The terminal bell (`\x07`) rang.
  const factory TerminalUiEvent.bell() = TerminalUiEvent_Bell;

  /// The remote set the window/tab title (OSC 0/2).
  const factory TerminalUiEvent.title({required String title}) =
      TerminalUiEvent_Title;

  /// The remote reset the title to its default.
  const factory TerminalUiEvent.resetTitle() = TerminalUiEvent_ResetTitle;

  /// The remote requested storing text in the system clipboard (OSC 52).
  const factory TerminalUiEvent.clipboardStore({required String text}) =
      TerminalUiEvent_ClipboardStore;

  /// The shell channel closed (remote `Eof` / exit). The pump task has
  /// ended; no further events or snapshots will change.
  const factory TerminalUiEvent.closed() = TerminalUiEvent_Closed;
}
