// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `slot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Start an additional in-process russh-server fixture. Returns the
/// bound port + the OpenSSH-shaped public-key blob the caller seeds
/// into `known_hosts`. Each call generates a fresh Ed25519 host
/// keypair + a fresh SFTP-root tempdir, so multiple concurrent
/// fixtures stay independent.
Future<TestSshServerInfo> testSshServerStart() =>
    RustLib.instance.api.crateApiTestHooksTestSshServerStart();

/// Stop every running fixture. Safe to call multiple times — each
/// `shutdown()` on the underlying handle is idempotent.
void testSshServerStopAll() =>
    RustLib.instance.api.crateApiTestHooksTestSshServerStopAll();

/// Bundle returned to the Dart test caller. Carries everything a
/// test needs to drive a connect against the fixture: the bound
/// localhost port, the host-key shape (so the test can pre-seed
/// `known_hosts` and avoid the prompt round-trip), the fixed
/// password the fixture's `auth_password` handler accepts, and the
/// absolute filesystem path the SFTP subsystem is rooted at (tests
/// can drop fixture files there with `dart:io` before the SFTP
/// flow reads them, or assert against the same path after a PUT).
class TestSshServerInfo {
  final int port;
  final String hostPubkeyAlgorithm;
  final String hostPubkeyB64;
  final String password;
  final String sftpRoot;

  const TestSshServerInfo({
    required this.port,
    required this.hostPubkeyAlgorithm,
    required this.hostPubkeyB64,
    required this.password,
    required this.sftpRoot,
  });

  @override
  int get hashCode =>
      port.hashCode ^
      hostPubkeyAlgorithm.hashCode ^
      hostPubkeyB64.hashCode ^
      password.hashCode ^
      sftpRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TestSshServerInfo &&
          runtimeType == other.runtimeType &&
          port == other.port &&
          hostPubkeyAlgorithm == other.hostPubkeyAlgorithm &&
          hostPubkeyB64 == other.hostPubkeyB64 &&
          password == other.password &&
          sftpRoot == other.sftpRoot;
}
