// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'tier_machine.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `into_core`, `into_core`, `machine_lock`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`

/// Snapshot the current state. Returns `Locked` before any
/// dispatch lands (cold-boot default).
DbTierState tierMachineState() =>
    RustLib.instance.api.crateApiTierMachineTierMachineState();

/// Snapshot the active tier wire-name (`plaintext` /
/// `keychain` / `hardware` / `paranoid`). Mirrors
/// `SecurityTier::wire_name`.
String tierMachineActiveTierWireName() =>
    RustLib.instance.api.crateApiTierMachineTierMachineActiveTierWireName();

/// Replace the active tier. Caller (wizard / settings) pushes
/// the new tier in before kicking off `UnlockRequested`. Returns
/// the new tier's wire name; `Err` for an unknown wire name.
String tierMachineSetTier({required String tierWireName}) => RustLib
    .instance
    .api
    .crateApiTierMachineTierMachineSetTier(tierWireName: tierWireName);

/// Apply a transition. Returns the new state on success, `None`
/// when the event is invalid for the current state (caller logs
/// + drops). Tagged-enum shape — every variant maps to a concrete
/// `TierEvent` at the FRB type-system level, so an unknown
/// discriminant is a compile-time error, not a runtime drop.
DbTierState? tierMachineDispatch({required DbTierEvent event}) =>
    RustLib.instance.api.crateApiTierMachineTierMachineDispatch(event: event);

/// Per-tier handler hook — checks the current state + active
/// tier and self-advances if the tier needs no external input.
/// Returns the new state when an advance fired, `None`
/// otherwise.
///
/// Plaintext is the only tier that self-advances today; Dart
/// calls this immediately after dispatching `unlock_requested`
/// so the synchronous unlock path lands without waiting on a
/// no-op prompt round-trip. Keychain / Hardware / Paranoid
/// keep returning `None` until their per-tier handlers wire
/// in.
DbTierState? tierMachineTryAdvance() =>
    RustLib.instance.api.crateApiTierMachineTierMachineTryAdvance();

@freezed
sealed class DbTierEvent with _$DbTierEvent {
  const DbTierEvent._();

  const factory DbTierEvent.unlockRequested() = DbTierEvent_UnlockRequested;
  const factory DbTierEvent.unlockSucceeded() = DbTierEvent_UnlockSucceeded;
  const factory DbTierEvent.unlockFailed({
    required DbUnlockFailureReason reason,
  }) = DbTierEvent_UnlockFailed;
  const factory DbTierEvent.lockRequested() = DbTierEvent_LockRequested;
  const factory DbTierEvent.wiped() = DbTierEvent_Wiped;
}

/// FRB mirror of `lfs_core::security::tier_machine::TierState`.
enum DbTierState { locked, unlocking, unlocked, wiping }

@freezed
sealed class DbUnlockFailureReason with _$DbUnlockFailureReason {
  const DbUnlockFailureReason._();

  const factory DbUnlockFailureReason.wrongSecret() =
      DbUnlockFailureReason_WrongSecret;
  const factory DbUnlockFailureReason.pluginUnavailable({
    required String code,
  }) = DbUnlockFailureReason_PluginUnavailable;
  const factory DbUnlockFailureReason.userCancelled() =
      DbUnlockFailureReason_UserCancelled;
  const factory DbUnlockFailureReason.corruption({required String detail}) =
      DbUnlockFailureReason_Corruption;
}
