// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Plaintext tier — no secret, no plugin call, no user prompt.
/// Dispatches `UnlockRequested` then `UnlockSucceeded` against
/// the singleton tier machine; subscribers see two
/// `BusEvent::TierStateChanged` events (`unlocking` →
/// `unlocked`) on the `tier` topic. The Dart caller still owns
/// the drift-open step (drift is a Dart ORM); the orchestrator
/// just fast-paths the cascade visibility.
void tierUnlockPlaintext() =>
    RustLib.instance.api.crateApiTierUnlockOrchestratorTierUnlockPlaintext();

/// Keychain tier (L1) — read the DB encryption key from the OS
/// keychain via the prompt registry; emit cascade events along
/// the way; return the key bytes on success or `None` on
/// missing entry / plugin error.
///
/// Async — round-trips through the bus to the Dart subscriber
/// for the `flutter_secure_storage.read` call. The receiver
/// completes as soon as the subscriber resolves the prompt;
/// the FRB worker frees during the wait so the unlock dialog
/// stays responsive.
Future<Uint8List?> tierUnlockKeychain() =>
    RustLib.instance.api.crateApiTierUnlockOrchestratorTierUnlockKeychain();

/// KeychainWithPassword tier (L2) — verify the typed user
/// password through the on-disk gate, then read the DB
/// encryption key from the OS keychain. Emits cascade events
/// along the way; returns the key bytes on success or `None`
/// on wrong password / missing keychain entry / cancelled
/// prompt.
///
/// The Dart caller owns the unlock dialog UI (rate-limit
/// countdown, biometric option); after the user submits the
/// password the caller invokes this orchestrator to drive the
/// verify + key-read + cascade emission in one FRB hop.
Future<Uint8List?> tierUnlockKeychainWithPassword({required String password}) =>
    RustLib.instance.api
        .crateApiTierUnlockOrchestratorTierUnlockKeychainWithPassword(
          password: password,
        );

/// Paranoid tier — derive the DB key from the typed master
/// password via Argon2id; emit cascade events along the way;
/// return the key bytes on success or `None` on a wrong
/// password / corrupted KDF record.
///
/// The Dart caller owns the unlock dialog UI (rate-limit
/// countdown, "forgot password" reset path); after the user
/// submits the password the caller invokes this orchestrator
/// to drive the verify + cascade emission in one FRB hop.
///
/// Reads the support dir from the pinned singleton — caller
/// must have invoked `master_password_init` at app startup.
Future<Uint8List?> tierUnlockParanoid({required String password}) => RustLib
    .instance
    .api
    .crateApiTierUnlockOrchestratorTierUnlockParanoid(password: password);

/// Hardware tier (L3) — fan out a hardware-vault-unlock prompt
/// to the Dart subscriber + emit cascade events. `pin` is the
/// typed user secret for the password modifier; pass `None`
/// for the passwordless variant.
///
/// The Dart subscriber owns the platform call:
/// `HardwareTierVault.read(pin)` fans out to `tpm2-tools` on
/// Linux or the platform method channel on Apple / Android /
/// Windows. This orchestrator emits the cascade (UnlockRequested
/// → UnlockSucceeded / UnlockFailed) and returns the unsealed
/// key bytes for the Dart caller to hand to drift.
Future<Uint8List?> tierUnlockHardware({String? pin}) => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierUnlockHardware(pin: pin);

/// Resolve a pending hardware-vault unlock with success bytes.
/// `Ok(Some(bytes))` on a successful unseal; the orchestrator
/// dispatches `UnlockSucceeded` against the tier machine.
bool hardwareVaultUnlockPromptResolve({
  required String promptId,
  required List<int> bytes,
}) => RustLib.instance.api
    .crateApiTierUnlockOrchestratorHardwareVaultUnlockPromptResolve(
      promptId: promptId,
      bytes: bytes,
    );

/// Resolve a pending hardware-vault unlock with the
/// "wrong PIN / user cancel / hardware reported failure"
/// signal. `Ok(None)`. Orchestrator dispatches `UnlockFailed
/// { WrongSecret }`.
bool hardwareVaultUnlockPromptResolveWrong({required String promptId}) =>
    RustLib.instance.api
        .crateApiTierUnlockOrchestratorHardwareVaultUnlockPromptResolveWrong(
          promptId: promptId,
        );

/// Resolve a pending hardware-vault unlock with a plugin
/// error message. Orchestrator dispatches `UnlockFailed
/// { PluginUnavailable { code: message } }`.
bool hardwareVaultUnlockPromptResolveError({
  required String promptId,
  required String message,
}) => RustLib.instance.api
    .crateApiTierUnlockOrchestratorHardwareVaultUnlockPromptResolveError(
      promptId: promptId,
      message: message,
    );

/// Cancel a pending hardware-vault unlock without resolving —
/// used by the Dart subscriber when the unlock dialog is torn
/// down before the platform call returns. Idempotent on a
/// missing id.
void hardwareVaultUnlockPromptCancel({required String promptId}) => RustLib
    .instance
    .api
    .crateApiTierUnlockOrchestratorHardwareVaultUnlockPromptCancel(
      promptId: promptId,
    );
