// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'tier_unlock_orchestrator.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Plaintext tier — no secret, no plugin call, no user prompt.
/// Dispatches `UnlockRequested` then `UnlockSucceeded` against
/// the singleton tier machine; subscribers see two
/// `BusEvent::TierStateChanged` events (`unlocking` →
/// `unlocked`) on the `tier` topic. The Dart caller still owns
/// the drift-open step (drift is a Dart ORM); the orchestrator
/// just fast-paths the cascade visibility.
void tierUnlockPlaintext() =>
    RustLib.instance.api.crateApiTierUnlockOrchestratorTierUnlockPlaintext();

/// Keychain tier (L1) — read the DB encryption key from the OS
/// keychain via the prompt registry; emit cascade events along
/// the way; stage the bytes in the SecretStore. Returns the
/// outcome discriminant — bytes never cross FRB.
///
/// Async — round-trips through the bus to the Dart subscriber
/// for the `flutter_secure_storage.read` call. The receiver
/// completes as soon as the subscriber resolves the prompt;
/// the FRB worker frees during the wait so the unlock dialog
/// stays responsive.
Future<DbUnlockOutcome> tierUnlockKeychain() =>
    RustLib.instance.api.crateApiTierUnlockOrchestratorTierUnlockKeychain();

/// KeychainWithPassword tier (L2) — verify the typed user
/// password through the on-disk gate, then read the DB
/// encryption key from the OS keychain. Stages bytes in the
/// SecretStore on success + returns the outcome.
///
/// The Dart caller owns the unlock dialog UI (rate-limit
/// countdown, biometric option); after the user submits the
/// password the caller invokes this orchestrator to drive the
/// verify + key-read + cascade emission in one FRB hop. The
/// dialog interprets `WrongSecret` as "keep open + decrement
/// rate limiter"; `Staged` triggers dialog close + the
/// post-unlock listener cascade.
Future<DbUnlockOutcome> tierUnlockKeychainWithPassword({
  required String password,
}) => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierUnlockKeychainWithPassword(
      password: password,
    );

/// Paranoid tier — derive the DB key from the typed master
/// password via Argon2id; stage in the SecretStore + emit
/// cascade. Returns the outcome.
///
/// Reads the support dir from the pinned singleton — caller
/// must have invoked `master_password_init` at app startup.
Future<DbUnlockOutcome> tierUnlockParanoid({required String password}) =>
    RustLib.instance.api.crateApiTierUnlockOrchestratorTierUnlockParanoid(
      password: password,
    );

/// Hardware tier (L3) — fan out a hardware-vault-unlock prompt
/// to the Dart subscriber + emit cascade events. `pin` is the
/// typed user secret for the password modifier; pass `None`
/// for the passwordless variant. Stages the unsealed bytes in
/// the SecretStore on success.
Future<DbUnlockOutcome> tierUnlockHardware({String? pin}) => RustLib
    .instance
    .api
    .crateApiTierUnlockOrchestratorTierUnlockHardware(pin: pin);

/// Resolve a pending hardware-vault unlock with success bytes.
/// `Ok(Some(bytes))` on a successful unseal; the orchestrator
/// dispatches `UnlockSucceeded` against the tier machine.
bool hardwareVaultUnlockPromptResolve({
  required String promptId,
  required List<int> bytes,
}) => RustLib.instance.api
    .crateApiTierUnlockOrchestratorHardwareVaultUnlockPromptResolve(
      promptId: promptId,
      bytes: bytes,
    );

/// Resolve a pending hardware-vault unlock with the
/// "wrong PIN / user cancel / hardware reported failure"
/// signal. `Ok(None)`. Orchestrator dispatches `UnlockFailed
/// { WrongSecret }`.
bool hardwareVaultUnlockPromptResolveWrong({required String promptId}) =>
    RustLib.instance.api
        .crateApiTierUnlockOrchestratorHardwareVaultUnlockPromptResolveWrong(
          promptId: promptId,
        );

/// Resolve a pending hardware-vault unlock with a plugin
/// error message. Orchestrator dispatches `UnlockFailed
/// { PluginUnavailable { code: message } }`.
bool hardwareVaultUnlockPromptResolveError({
  required String promptId,
  required String message,
}) => RustLib.instance.api
    .crateApiTierUnlockOrchestratorHardwareVaultUnlockPromptResolveError(
      promptId: promptId,
      message: message,
    );

/// Cancel a pending hardware-vault unlock without resolving —
/// used by the Dart subscriber when the unlock dialog is torn
/// down before the platform call returns. Idempotent on a
/// missing id.
void hardwareVaultUnlockPromptCancel({required String promptId}) => RustLib
    .instance
    .api
    .crateApiTierUnlockOrchestratorHardwareVaultUnlockPromptCancel(
      promptId: promptId,
    );

/// First-launch L0 (Plaintext). Dispatches the cascade with an
/// empty staged key so the listener opens the DB unencrypted via
/// `ensureRustDbOpen(key: empty)`. Identical wire shape to
/// `tier_unlock_plaintext` — first-launch and re-unlock converge
/// on the same listener path.
void tierFirstLaunchPlaintext() => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierFirstLaunchPlaintext();

/// First-launch Paranoid. Runs `master_password::enable` (Argon2id
/// + writes `credentials.kdf` + `credentials.verify`), stages the
/// derived key + emits the cascade. Async — Argon2id is
/// CPU-heavy and runs on `spawn_blocking`.
Future<DbUnlockOutcome> tierFirstLaunchParanoid({required String password}) =>
    RustLib.instance.api.crateApiTierUnlockOrchestratorTierFirstLaunchParanoid(
      password: password,
    );

/// First-launch L1 (Keychain). Generates a fresh AES-GCM key,
/// publishes a `KeychainOpPromptRequest { Write }` so the Dart
/// subscriber writes it via `flutter_secure_storage`, stages
/// the bytes + emits the cascade.
Future<DbUnlockOutcome> tierFirstLaunchKeychain() => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierFirstLaunchKeychain();

/// First-launch L2 (KeychainWithPassword). Sets the on-disk gate
/// password (HMAC-SHA-256 salt + verifier files), generates a
/// fresh AES-GCM key, writes it to the OS keychain via the Dart
/// subscriber, stages + emits cascade. On a keychain write
/// failure the gate is rolled back so a retry sees the
/// "not configured" state.
Future<DbUnlockOutcome> tierFirstLaunchKeychainWithPassword({
  required String password,
}) => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierFirstLaunchKeychainWithPassword(
      password: password,
    );

/// Stage [`bytes`] in the SecretStore + emit the unlock cascade
/// for [`tier_wire_name`] without running the per-tier verify
/// step. Used by the biometric fast-path: the bytes come from
/// the OS-managed `BiometricKeyVault` (Dart-side flutter
/// plugin), so the orchestrator's verify is bypassed but the
/// `TierUnlockedListener` still runs the post-unlock cascade
/// (caches, drift open, config persist) off the staged key.
///
/// `tier_wire_name` is the same kebab-case wire name the
/// `tier_machine` exposes (`keychain_with_password`,
/// `hardware`, etc.). Returns `false` on an unrecognised wire
/// name so the Dart caller can fall back to inline injection.
bool tierUnlockBiometricCommit({
  required String tierWireName,
  required List<int> bytes,
}) => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierUnlockBiometricCommit(
      tierWireName: tierWireName,
      bytes: bytes,
    );

/// Cancel an in-flight Keychain (L1) unlock attempt. Dispatches
/// `UnlockFailed { UserCancelled }` so the tier machine flips
/// back to `Locked`. Used by the Dart unlock-flow caller when
/// the L1 cascade is torn down before the keychain read lands
/// (e.g. user invoked a tier reset mid-unlock).
void tierUnlockKeychainCancel() => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierUnlockKeychainCancel();

/// Cancel an in-flight L2 unlock attempt. Dispatches
/// `UnlockFailed { UserCancelled }` so the tier machine flips
/// back to `Locked` when the user dismisses the L2 unlock
/// dialog without submitting a password.
void tierUnlockKeychainWithPasswordCancel() => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierUnlockKeychainWithPasswordCancel();

/// Cancel an in-flight L3 unlock attempt. Dispatches
/// `UnlockFailed { UserCancelled }` so the tier machine flips
/// back to `Locked` when the user dismisses the L3 PIN dialog
/// without submitting.
void tierUnlockHardwareCancel() => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierUnlockHardwareCancel();

/// Cancel an in-flight Paranoid unlock attempt. Dispatches
/// `UnlockFailed { UserCancelled }` so the tier machine flips
/// back to `Locked` when the user dismisses the master-
/// password unlock dialog without submitting. The Dart
/// "forgot password" reset flow also routes through this
/// before kicking off the wipe.
void tierUnlockParanoidCancel() => RustLib.instance.api
    .crateApiTierUnlockOrchestratorTierUnlockParanoidCancel();

@freezed
sealed class DbUnlockOutcome with _$DbUnlockOutcome {
  const DbUnlockOutcome._();

  /// Key staged under `tier.unlock.key` + `UnlockSucceeded`
  /// dispatched. Listener handles the post-unlock cascade.
  const factory DbUnlockOutcome.staged() = DbUnlockOutcome_Staged;

  /// Wrong password / PIN. Dialog stays open for retry.
  const factory DbUnlockOutcome.wrongSecret() = DbUnlockOutcome_WrongSecret;

  /// User cancelled an inner prompt (e.g. hardware vault PIN
  /// sub-dialog). Outer dialog stays open.
  const factory DbUnlockOutcome.cancelled() = DbUnlockOutcome_Cancelled;

  /// Plugin / hardware unrecoverable error. Carries the
  /// machine-readable code for log + diagnostics.
  const factory DbUnlockOutcome.pluginError(String field0) =
      DbUnlockOutcome_PluginError;

  /// On-disk KDF/gate state corrupt. Caller routes through
  /// corruption recovery.
  const factory DbUnlockOutcome.corruption(String field0) =
      DbUnlockOutcome_Corruption;
}
