// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Read the marker payload, or `None` when the marker is absent.
/// Any I/O failure (or a missing pin) short-circuits to `None` so a
/// corrupt marker never blocks startup.
String? tierTransitionMarkerRead() =>
    RustLib.instance.api.crateApiTierTransitionMarkerTierTransitionMarkerRead();

/// Write the marker with [`payload`] as its body. Atomic via tmp +
/// rename + 0600 hardening.
void tierTransitionMarkerWrite({required String payload}) => RustLib
    .instance
    .api
    .crateApiTierTransitionMarkerTierTransitionMarkerWrite(payload: payload);

/// Drop the marker. Idempotent on a missing file.
void tierTransitionMarkerClear() => RustLib.instance.api
    .crateApiTierTransitionMarkerTierTransitionMarkerClear();
