// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Read the marker payload, or `None` when the marker is absent.
/// Any I/O failure short-circuits to `None` so a corrupt marker
/// never blocks startup.
String? tierTransitionMarkerRead({required String supportDir}) =>
    RustLib.instance.api.crateApiTierTransitionMarkerTierTransitionMarkerRead(
      supportDir: supportDir,
    );

/// Write the marker with [`payload`] as its body. Atomic via tmp +
/// rename + 0600 hardening — same shape as the Dart switcher's
/// previous `_writeMarker`.
void tierTransitionMarkerWrite({
  required String supportDir,
  required String payload,
}) =>
    RustLib.instance.api.crateApiTierTransitionMarkerTierTransitionMarkerWrite(
      supportDir: supportDir,
      payload: payload,
    );

/// Drop the marker. Idempotent on a missing file.
void tierTransitionMarkerClear({required String supportDir}) =>
    RustLib.instance.api.crateApiTierTransitionMarkerTierTransitionMarkerClear(
      supportDir: supportDir,
    );
