// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_cfg`, `map_probe`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Run the classified TPM availability probe (device node +
/// binary + `tpm2 createprimary` round-trip). On non-Linux hosts
/// returns `NotLinux` without doing any I/O — the call is cheap
/// to drop into a Dart `if (Platform.isLinux)` guard for safety
/// rather than performance.
///
/// `binary` / `device` / `timeout_ms` mirror the Dart
/// `TpmClient` knobs so unit tests can swap them. Production
/// callers pass `None` for all three to pick up the lfs_core
/// defaults.
Future<DbTpmProbeResult> tpmProbe({
  String? binary,
  String? device,
  BigInt? timeoutMs,
}) => RustLib.instance.api.crateApiTpmTpmProbe(
  binary: binary,
  device: device,
  timeoutMs: timeoutMs,
);

/// Seal `secret` (≤ 128 bytes — TPM2 direct-seal spec ceiling)
/// under a freshly-created primary with `auth_value` as the
/// unseal password. Returns the packed
/// `[u32 BE pub_len][pub][u32 BE priv_len][priv]` blob the Dart
/// vault writes verbatim to `hardware_vault.bin`.
///
/// Plaintext discipline — `secret` and `auth_value` cross FRB
/// once per seal, get written to 0600 temp files inside an RAII
/// work dir that zero-overwrites on drop. The auth-value file is
/// passed via `tpm2-tools`' `file:<path>` argument, never via
/// `hex:<hex>`, so the bytes never appear in
/// `/proc/<pid>/cmdline`.
Future<Uint8List> tpmSeal({
  required List<int> secret,
  required List<int> authValue,
  String? binary,
  String? device,
  BigInt? timeoutMs,
}) => RustLib.instance.api.crateApiTpmTpmSeal(
  secret: secret,
  authValue: authValue,
  binary: binary,
  device: device,
  timeoutMs: timeoutMs,
);

/// Inverse of [`tpm_seal`]. Returns the original secret on
/// successful unseal; format mismatch / wrong auth / missing
/// TPM all surface as `Err(<stderr or io error>)`.
Future<Uint8List> tpmUnseal({
  required List<int> blob,
  required List<int> authValue,
  String? binary,
  String? device,
  BigInt? timeoutMs,
}) => RustLib.instance.api.crateApiTpmTpmUnseal(
  blob: blob,
  authValue: authValue,
  binary: binary,
  device: device,
  timeoutMs: timeoutMs,
);

/// Mirror of `lfs_core::platform::linux::tpm::TpmProbeResult` so
/// the Dart UI can branch on a typed enum instead of a magic
/// number. Keeps the wire-name discipline identical to the Dart
/// `TpmProbeResult` enum case-for-case.
enum DbTpmProbeResult {
  available,
  deviceNodeMissing,
  binaryMissing,
  probeFailed,

  /// Non-Linux host. The Dart enum's `wrongPlatform` slot.
  notLinux,
}
