// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`, `from`

/// Register a fresh state for [`handle`]. Idempotent — a second
/// `create` with the same handle resets the state to default.
void transferConflictCreate({required String handle}) => RustLib.instance.api
    .crateApiTransferConflictTransferConflictCreate(handle: handle);

/// Drop the state for [`handle`]. No-op when the handle is
/// already gone — Dart `dispose` runs unconditionally.
void transferConflictDrop({required String handle}) => RustLib.instance.api
    .crateApiTransferConflictTransferConflictDrop(handle: handle);

/// Cached action for [`handle`], or `None` when the user hasn't
/// checked "apply to all" yet (or the handle is unknown).
DbConflictAction? transferConflictCached({required String handle}) => RustLib
    .instance
    .api
    .crateApiTransferConflictTransferConflictCached(handle: handle);

/// True after the user cancelled the batch behind [`handle`].
bool transferConflictIsCancelled({required String handle}) => RustLib
    .instance
    .api
    .crateApiTransferConflictTransferConflictIsCancelled(handle: handle);

/// Fold a prompt result into the state behind [`handle`] and
/// return the effective action. `apply_to_all` (with a non-cancel
/// action) caches the action for future calls; `Cancel` flips
/// the cancellation flag so subsequent calls short-circuit.
DbConflictAction transferConflictRecordDecision({
  required String handle,
  required DbConflictAction action,
  required bool applyToAll,
}) =>
    RustLib.instance.api.crateApiTransferConflictTransferConflictRecordDecision(
      handle: handle,
      action: action,
      applyToAll: applyToAll,
    );

/// Mirror of `lfs_core::transfer_conflict::ConflictAction` that
/// crosses the FRB boundary.
enum DbConflictAction { skip, keepBoth, replace, cancel }
