// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool_arc`

/// Dispatch a previously-enqueued task into the worker pool.
/// Caller must have already inserted the row through the
/// existing DAO surface (currently exposed by the export /
/// import driver path Dart-side); the pool needs the row to
/// resolve session id + paths via [`TransferQueue::snapshot`].
///
/// Lazy-initialises the worker pool on the first call so the
/// tokio runtime is guaranteed to be alive (the FRB worker
/// hosts a tokio runtime by construction).
Future<void> transferDispatch({required String taskId}) =>
    RustLib.instance.api.crateApiTransferTransferDispatch(taskId: taskId);

/// Flip the cancel flag for a running task. Idempotent on a
/// missing id (task already finished or never dispatched).
/// Returns `true` when a token was actually flipped.
Future<bool> transferCancel({required String taskId}) =>
    RustLib.instance.api.crateApiTransferTransferCancel(taskId: taskId);
