// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Verify `signature` (raw 64-byte Ed25519 signature) over
/// `message` against the pinned release-signing public key(s).
/// Returns `false` for any malformed input — the Dart caller's
/// "no signature match → fail closed" branch is the only
/// negative path it has to handle.
bool updateVerifyReleaseSignature({
  required List<int> message,
  required List<int> signature,
}) => RustLib.instance.api.crateApiUpdateSigningUpdateVerifyReleaseSignature(
  message: message,
  signature: signature,
);
