// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_auth_method`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// Open a WebDAV session.
///
/// `password_secret_id` is the SecretStore id under which the
/// password / bearer token has been staged (typically
/// `session.webdav.<session_id>`). The connect path resolves the
/// id, builds the typed `Credentials`, constructs the
/// `WebDavClient`, and runs a PROPFIND depth=0 against the base
/// URL as a connect probe — so a bad URL or wrong credential
/// surfaces at connect time rather than at the first list.
///
/// `self_signed_fingerprint` is reserved for the future TOFU
/// pinning surface; the current `WebDavClient` constructor relies
/// on the bundled webpki-roots so a non-null value here is a
/// no-op for now. Wiring it through the FRB layer up-front lets
/// the Dart UI persist the value before the transport-side
/// hookup lands.
Future<WebDavConnection> webdavConnect({
  required String baseUrl,
  required String username,
  required String passwordSecretId,
  required String authMethod,
  String? selfSignedFingerprint,
}) => RustLib.instance.api.crateApiWebdavWebdavConnect(
  baseUrl: baseUrl,
  username: username,
  passwordSecretId: passwordSecretId,
  authMethod: authMethod,
  selfSignedFingerprint: selfSignedFingerprint,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WebDavConnection>>
abstract class WebDavConnection implements RustOpaqueInterface {
  /// Recursive size walk. Same depth cap as the SFTP equivalent
  /// (100 levels) — see the `Provider::dir_size` doc for the
  /// rationale.
  Future<BigInt> dirSize({required String path});

  /// Fetch the full body. Buffered into a `Vec<u8>` — large-file
  /// streaming through a FRB `StreamSink` is a follow-up.
  Future<Uint8List> getFull({required String path});

  /// List one directory level. The server returns the listed
  /// directory itself as the first entry per RFC 4918; the
  /// `WebDavProvider` filters it out so this matches SFTP's
  /// "children only" contract.
  Future<List<WebDavDirEntry>> list({required String path});

  /// `MKCOL path`. Single level — no `mkdir -p` semantics; the
  /// Dart caller walks the path if needed.
  Future<void> mkdir({required String path});

  /// Upload `body` to `path`. Single buffered PUT — see
  /// [`get_full`] note on streaming.
  Future<void> putFull({required String path, required List<int> body});

  /// Remove a file or empty collection. Recursive collection
  /// removal is server-defined (most WebDAV servers cascade by
  /// default); the file browser drives one DELETE per entry to
  /// stay portable.
  Future<void> remove({required String path});

  /// `MOVE from to` with `Overwrite: F`. Callers that want to
  /// overwrite delete the target first — same contract as the
  /// SFTP rename.
  Future<void> rename({required String from, required String to});

  /// PROPFIND depth=0 against `path`. Errors when the path does
  /// not exist; callers wanting "exists?" semantics catch and
  /// treat any error as `false`.
  Future<WebDavFileMetadata> stat({required String path});
}

/// One directory entry surfaced by [`WebDavConnection::list`].
/// Field set mirrors the SFTP shape so the Dart `RemoteFileSystem`
/// facade can hand both surfaces the same `FileEntry` row.
class WebDavDirEntry {
  final String name;
  final String path;
  final bool isDir;
  final BigInt size;

  /// Unix epoch milliseconds. `null` on the Dart side when the
  /// server omitted the modification timestamp.
  final PlatformInt64? modifiedUnixMs;

  const WebDavDirEntry({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
    this.modifiedUnixMs,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      modifiedUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavDirEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size &&
          modifiedUnixMs == other.modifiedUnixMs;
}

/// File metadata surfaced by [`WebDavConnection::stat`].
class WebDavFileMetadata {
  final bool isDir;
  final BigInt size;
  final PlatformInt64? modifiedUnixMs;

  const WebDavFileMetadata({
    required this.isDir,
    required this.size,
    this.modifiedUnixMs,
  });

  @override
  int get hashCode => isDir.hashCode ^ size.hashCode ^ modifiedUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavFileMetadata &&
          runtimeType == other.runtimeType &&
          isDir == other.isDir &&
          size == other.size &&
          modifiedUnixMs == other.modifiedUnixMs;
}
