// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

bool wipeHasPending() => RustLib.instance.api.crateApiWipeWipeHasPending();

bool wipeHasAnyState() => RustLib.instance.api.crateApiWipeWipeHasAnyState();

/// Walk every managed file + the logs directory; clear the
/// `.wipe-pending` marker last so a mid-sweep crash leaves a trace
/// the next launch can detect. Async + on the blocking pool —
/// worst-case touches the DB sidecars + the whole logs tree. An
/// empty report is returned when the support dir is unpinned or the
/// runtime is shutting down rather than panicking the FRB worker.
Future<DbFileSweepReport> wipeSweepFiles() =>
    RustLib.instance.api.crateApiWipeWipeSweepFiles();

/// Per-file outcome of a [`wipe_sweep_files`] run. The Dart caller
/// merges this with the keychain / native-vault / overlay results
/// before surfacing the final `WipeReport` to the UI.
class DbFileSweepReport {
  final List<String> deletedFiles;
  final List<String> failedFiles;

  const DbFileSweepReport({
    required this.deletedFiles,
    required this.failedFiles,
  });

  @override
  int get hashCode => deletedFiles.hashCode ^ failedFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbFileSweepReport &&
          runtimeType == other.runtimeType &&
          deletedFiles == other.deletedFiles &&
          failedFiles == other.failedFiles;
}
