// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Walk the canonical OS-keychain alias list and dispatch a delete
/// per key via `lfs_os_security::secure_key_storage::delete`
/// (libsecret on Linux, Keychain Services on Apple, Credential
/// Manager on Windows, AndroidKeyStore JNI on Android). Alias
/// prefix is fixed by `KEY_ALIAS_PREFIX` (external-compat
/// constant — see its docstring).
///
/// Best-effort: a failed delete on one key does not abort the
/// rest. The Dart wrapper surfaces partial failure in the UI.
Future<DbKeychainWipeReport> wipeKeychainRun() =>
    RustLib.instance.api.crateApiWipeKeychainWipeKeychainRun();

/// The canonical key list, exposed so the Dart-side fallback
/// (flutter_test contexts that don't load the FRB native lib)
/// can iterate the same set without re-listing the names. Pure
/// string list — Dart caller maps to its own delete loop.
List<String> wipeKeychainManagedKeys() =>
    RustLib.instance.api.crateApiWipeKeychainWipeKeychainManagedKeys();

/// Per-key wipe outcome, mirrored to FRB so the Dart `WipeReport`
/// can render which slots failed without re-parsing a flat string.
class DbKeychainKeyWipe {
  final String key;

  /// `"deleted"` on success, `"failed: <msg>"` on backend error.
  /// The wipe driver fans out one delete per key without any
  /// user-facing prompt, so cancellation never appears here —
  /// only success / failure shapes ship.
  final String status;

  const DbKeychainKeyWipe({required this.key, required this.status});

  @override
  int get hashCode => key.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbKeychainKeyWipe &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          status == other.status;
}

/// Aggregated result of a `wipe_keychain_run`. `succeeded_count` +
/// `failed_count` lets the Settings UI render a "wiped N of M
/// keychain entries" line without iterating `entries`.
class DbKeychainWipeReport {
  final List<DbKeychainKeyWipe> entries;
  final int succeededCount;
  final int failedCount;

  /// Convenience flag — true when EVERY key wiped successfully.
  /// Mirrors the Dart `WipeReport.keychainPurged` bool.
  final bool allSucceeded;

  const DbKeychainWipeReport({
    required this.entries,
    required this.succeededCount,
    required this.failedCount,
    required this.allSucceeded,
  });

  @override
  int get hashCode =>
      entries.hashCode ^
      succeededCount.hashCode ^
      failedCount.hashCode ^
      allSucceeded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbKeychainWipeReport &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          succeededCount == other.succeededCount &&
          failedCount == other.failedCount &&
          allSucceeded == other.allSucceeded;
}
