// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_wizard_tier`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Translate the wizard's (`tier` + password + biometric + typed
/// secret) shape into the persistence-layer tier + typed secret the
/// `_applyTierChange` cascade expects. Returns `Err` for an unknown
/// `tier_wire_name` so the misuse surfaces instead of silently
/// picking a wrong tier.
DbMappedSetupChoice securityMapWizardChoice({
  required String tierWireName,
  required bool password,
  required bool biometric,
  String? typedSecret,
}) => RustLib.instance.api.crateApiWizardSetupSecurityMapWizardChoice(
  tierWireName: tierWireName,
  password: password,
  biometric: biometric,
  typedSecret: typedSecret,
);

/// FRB-side mirror of `lfs_core::security::MappedSetupChoice`. The
/// `tier_wire_name` round-trips through the existing
/// `SecurityTier::from_wire_name` Dart-side; only one of
/// `master_password` / `short_password` / `pin` is ever
/// `Some(_)` per call (see [`map_wizard_choice`]'s contract).
class DbMappedSetupChoice {
  final String tierWireName;
  final bool password;
  final bool biometric;
  final bool biometricShortcut;
  final int pinLength;
  final String? masterPassword;
  final String? shortPassword;
  final String? pin;

  const DbMappedSetupChoice({
    required this.tierWireName,
    required this.password,
    required this.biometric,
    required this.biometricShortcut,
    required this.pinLength,
    this.masterPassword,
    this.shortPassword,
    this.pin,
  });

  @override
  int get hashCode =>
      tierWireName.hashCode ^
      password.hashCode ^
      biometric.hashCode ^
      biometricShortcut.hashCode ^
      pinLength.hashCode ^
      masterPassword.hashCode ^
      shortPassword.hashCode ^
      pin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbMappedSetupChoice &&
          runtimeType == other.runtimeType &&
          tierWireName == other.tierWireName &&
          password == other.password &&
          biometric == other.biometric &&
          biometricShortcut == other.biometricShortcut &&
          pinLength == other.pinLength &&
          masterPassword == other.masterPassword &&
          shortPassword == other.shortPassword &&
          pin == other.pin;
}
